name: "Build Content Pack"
description: "Builds with cobra-tools and packages the Content Pack artifact"

inputs:
  python_version:
    description: "Python version to use for the build"
    required: false
    default: "3.11"
  cobra_tools_ref:
    description: "Commit hash or branch to checkout for cobra-tools. Defaults to master if omitted."
    required: false
    default: "master"
  artifact_name:
    description: "Name to use when uploading the build artifact. If omitted, the artifact will not be uploaded."
    required: false

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python_version }}

    - name: Checkout cobratools
      uses: actions/checkout@v4
      with:
        repository: OpenNaja/cobra-tools
        path: cobra-tools
        ref: ${{ inputs.cobra_tools_ref }}

    - name: Install cobratools with GUI extras
      shell: bash
      run: |
        cd cobra-tools
        python -m pip install --upgrade pip
        pip install ".[gui]"

    # Needed as specific mods might need specific packing settings.
    - name: Move config if exists into Cobra Tools
      shell: bash
      run: |
        if [ -f "${{ github.workspace }}/Build/config.json" ]; then
          cp "${{ github.workspace }}/Build/config.json" "${{ github.workspace }}/cobra-tools/config.json"
        fi

    - name: Run build script
      shell: bash
      run: python Build/build.py "${{ github.workspace }}/cobra-tools" "./Manifest.xml"

    - name: Remove cobra tools
      shell: bash
      run: rm -rf cobra-tools

    - name: Run package script
      if: ${{ inputs.artifact_name != '' }}
      shell: bash
      run: python Build/package.py . ${{ inputs.artifact_name }}.zip

    - name: Upload build artifact
      if: ${{ inputs.artifact_name != '' }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact_name }}
        path: ${{ inputs.artifact_name }}.zip
