---
--- NOTE: THIS FILE IS AUTOGENERATED.
--- PLEASE NOTE THAT THIS IS SUBJECT TO CHANGE
--- BETWEEN EACH VERSION. IF BROKEN BY AN UPDATE,
--- REGENERATE VIA THE SCRIPT IN SQLBINDINGFOLDER.
--- 

---@class forgeutils.internal.database.constants.TrackedRideCars
--- Note: Autogenerated!
--- This is a class containing generated
--- lua constants from the TrackedRideCars database.
local TrackedRideCars = {}

---
--- Constants for: WhichCars
---

TrackedRideCars.WhichCars_Front = "Front"
TrackedRideCars.WhichCars_Middle = "Middle"
TrackedRideCars.WhichCars_Rear = "Rear"

---
--- Constants for: LuaScoringModules
---

TrackedRideCars.LuaScoringModules_CascadeScoring = "CascadeScoring"
TrackedRideCars.LuaScoringModules_CoasterScoring = "CoasterScoring"
TrackedRideCars.LuaScoringModules_DefaultScoring = "DefaultScoring"
TrackedRideCars.LuaScoringModules_HuntsmanTrackedRideScoring = "HuntsmanTrackedRideScoring"
TrackedRideCars.LuaScoringModules_LogFlumeScoring = "LogFlumeScoring"
TrackedRideCars.LuaScoringModules_NonInvertedCoasterScoring = "NonInvertedCoasterScoring"
TrackedRideCars.LuaScoringModules_NonInvertedCoasterScoringSlow = "NonInvertedCoasterScoringSlow"
TrackedRideCars.LuaScoringModules_PoweredTrackedRideScoring = "PoweredTrackedRideScoring"
TrackedRideCars.LuaScoringModules_SwimsuitFlumeScoring = "SwimsuitFlumeScoring"
TrackedRideCars.LuaScoringModules_TransportRideScoring = "TransportRideScoring"

---
--- Constants for: AudioChainLiftPrefixes
---

TrackedRideCars.AudioChainLiftPrefixes_BigM_WaterCoaster = "BigM_WaterCoaster"
TrackedRideCars.AudioChainLiftPrefixes_FWL = "FWL"
TrackedRideCars.AudioChainLiftPrefixes_FWL_Return = "FWL_Return"
TrackedRideCars.AudioChainLiftPrefixes_Hunts = "Hunts"
TrackedRideCars.AudioChainLiftPrefixes_Hyb = "Hyb"
TrackedRideCars.AudioChainLiftPrefixes_Knot_GhostTrain = "Knot_GhostTrain"
TrackedRideCars.AudioChainLiftPrefixes_MS_StarLoop = "MS_StarLoop"
TrackedRideCars.AudioChainLiftPrefixes_Mse = "Mse"
TrackedRideCars.AudioChainLiftPrefixes_Mtl = "Mtl"
TrackedRideCars.AudioChainLiftPrefixes_MtlHvy = "MtlHvy"
TrackedRideCars.AudioChainLiftPrefixes_MtlVer = "MtlVer"
TrackedRideCars.AudioChainLiftPrefixes_Outa_SitDown = "Outa_SitDown"
TrackedRideCars.AudioChainLiftPrefixes_Outa_Wing = "Outa_Wing"
TrackedRideCars.AudioChainLiftPrefixes_Slide = "Slide"
TrackedRideCars.AudioChainLiftPrefixes_SlideConveyor = "SlideConveyor"
TrackedRideCars.AudioChainLiftPrefixes_Trident = "Trident"
TrackedRideCars.AudioChainLiftPrefixes_Vector_InvertedBoom = "Vector_InvertedBoom"
TrackedRideCars.AudioChainLiftPrefixes_Water = "Water"
TrackedRideCars.AudioChainLiftPrefixes_Wood = "Wood"

---
--- Constants for: AudioBrakePrefixes
---

TrackedRideCars.AudioBrakePrefixes_Fri = "Fri"
TrackedRideCars.AudioBrakePrefixes_Mag = "Mag"
TrackedRideCars.AudioBrakePrefixes_SFri = "SFri"
TrackedRideCars.AudioBrakePrefixes_SlideBrake = "SlideBrake"
TrackedRideCars.AudioBrakePrefixes_WdFr = "WdFr"

return TrackedRideCars
