---
--- NOTE: THIS FILE IS AUTOGENERATED.
--- PLEASE NOTE THAT THIS IS SUBJECT TO CHANGE
--- BETWEEN EACH VERSION. IF BROKEN BY AN UPDATE,
--- REGENERATE VIA THE EXT FOLDER.
--- 
local global = _G
local ipairs = global.ipairs
local DatabaseUtils = require("forgeutils.internal.database.databaseutils")

local logger = require("forgeutils.logger").Get("Audio")

---@class forgeutils.internal.database.Audio
--- Note: Autogenerated!
--- This is a generated lua binding layer for the Audio database.
local Audio = {}

---@private
--- This method is called after data is merged
Audio.InsertToDBs = function()
    Audio.BindPreparedStatements()
end

Audio.tPreparedStatements = {
    "Audio_AmbienceCategories", 
    "Audio_AmbienceEventToCategoryMap", 
    "Audio_Categories", 
    "Audio_CoasterMusicEventToCategoryMap", 
    "Audio_CoasterMusicEvents", 
    "Audio_ContentPacks", 
    "Audio_DiegeticMusicEventToCategoryMap", 
    "Audio_DiegeticMusicEvents", 
    "Audio_EventToCategoryMap", 
    "Audio_FlatrideMusicEventToCategoryMap", 
    "Audio_FlatrideMusicEvents", 
    "Audio_GunSoundCategories", 
    "Audio_GunSoundEventToCategoryMap", 
    "Audio_GunSoundEvents", 
    "Audio_MusicCategories", 
    "Audio_PlaceableAmbienceEvents", 
    "Audio_PlaceableTriggeredEvents", 
    "Audio_SpeakerMusicEventToCategoryMap", 
    "Audio_SpeakerMusicEvents"
}

---@private
function Audio.BindPreparedStatements()
    logger:DebugQuery("BindPreparedStatements()")
    for _, filename in ipairs(Audio.tPreparedStatements) do
        DatabaseUtils.BindPreparedStatement("Audio", filename)
    end
end


--- Note: Autogenerated.
---@param Name string Common Values = "Aquatic", "Electronic", "GreekMythos", "Legacy", "Orchestral". 
function Audio.AmbienceCategories__Insert(Name)
    DatabaseUtils.ExecuteQuery("AmbienceCategories", "AmbienceCategories__Insert", {Name}, 1)
end

--- Note: Autogenerated.
---@param Name string Common Values = "Aquatic", "Electronic", "GreekMythos", "Legacy", "Orchestral". (Lookup Key)
---@param TextSymbol string|nil Common Values = "Music_Heading_Aquatic", "Music_Heading_Electronic", "Music_Heading_GreekMythos", "Music_Heading_Legacy", "Music_Heading_Orchestral". 
function Audio.AmbienceCategories__Update__TextSymbol(Name, TextSymbol)
    DatabaseUtils.ExecuteQuery("AmbienceCategories", "AmbienceCategories__Update__TextSymbol", {Name, TextSymbol}, 2)
end

--- Note: Autogenerated.
---@param EventName string Common Values = "AMB_Baths", "AMB_Battlefield", "AMB_BubblyUnderwater", "AMB_CocktailParty", "AMB_CrumblyTemple". 
---@param Category string Common Values = "GreekMythos", "Viking", "Aquatic", "Spooky", "Resort". 
function Audio.AmbienceEventToCategoryMap__Insert(EventName, Category)
    DatabaseUtils.ExecuteQuery("AmbienceEventToCategoryMap", "AmbienceEventToCategoryMap__Insert", {EventName, Category}, 2)
end

--- Note: Autogenerated.
---@param EventName string Common Values = "AMB_Baths", "AMB_Battlefield", "AMB_BubblyUnderwater", "AMB_CocktailParty", "AMB_CrumblyTemple". (Lookup Key)
---@param Category string Common Values = "GreekMythos", "Viking", "Aquatic", "Spooky", "Resort". 
function Audio.AmbienceEventToCategoryMap__Update__Category(EventName, Category)
    DatabaseUtils.ExecuteQuery("AmbienceEventToCategoryMap", "AmbienceEventToCategoryMap__Update__Category", {EventName, Category}, 2)
end

--- Note: Autogenerated.
---@param Name string Common Values = "Alarms", "Announcement", "Aquatic", "Creatures", "Electronic". 
function Audio.Categories__Insert(Name)
    DatabaseUtils.ExecuteQuery("Categories", "Categories__Insert", {Name}, 1)
end

--- Note: Autogenerated.
---@param Name string Common Values = "Alarms", "Announcement", "Aquatic", "Creatures", "Electronic". (Lookup Key)
---@param TextSymbol string|nil Common Values = "TriggeredSFX_Alarms_Heading", "TriggeredSFX_Announcement_Heading", "TriggeredSFX_Aquatic_Heading", "TriggeredSFX_Creatures_Heading", "TriggeredSFX_Electronic_Heading". 
function Audio.Categories__Update__TextSymbol(Name, TextSymbol)
    DatabaseUtils.ExecuteQuery("Categories", "Categories__Update__TextSymbol", {Name, TextSymbol}, 2)
end

--- Note: Autogenerated.
---@param EventName string 
---@param Category string 
function Audio.CoasterMusicEventToCategoryMap__Insert(EventName, Category)
    DatabaseUtils.ExecuteQuery("CoasterMusicEventToCategoryMap", "CoasterMusicEventToCategoryMap__Insert", {EventName, Category}, 2)
end

--- Note: Autogenerated.
---@param EventName string (Lookup Key)
---@param Category string 
function Audio.CoasterMusicEventToCategoryMap__Update__Category(EventName, Category)
    DatabaseUtils.ExecuteQuery("CoasterMusicEventToCategoryMap", "CoasterMusicEventToCategoryMap__Update__Category", {EventName, Category}, 2)
end

--- Note: Autogenerated.
---@param EventName string 
function Audio.CoasterMusicEvents__Insert(EventName)
    DatabaseUtils.ExecuteQuery("CoasterMusicEvents", "CoasterMusicEvents__Insert", {EventName}, 1)
end

--- Note: Autogenerated.
---@param EventName string (Lookup Key)
---@param ContentPack string Default = BaseGame. 
function Audio.CoasterMusicEvents__Update__ContentPack(EventName, ContentPack)
    DatabaseUtils.ExecuteQuery("CoasterMusicEvents", "CoasterMusicEvents__Update__ContentPack", {EventName, ContentPack}, 2)
end

--- Note: Autogenerated.
---@param Name string Common Values = "BaseGame", "Deluxe", "PermanentLocked", "Preorder". 
---@param EnumValue integer Common Values = 0, 1, 2, 4. 
function Audio.ContentPacks__Insert(Name, EnumValue)
    DatabaseUtils.ExecuteQuery("ContentPacks", "ContentPacks__Insert", {Name, EnumValue}, 2)
end

--- Note: Autogenerated.
---@param Name string Common Values = "BaseGame", "Deluxe", "PermanentLocked", "Preorder". (Lookup Key)
---@param EnumValue integer Common Values = 0, 1, 2, 4. 
function Audio.ContentPacks__Update__EnumValue(Name, EnumValue)
    DatabaseUtils.ExecuteQuery("ContentPacks", "ContentPacks__Update__EnumValue", {Name, EnumValue}, 2)
end

--- Note: Autogenerated.
---@param EventName string Common Values = "Aqua_01", "Aqua_02", "Aqua_03", "Aqua_04", "BandMusic_01". 
---@param Category string Common Values = "Legacy", "Orchestral", "Western", "Electronic", "Pop". 
function Audio.DiegeticMusicEventToCategoryMap__Insert(EventName, Category)
    DatabaseUtils.ExecuteQuery("DiegeticMusicEventToCategoryMap", "DiegeticMusicEventToCategoryMap__Insert", {EventName, Category}, 2)
end

--- Note: Autogenerated.
---@param EventName string Common Values = "Aqua_01", "Aqua_02", "Aqua_03", "Aqua_04", "BandMusic_01". (Lookup Key)
---@param Category string Common Values = "Legacy", "Orchestral", "Western", "Electronic", "Pop". 
function Audio.DiegeticMusicEventToCategoryMap__Update__Category(EventName, Category)
    DatabaseUtils.ExecuteQuery("DiegeticMusicEventToCategoryMap", "DiegeticMusicEventToCategoryMap__Update__Category", {EventName, Category}, 2)
end

--- Note: Autogenerated.
---@param EventName string Common Values = "Aqua_01", "Aqua_02", "Aqua_03", "Aqua_04", "BandMusic_01". 
function Audio.DiegeticMusicEvents__Insert(EventName)
    DatabaseUtils.ExecuteQuery("DiegeticMusicEvents", "DiegeticMusicEvents__Insert", {EventName}, 1)
end

--- Note: Autogenerated.
---@param EventName string Common Values = "Aqua_01", "Aqua_02", "Aqua_03", "Aqua_04", "BandMusic_01". (Lookup Key)
---@param ContentPack string Default = BaseGame. Common Values = "BaseGame". 
function Audio.DiegeticMusicEvents__Update__ContentPack(EventName, ContentPack)
    DatabaseUtils.ExecuteQuery("DiegeticMusicEvents", "DiegeticMusicEvents__Update__ContentPack", {EventName, ContentPack}, 2)
end

--- Note: Autogenerated.
---@param EventName string Common Values = "CPT_TSFX_Adventure_BoatBell", "CPT_TSFX_Adventure_TempleCollapse", "CPT_TSFX_Creatures_AnimalRoar", "CPT_TSFX_Creatures_AnimalWolf", "CPT_TSFX_Creatures_Kraken". 
---@param Category string Common Values = "Musical", "Legacy", "GreekMythos", "Viking", "Aquatic". 
function Audio.EventToCategoryMap__Insert(EventName, Category)
    DatabaseUtils.ExecuteQuery("EventToCategoryMap", "EventToCategoryMap__Insert", {EventName, Category}, 2)
end

--- Note: Autogenerated.
---@param EventName string Common Values = "CPT_TSFX_Adventure_BoatBell", "CPT_TSFX_Adventure_TempleCollapse", "CPT_TSFX_Creatures_AnimalRoar", "CPT_TSFX_Creatures_AnimalWolf", "CPT_TSFX_Creatures_Kraken". (Lookup Key)
---@param Category string Common Values = "Musical", "Legacy", "GreekMythos", "Viking", "Aquatic". 
function Audio.EventToCategoryMap__Update__Category(EventName, Category)
    DatabaseUtils.ExecuteQuery("EventToCategoryMap", "EventToCategoryMap__Update__Category", {EventName, Category}, 2)
end

--- Note: Autogenerated.
---@param EventName string 
---@param Category string 
function Audio.FlatrideMusicEventToCategoryMap__Insert(EventName, Category)
    DatabaseUtils.ExecuteQuery("FlatrideMusicEventToCategoryMap", "FlatrideMusicEventToCategoryMap__Insert", {EventName, Category}, 2)
end

--- Note: Autogenerated.
---@param EventName string (Lookup Key)
---@param Category string 
function Audio.FlatrideMusicEventToCategoryMap__Update__Category(EventName, Category)
    DatabaseUtils.ExecuteQuery("FlatrideMusicEventToCategoryMap", "FlatrideMusicEventToCategoryMap__Update__Category", {EventName, Category}, 2)
end

--- Note: Autogenerated.
---@param EventName string Common Values = "BehemothSwing360", "BumperCarMedley", "CLD", "CSL", "Chairoplane". 
function Audio.FlatrideMusicEvents__Insert(EventName)
    DatabaseUtils.ExecuteQuery("FlatrideMusicEvents", "FlatrideMusicEvents__Insert", {EventName}, 1)
end

--- Note: Autogenerated.
---@param EventName string Common Values = "BehemothSwing360", "BumperCarMedley", "CLD", "CSL", "Chairoplane". (Lookup Key)
---@param ContentPack string Default = BaseGame. Common Values = "BaseGame". 
function Audio.FlatrideMusicEvents__Update__ContentPack(EventName, ContentPack)
    DatabaseUtils.ExecuteQuery("FlatrideMusicEvents", "FlatrideMusicEvents__Update__ContentPack", {EventName, ContentPack}, 2)
end

--- Note: Autogenerated.
---@param Name string|nil 
---@param TextSymbol string|nil 
function Audio.GunSoundCategories__Insert(Name, TextSymbol)
    DatabaseUtils.ExecuteQuery("GunSoundCategories", "GunSoundCategories__Insert", {Name, TextSymbol}, 2)
end

--- Note: Autogenerated.
---@param Name string|nil (Lookup Key)
---@param TextSymbol string|nil 
function Audio.GunSoundCategories__Update__TextSymbol(Name, TextSymbol)
    DatabaseUtils.ExecuteQuery("GunSoundCategories", "GunSoundCategories__Update__TextSymbol", {Name, TextSymbol}, 2)
end

--- Note: Autogenerated.
---@param EventName string|nil 
---@param Category string|nil 
function Audio.GunSoundEventToCategoryMap__Insert(EventName, Category)
    DatabaseUtils.ExecuteQuery("GunSoundEventToCategoryMap", "GunSoundEventToCategoryMap__Insert", {EventName, Category}, 2)
end

--- Note: Autogenerated.
---@param EventName string|nil (Lookup Key)
---@param Category string|nil 
function Audio.GunSoundEventToCategoryMap__Update__Category(EventName, Category)
    DatabaseUtils.ExecuteQuery("GunSoundEventToCategoryMap", "GunSoundEventToCategoryMap__Update__Category", {EventName, Category}, 2)
end

--- Note: Autogenerated.
---@param EventName string|nil 
---@param ContentPack string|nil 
function Audio.GunSoundEvents__Insert(EventName, ContentPack)
    DatabaseUtils.ExecuteQuery("GunSoundEvents", "GunSoundEvents__Insert", {EventName, ContentPack}, 2)
end

--- Note: Autogenerated.
---@param EventName string|nil (Lookup Key)
---@param ContentPack string|nil 
function Audio.GunSoundEvents__Update__ContentPack(EventName, ContentPack)
    DatabaseUtils.ExecuteQuery("GunSoundEvents", "GunSoundEvents__Update__ContentPack", {EventName, ContentPack}, 2)
end

--- Note: Autogenerated.
---@param Name string Common Values = "Aquatic", "Electronic", "GreekMythos", "Legacy", "Orchestral". 
function Audio.MusicCategories__Insert(Name)
    DatabaseUtils.ExecuteQuery("MusicCategories", "MusicCategories__Insert", {Name}, 1)
end

--- Note: Autogenerated.
---@param Name string Common Values = "Aquatic", "Electronic", "GreekMythos", "Legacy", "Orchestral". (Lookup Key)
---@param TextSymbol string|nil Common Values = "Music_Heading_Aquatic", "Music_Heading_Electronic", "Music_Heading_GreekMythos", "Music_Heading_Legacy", "Music_Heading_Orchestral". 
function Audio.MusicCategories__Update__TextSymbol(Name, TextSymbol)
    DatabaseUtils.ExecuteQuery("MusicCategories", "MusicCategories__Update__TextSymbol", {Name, TextSymbol}, 2)
end

--- Note: Autogenerated.
---@param EventName string Common Values = "AMB_Baths", "AMB_Battlefield", "AMB_BubblyUnderwater", "AMB_CocktailParty", "AMB_CrumblyTemple". 
function Audio.PlaceableAmbienceEvents__Insert(EventName)
    DatabaseUtils.ExecuteQuery("PlaceableAmbienceEvents", "PlaceableAmbienceEvents__Insert", {EventName}, 1)
end

--- Note: Autogenerated.
---@param EventName string Common Values = "AMB_Baths", "AMB_Battlefield", "AMB_BubblyUnderwater", "AMB_CocktailParty", "AMB_CrumblyTemple". (Lookup Key)
---@param ContentPack string Default = BaseGame. Common Values = "BaseGame". 
function Audio.PlaceableAmbienceEvents__Update__ContentPack(EventName, ContentPack)
    DatabaseUtils.ExecuteQuery("PlaceableAmbienceEvents", "PlaceableAmbienceEvents__Update__ContentPack", {EventName, ContentPack}, 2)
end

--- Note: Autogenerated.
---@param EventName string Common Values = "CPT_TSFX_Adventure_BoatBell", "CPT_TSFX_Adventure_TempleCollapse", "CPT_TSFX_Creatures_AnimalRoar", "CPT_TSFX_Creatures_AnimalWolf", "CPT_TSFX_Creatures_Kraken". 
function Audio.PlaceableTriggeredEvents__Insert(EventName)
    DatabaseUtils.ExecuteQuery("PlaceableTriggeredEvents", "PlaceableTriggeredEvents__Insert", {EventName}, 1)
end

--- Note: Autogenerated.
---@param EventName string Common Values = "CPT_TSFX_Adventure_BoatBell", "CPT_TSFX_Adventure_TempleCollapse", "CPT_TSFX_Creatures_AnimalRoar", "CPT_TSFX_Creatures_AnimalWolf", "CPT_TSFX_Creatures_Kraken". (Lookup Key)
---@param ContentPack string Default = BaseGame. Common Values = "BaseGame". 
function Audio.PlaceableTriggeredEvents__Update__ContentPack(EventName, ContentPack)
    DatabaseUtils.ExecuteQuery("PlaceableTriggeredEvents", "PlaceableTriggeredEvents__Update__ContentPack", {EventName, ContentPack}, 2)
end

--- Note: Autogenerated.
---@param EventName string Common Values = "CPT_TSFX_Adventure_BoatBell", "CPT_TSFX_Adventure_TempleCollapse", "CPT_TSFX_Creatures_AnimalRoar", "CPT_TSFX_Creatures_AnimalWolf", "CPT_TSFX_Creatures_Kraken". (Lookup Key)
---@param SupportsPitchShift boolean Default = 0. Common Values = 1. 
function Audio.PlaceableTriggeredEvents__Update__SupportsPitchShift(EventName, SupportsPitchShift)
    DatabaseUtils.ExecuteQuery("PlaceableTriggeredEvents", "PlaceableTriggeredEvents__Update__SupportsPitchShift", {EventName, SupportsPitchShift}, 2)
end

--- Note: Autogenerated.
---@param EventName string 
---@param Category string 
function Audio.SpeakerMusicEventToCategoryMap__Insert(EventName, Category)
    DatabaseUtils.ExecuteQuery("SpeakerMusicEventToCategoryMap", "SpeakerMusicEventToCategoryMap__Insert", {EventName, Category}, 2)
end

--- Note: Autogenerated.
---@param EventName string (Lookup Key)
---@param Category string 
function Audio.SpeakerMusicEventToCategoryMap__Update__Category(EventName, Category)
    DatabaseUtils.ExecuteQuery("SpeakerMusicEventToCategoryMap", "SpeakerMusicEventToCategoryMap__Update__Category", {EventName, Category}, 2)
end

--- Note: Autogenerated.
---@param EventName string 
function Audio.SpeakerMusicEvents__Insert(EventName)
    DatabaseUtils.ExecuteQuery("SpeakerMusicEvents", "SpeakerMusicEvents__Insert", {EventName}, 1)
end

--- Note: Autogenerated.
---@param EventName string (Lookup Key)
---@param ContentPack string Default = BaseGame. 
function Audio.SpeakerMusicEvents__Update__ContentPack(EventName, ContentPack)
    DatabaseUtils.ExecuteQuery("SpeakerMusicEvents", "SpeakerMusicEvents__Update__ContentPack", {EventName, ContentPack}, 2)
end


return Audio
