---
--- NOTE: THIS FILE IS AUTOGENERATED.
--- PLEASE NOTE THAT THIS IS SUBJECT TO CHANGE
--- BETWEEN EACH VERSION. IF BROKEN BY AN UPDATE,
--- REGENERATE VIA THE EXT FOLDER.
--- 
local global = _G
local ipairs = global.ipairs
local DatabaseUtils = require("forgeutils.internal.database.databaseutils")

local logger = require("forgeutils.logger").Get("ModularScenery")

---@class forgeutils.internal.database.ModularScenery
--- Note: Autogenerated!
--- This is a generated lua binding layer for the ModularScenery database.
local ModularScenery = {}

---@private
--- This method is called after data is merged
ModularScenery.InsertToDBs = function()
    ModularScenery.BindPreparedStatements()
end

ModularScenery.tPreparedStatements = {
    "ModularScenery_Blueprint_Tags", 
    "ModularScenery_BrowserCategories", 
    "ModularScenery_BrowserFilters", 
    "ModularScenery_ComplexTypes", 
    "ModularScenery_ContentPacks", 
    "ModularScenery_DevTransitionList", 
    "ModularScenery_FacilityProps", 
    "ModularScenery_FireworkEffects", 
    "ModularScenery_GridProps", 
    "ModularScenery_LocalGridAlignmentStyle", 
    "ModularScenery_Metadata_Tags", 
    "ModularScenery_ModularSceneryParts", 
    "ModularScenery_PartComplexMembers", 
    "ModularScenery_PartControlPoints", 
    "ModularScenery_PartDataPrefabs", 
    "ModularScenery_PathExtraProps", 
    "ModularScenery_PathExtraSnapType", 
    "ModularScenery_PathProps", 
    "ModularScenery_SceneryScaling", 
    "ModularScenery_Simulation", 
    "ModularScenery_SnapEdgePartData", 
    "ModularScenery_TagGroups", 
    "ModularScenery_TagGroupsDefinition", 
    "ModularScenery_TagGroupsToBrowserTabs", 
    "ModularScenery_TagSet", 
    "ModularScenery_ThemeNames", 
    "ModularScenery_Theming", 
    "ModularScenery_TriggerTargetProps", 
    "ModularScenery_UIData", 
    "ModularScenery_UIPartOrdering", 
    "ModularScenery_UtilityConnection", 
    "ModularScenery_UtilityConsumer", 
    "ModularScenery_UtilityDistribution", 
    "ModularScenery_UtilityProduction", 
    "ModularScenery_UtilityTypes", 
    "ModularScenery_WaterCleanliness"
}

---@private
function ModularScenery.BindPreparedStatements()
    logger:DebugQuery("BindPreparedStatements()")
    for _, filename in ipairs(ModularScenery.tPreparedStatements) do
        DatabaseUtils.BindPreparedStatement("ModularScenery", filename)
    end
end


--- Note: Autogenerated.
---@param SceneryPart string Common Values = "NAT_Aquatic_WaterLily_Common_01", "NAT_Aquatic_WaterLily_Common_02", "NAT_Aquatic_WaterLily_Common_03", "NAT_Aquatic_WaterLily_Common_04", "NAT_Bush_Bramble_Medium_01". 
---@param Tag string Common Values = "Filter_Theme_PlanetCoaster", "Filter_Theme_Resort", "Filter_Theme_Mythology", "Filter_Theme_Viking", "Filter_Theme_Western". 
function ModularScenery.Blueprint_Tags__Insert(SceneryPart, Tag)
    DatabaseUtils.ExecuteQuery("Blueprint_Tags", "Blueprint_Tags__Insert", {SceneryPart, Tag}, 2)
end

--- Note: Autogenerated.
---@param SceneryPart string Common Values = "NAT_Aquatic_WaterLily_Common_01", "NAT_Aquatic_WaterLily_Common_02", "NAT_Aquatic_WaterLily_Common_03", "NAT_Aquatic_WaterLily_Common_04", "NAT_Bush_Bramble_Medium_01". (Lookup Key)
---@param Tag string Common Values = "Filter_Theme_PlanetCoaster", "Filter_Theme_Resort", "Filter_Theme_Mythology", "Filter_Theme_Viking", "Filter_Theme_Western". 
function ModularScenery.Blueprint_Tags__Update__Tag(SceneryPart, Tag)
    DatabaseUtils.ExecuteQuery("Blueprint_Tags", "Blueprint_Tags__Update__Tag", {SceneryPart, Tag}, 2)
end

--- Note: Autogenerated.
---@param Label string Common Values = "Browser_Cat_Shop_Drink", "Browser_Cat_Shop_Food", "Browser_Cat_Shop_Gift", "Browser_SubCat_Walls_Arches", "HUD_ShopMenu_Create". 
function ModularScenery.BrowserCategories__Insert(Label)
    DatabaseUtils.ExecuteQuery("BrowserCategories", "BrowserCategories__Insert", {Label}, 1)
end

--- Note: Autogenerated.
---@param CategoryID integer|nil Common Values = 1, 3, 4, 5, 7. (Lookup Key)
---@param CategoryTag string|nil Common Values = nil, "Filter_BuildingProps_Spire", "Menu_Building_Arches_Archway", "Menu_Building_Decorations", "Menu_Building_Doors". 
function ModularScenery.BrowserCategories__Update__CategoryTag(CategoryID, CategoryTag)
    DatabaseUtils.ExecuteQuery("BrowserCategories", "BrowserCategories__Update__CategoryTag", {CategoryID, CategoryTag}, 2)
end

--- Note: Autogenerated.
---@param CategoryID integer|nil Common Values = 1, 3, 4, 5, 7. (Lookup Key)
---@param Label string Common Values = "Browser_Cat_Shop_Drink", "Browser_Cat_Shop_Food", "Browser_Cat_Shop_Gift", "Browser_SubCat_Walls_Arches", "HUD_ShopMenu_Create". 
function ModularScenery.BrowserCategories__Update__Label(CategoryID, Label)
    DatabaseUtils.ExecuteQuery("BrowserCategories", "BrowserCategories__Update__Label", {CategoryID, Label}, 2)
end

--- Note: Autogenerated.
---@param CategoryID integer|nil Common Values = 1, 3, 4, 5, 7. (Lookup Key)
---@param Icon string|nil Common Values = "HUDIconShops", "objectBrowserShopCounter", "categoryBrowserMenu_Create", "objectBrowserArches", "objectBrowserFramework". 
function ModularScenery.BrowserCategories__Update__Icon(CategoryID, Icon)
    DatabaseUtils.ExecuteQuery("BrowserCategories", "BrowserCategories__Update__Icon", {CategoryID, Icon}, 2)
end

--- Note: Autogenerated.
---@param CategoryID integer|nil Common Values = 1, 3, 4, 5, 7. (Lookup Key)
---@param ParentID integer|nil Common Values = 4, 3, 999, 1, 46. 
function ModularScenery.BrowserCategories__Update__ParentID(CategoryID, ParentID)
    DatabaseUtils.ExecuteQuery("BrowserCategories", "BrowserCategories__Update__ParentID", {CategoryID, ParentID}, 2)
end

--- Note: Autogenerated.
---@param CategoryID integer|nil Common Values = 1, 3, 4, 5, 7. (Lookup Key)
---@param Ordering integer Default = 1. Common Values = 2, 3, 1, 4, 5. 
function ModularScenery.BrowserCategories__Update__Ordering(CategoryID, Ordering)
    DatabaseUtils.ExecuteQuery("BrowserCategories", "BrowserCategories__Update__Ordering", {CategoryID, Ordering}, 2)
end

--- Note: Autogenerated.
---@param CategoryID integer|nil Common Values = 1, 3, 4, 5, 7. (Lookup Key)
---@param AudioOpenSound string|nil Common Values = "Gui_MenuBarTab_SceneryPropsMisc", "Gui_MenuBarTab_SceneryPropsAll", "Gui_Select_Create_Scenery_Cameras", "Gui_MenuBarTab_BuildingsPathRoofsFlat", "Gui_MenuBarTab_BuildingsWallsArches". 
function ModularScenery.BrowserCategories__Update__AudioOpenSound(CategoryID, AudioOpenSound)
    DatabaseUtils.ExecuteQuery("BrowserCategories", "BrowserCategories__Update__AudioOpenSound", {CategoryID, AudioOpenSound}, 2)
end

--- Note: Autogenerated.
---@param CategoryID integer|nil Common Values = 1, 3, 4, 5, 7. (Lookup Key)
---@param UGCWorkshopTag string|nil Common Values = nil, "Arches", "Decorations", "Flat", "Signs and Ads". 
function ModularScenery.BrowserCategories__Update__UGCWorkshopTag(CategoryID, UGCWorkshopTag)
    DatabaseUtils.ExecuteQuery("BrowserCategories", "BrowserCategories__Update__UGCWorkshopTag", {CategoryID, UGCWorkshopTag}, 2)
end

--- Note: Autogenerated.
---@param CategoryID integer|nil Common Values = 1, 3, 4, 5, 7. (Lookup Key)
---@param Category string|nil Common Values = nil, "Guests". 
function ModularScenery.BrowserCategories__Update__Category(CategoryID, Category)
    DatabaseUtils.ExecuteQuery("BrowserCategories", "BrowserCategories__Update__Category", {CategoryID, Category}, 2)
end

--- Note: Autogenerated.
---@param FilterName string Common Values = "Belonging", "PlatformAttachment", "RestaurantTables", "SceneryBrush". 
---@param DataPrefabName string Common Values = "SurfaceScaling", "Billboard", "Firework", "SceneryPlatform", "Sign". 
function ModularScenery.BrowserFilters__Insert(FilterName, DataPrefabName)
    DatabaseUtils.ExecuteQuery("BrowserFilters", "BrowserFilters__Insert", {FilterName, DataPrefabName}, 2)
end

--- Note: Autogenerated.
---@param FilterName string Common Values = "Belonging", "PlatformAttachment", "RestaurantTables", "SceneryBrush". (Lookup Key)
---@param DataPrefabName string Common Values = "SurfaceScaling", "Billboard", "Firework", "SceneryPlatform", "Sign". 
function ModularScenery.BrowserFilters__Update__DataPrefabName(FilterName, DataPrefabName)
    DatabaseUtils.ExecuteQuery("BrowserFilters", "BrowserFilters__Update__DataPrefabName", {FilterName, DataPrefabName}, 2)
end

--- Note: Autogenerated.
---@param Name string Common Values = "ChangingVillage", "Restaurant". 
---@param EnumValue integer Common Values = 1, 2. 
function ModularScenery.ComplexTypes__Insert(Name, EnumValue)
    DatabaseUtils.ExecuteQuery("ComplexTypes", "ComplexTypes__Insert", {Name, EnumValue}, 2)
end

--- Note: Autogenerated.
---@param Name string Common Values = "ChangingVillage", "Restaurant". (Lookup Key)
---@param EnumValue integer Common Values = 1, 2. 
function ModularScenery.ComplexTypes__Update__EnumValue(Name, EnumValue)
    DatabaseUtils.ExecuteQuery("ComplexTypes", "ComplexTypes__Update__EnumValue", {Name, EnumValue}, 2)
end

--- Note: Autogenerated.
---@param Name string Common Values = "BaseGame", "Deluxe", "PDLC1", "PermanentLocked", "Preorder". 
---@param EnumValue integer Common Values = 0, 1, 2, 4, 8. 
function ModularScenery.ContentPacks__Insert(Name, EnumValue)
    DatabaseUtils.ExecuteQuery("ContentPacks", "ContentPacks__Insert", {Name, EnumValue}, 2)
end

--- Note: Autogenerated.
---@param Name string Common Values = "BaseGame", "Deluxe", "PDLC1", "PermanentLocked", "Preorder". (Lookup Key)
---@param EnumValue integer Common Values = 0, 1, 2, 4, 8. 
function ModularScenery.ContentPacks__Update__EnumValue(Name, EnumValue)
    DatabaseUtils.ExecuteQuery("ContentPacks", "ContentPacks__Update__EnumValue", {Name, EnumValue}, 2)
end

--- Note: Autogenerated.
---@param SceneryPartName string|nil Common Values = "FDLC1_GlassPanel_Circle", "FDLC1_GlassPanel_Frame_Circle", "FDLC1_GlassPanel_Frame_Hexagon", "FDLC1_GlassPanel_Frame_Octagon", "FDLC1_GlassPanel_Frame_SemiCircle". 
function ModularScenery.DevTransitionList__Insert(SceneryPartName)
    DatabaseUtils.ExecuteQuery("DevTransitionList", "DevTransitionList__Insert", {SceneryPartName}, 1)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "DebugDryer", "Facility_ChangingRoom", "Facility_Generator_SolarPanel", "Facility_Generator_SolarPanel_Large", "Facility_GuestSpawner_Coach". 
function ModularScenery.FacilityProps__Insert(SceneryPartName)
    DatabaseUtils.ExecuteQuery("FacilityProps", "FacilityProps__Insert", {SceneryPartName}, 1)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "DebugDryer", "Facility_ChangingRoom", "Facility_Generator_SolarPanel", "Facility_Generator_SolarPanel_Large", "Facility_GuestSpawner_Coach". (Lookup Key)
---@param ShopInventoryName string|nil Common Values = nil, "ChiefBeef", "CosmicCow", "Facility_HaystackDryer", "Facility_Staff_Building_Small". 
function ModularScenery.FacilityProps__Update__ShopInventoryName(SceneryPartName, ShopInventoryName)
    DatabaseUtils.ExecuteQuery("FacilityProps", "FacilityProps__Update__ShopInventoryName", {SceneryPartName, ShopInventoryName}, 2)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "DLC1_Firework_Chrysanthemum", "DLC1_Firework_ChrysanthemumLarge", "DLC1_Firework_Comet", "DLC1_Firework_CometMultiLaunch", "DLC1_Firework_Crossette". 
---@param Radius integer Common Values = 150, 200. 
---@param Magnitude integer Common Values = 8, 10, 12. 
---@param Duration number Common Values = 7.0, 5.0. 
function ModularScenery.FireworkEffects__Insert(SceneryPartName, Radius, Magnitude, Duration)
    DatabaseUtils.ExecuteQuery("FireworkEffects", "FireworkEffects__Insert", {SceneryPartName, Radius, Magnitude, Duration}, 4)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "DLC1_Firework_Chrysanthemum", "DLC1_Firework_ChrysanthemumLarge", "DLC1_Firework_Comet", "DLC1_Firework_CometMultiLaunch", "DLC1_Firework_Crossette". (Lookup Key)
---@param Radius integer Common Values = 150, 200. 
function ModularScenery.FireworkEffects__Update__Radius(SceneryPartName, Radius)
    DatabaseUtils.ExecuteQuery("FireworkEffects", "FireworkEffects__Update__Radius", {SceneryPartName, Radius}, 2)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "DLC1_Firework_Chrysanthemum", "DLC1_Firework_ChrysanthemumLarge", "DLC1_Firework_Comet", "DLC1_Firework_CometMultiLaunch", "DLC1_Firework_Crossette". (Lookup Key)
---@param Magnitude integer Common Values = 8, 10, 12. 
function ModularScenery.FireworkEffects__Update__Magnitude(SceneryPartName, Magnitude)
    DatabaseUtils.ExecuteQuery("FireworkEffects", "FireworkEffects__Update__Magnitude", {SceneryPartName, Magnitude}, 2)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "DLC1_Firework_Chrysanthemum", "DLC1_Firework_ChrysanthemumLarge", "DLC1_Firework_Comet", "DLC1_Firework_CometMultiLaunch", "DLC1_Firework_Crossette". (Lookup Key)
---@param Duration number Common Values = 7.0, 5.0. 
function ModularScenery.FireworkEffects__Update__Duration(SceneryPartName, Duration)
    DatabaseUtils.ExecuteQuery("FireworkEffects", "FireworkEffects__Update__Duration", {SceneryPartName, Duration}, 2)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "AQ_Roof_Bevelled_Corner", "AQ_Roof_Bevelled_InsideCorner", "AQ_Roof_Bevelled_Straight", "AQ_Roof_Corrugated_2h_4m", "AQ_Roof_Corrugated_2h_4m_Trim". 
---@param CellXSize number Common Values = 4.0, 2.0, 8.0, 6.0, 0.5. 
---@param CellYSize number Common Values = 4.0, 2.0, 1.0, 0.5, 0.2. 
---@param CellZSize number Common Values = 4.0, 2.0, 8.0, 0.5, 1.0. 
---@param BoxXSize number Common Values = 4.0, 2.0, 0.667, 8.0, 0.5. 
---@param BoxYSize number Common Values = 4.0, 2.0, 1.0, 0.5, 0.2. 
---@param BoxZSize number Common Values = 0.375, 4.0, 0.5, 2.0, 0.667. 
function ModularScenery.GridProps__Insert(SceneryPartName, CellXSize, CellYSize, CellZSize, BoxXSize, BoxYSize, BoxZSize)
    DatabaseUtils.ExecuteQuery("GridProps", "GridProps__Insert", {SceneryPartName, CellXSize, CellYSize, CellZSize, BoxXSize, BoxYSize, BoxZSize}, 7)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "AQ_Roof_Bevelled_Corner", "AQ_Roof_Bevelled_InsideCorner", "AQ_Roof_Bevelled_Straight", "AQ_Roof_Corrugated_2h_4m", "AQ_Roof_Corrugated_2h_4m_Trim". (Lookup Key)
---@param CellXSize number Common Values = 4.0, 2.0, 8.0, 6.0, 0.5. 
function ModularScenery.GridProps__Update__CellXSize(SceneryPartName, CellXSize)
    DatabaseUtils.ExecuteQuery("GridProps", "GridProps__Update__CellXSize", {SceneryPartName, CellXSize}, 2)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "AQ_Roof_Bevelled_Corner", "AQ_Roof_Bevelled_InsideCorner", "AQ_Roof_Bevelled_Straight", "AQ_Roof_Corrugated_2h_4m", "AQ_Roof_Corrugated_2h_4m_Trim". (Lookup Key)
---@param CellYSize number Common Values = 4.0, 2.0, 1.0, 0.5, 0.2. 
function ModularScenery.GridProps__Update__CellYSize(SceneryPartName, CellYSize)
    DatabaseUtils.ExecuteQuery("GridProps", "GridProps__Update__CellYSize", {SceneryPartName, CellYSize}, 2)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "AQ_Roof_Bevelled_Corner", "AQ_Roof_Bevelled_InsideCorner", "AQ_Roof_Bevelled_Straight", "AQ_Roof_Corrugated_2h_4m", "AQ_Roof_Corrugated_2h_4m_Trim". (Lookup Key)
---@param CellZSize number Common Values = 4.0, 2.0, 8.0, 0.5, 1.0. 
function ModularScenery.GridProps__Update__CellZSize(SceneryPartName, CellZSize)
    DatabaseUtils.ExecuteQuery("GridProps", "GridProps__Update__CellZSize", {SceneryPartName, CellZSize}, 2)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "AQ_Roof_Bevelled_Corner", "AQ_Roof_Bevelled_InsideCorner", "AQ_Roof_Bevelled_Straight", "AQ_Roof_Corrugated_2h_4m", "AQ_Roof_Corrugated_2h_4m_Trim". (Lookup Key)
---@param BoxXSize number Common Values = 4.0, 2.0, 0.667, 8.0, 0.5. 
function ModularScenery.GridProps__Update__BoxXSize(SceneryPartName, BoxXSize)
    DatabaseUtils.ExecuteQuery("GridProps", "GridProps__Update__BoxXSize", {SceneryPartName, BoxXSize}, 2)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "AQ_Roof_Bevelled_Corner", "AQ_Roof_Bevelled_InsideCorner", "AQ_Roof_Bevelled_Straight", "AQ_Roof_Corrugated_2h_4m", "AQ_Roof_Corrugated_2h_4m_Trim". (Lookup Key)
---@param BoxYSize number Common Values = 4.0, 2.0, 1.0, 0.5, 0.2. 
function ModularScenery.GridProps__Update__BoxYSize(SceneryPartName, BoxYSize)
    DatabaseUtils.ExecuteQuery("GridProps", "GridProps__Update__BoxYSize", {SceneryPartName, BoxYSize}, 2)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "AQ_Roof_Bevelled_Corner", "AQ_Roof_Bevelled_InsideCorner", "AQ_Roof_Bevelled_Straight", "AQ_Roof_Corrugated_2h_4m", "AQ_Roof_Corrugated_2h_4m_Trim". (Lookup Key)
---@param BoxZSize number Common Values = 0.375, 4.0, 0.5, 2.0, 0.667. 
function ModularScenery.GridProps__Update__BoxZSize(SceneryPartName, BoxZSize)
    DatabaseUtils.ExecuteQuery("GridProps", "GridProps__Update__BoxZSize", {SceneryPartName, BoxZSize}, 2)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "AQ_Roof_Bevelled_Corner", "AQ_Roof_Bevelled_InsideCorner", "AQ_Roof_Bevelled_Straight", "AQ_Roof_Corrugated_2h_4m", "AQ_Roof_Corrugated_2h_4m_Trim". (Lookup Key)
---@param AlignmentStyle string Default = Middle. Common Values = "EdgesNESW", "Middle", "EdgesNESW_ZCentred", "Corners". 
function ModularScenery.GridProps__Update__AlignmentStyle(SceneryPartName, AlignmentStyle)
    DatabaseUtils.ExecuteQuery("GridProps", "GridProps__Update__AlignmentStyle", {SceneryPartName, AlignmentStyle}, 2)
end

--- Note: Autogenerated.
---@param Name string Common Values = "Corners", "EdgesNESW", "EdgesNESW_ZCentred", "Middle", "NoAlign". 
---@param EnumValue integer Common Values = 0, 1, 2, 3, 4. 
function ModularScenery.LocalGridAlignmentStyle__Insert(Name, EnumValue)
    DatabaseUtils.ExecuteQuery("LocalGridAlignmentStyle", "LocalGridAlignmentStyle__Insert", {Name, EnumValue}, 2)
end

--- Note: Autogenerated.
---@param Name string Common Values = "Corners", "EdgesNESW", "EdgesNESW_ZCentred", "Middle", "NoAlign". (Lookup Key)
---@param EnumValue integer Common Values = 0, 1, 2, 3, 4. 
function ModularScenery.LocalGridAlignmentStyle__Update__EnumValue(Name, EnumValue)
    DatabaseUtils.ExecuteQuery("LocalGridAlignmentStyle", "LocalGridAlignmentStyle__Update__EnumValue", {Name, EnumValue}, 2)
end

--- Note: Autogenerated.
---@param SceneryPart string Common Values = "RE_Lighting_CeilingLamp_02", "VI_Bellows_01", "AQ_Roof_Corrugated_Slope_Eave_Corner_4m", "PC_Wall_Brick_GableTri_1m", "PC_Wall_Brick_GableTri_2m". 
---@param Tag string Common Values = "Filter_PDLC_None", "Filter_Property_FlexiColour", "Filter_GridProperty_OffGrid", "Filter_Scenery_Inanimate", "Filter_BaseMaterial_Metal". 
function ModularScenery.Metadata_Tags__Insert(SceneryPart, Tag)
    DatabaseUtils.ExecuteQuery("Metadata_Tags", "Metadata_Tags__Insert", {SceneryPart, Tag}, 2)
end

--- Note: Autogenerated.
---@param SceneryPart string Common Values = "RE_Lighting_CeilingLamp_02", "VI_Bellows_01", "AQ_Roof_Corrugated_Slope_Eave_Corner_4m", "PC_Wall_Brick_GableTri_1m", "PC_Wall_Brick_GableTri_2m". (Lookup Key)
---@param Tag string Common Values = "Filter_PDLC_None", "Filter_Property_FlexiColour", "Filter_GridProperty_OffGrid", "Filter_Scenery_Inanimate", "Filter_BaseMaterial_Metal". 
function ModularScenery.Metadata_Tags__Update__Tag(SceneryPart, Tag)
    DatabaseUtils.ExecuteQuery("Metadata_Tags", "Metadata_Tags__Update__Tag", {SceneryPart, Tag}, 2)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "AQ_Anchor", "AQ_Bench_01", "AQ_Bench_02", "AQ_Bin_01", "AQ_Bin_02". 
---@param DataPrefabName string Common Values = "SurfaceScaling", "OnGrid", "TriggerableScenery", "SignScaling", "Firework". 
---@param ContentPack string Common Values = "BaseGame". 
function ModularScenery.ModularSceneryParts__Insert(SceneryPartName, DataPrefabName, ContentPack)
    DatabaseUtils.ExecuteQuery("ModularSceneryParts", "ModularSceneryParts__Insert", {SceneryPartName, DataPrefabName, ContentPack}, 3)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "AQ_Anchor", "AQ_Bench_01", "AQ_Bench_02", "AQ_Bin_01", "AQ_Bin_02". (Lookup Key)
---@param PrefabName string|nil Common Values = nil, "PlaceholderActualParkEntrance", "RR_ParkEntrance", "SF_Outpost_Soldier_Animatronic_Green", "SF_Outpost_Soldier_Animatronic_Green_Computer". 
function ModularScenery.ModularSceneryParts__Update__PrefabName(SceneryPartName, PrefabName)
    DatabaseUtils.ExecuteQuery("ModularSceneryParts", "ModularSceneryParts__Update__PrefabName", {SceneryPartName, PrefabName}, 2)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "AQ_Anchor", "AQ_Bench_01", "AQ_Bench_02", "AQ_Bin_01", "AQ_Bin_02". (Lookup Key)
---@param DataPrefabName string Common Values = "SurfaceScaling", "OnGrid", "TriggerableScenery", "SignScaling", "Firework". 
function ModularScenery.ModularSceneryParts__Update__DataPrefabName(SceneryPartName, DataPrefabName)
    DatabaseUtils.ExecuteQuery("ModularSceneryParts", "ModularSceneryParts__Update__DataPrefabName", {SceneryPartName, DataPrefabName}, 2)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "AQ_Anchor", "AQ_Bench_01", "AQ_Bench_02", "AQ_Bin_01", "AQ_Bin_02". (Lookup Key)
---@param ContentPack string Common Values = "BaseGame". 
function ModularScenery.ModularSceneryParts__Update__ContentPack(SceneryPartName, ContentPack)
    DatabaseUtils.ExecuteQuery("ModularSceneryParts", "ModularSceneryParts__Update__ContentPack", {SceneryPartName, ContentPack}, 2)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "AQ_Anchor", "AQ_Bench_01", "AQ_Bench_02", "AQ_Bin_01", "AQ_Bin_02". (Lookup Key)
---@param UGCID string|nil Default = NULL. Common Values = nil, "". 
function ModularScenery.ModularSceneryParts__Update__UGCID(SceneryPartName, UGCID)
    DatabaseUtils.ExecuteQuery("ModularSceneryParts", "ModularSceneryParts__Update__UGCID", {SceneryPartName, UGCID}, 2)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "AQ_Anchor", "AQ_Bench_01", "AQ_Bench_02", "AQ_Bin_01", "AQ_Bin_02". (Lookup Key)
---@param BoxXSize number|nil Common Values = nil, 4.0, 2.0, 400.0, 4.5. 
function ModularScenery.ModularSceneryParts__Update__BoxXSize(SceneryPartName, BoxXSize)
    DatabaseUtils.ExecuteQuery("ModularSceneryParts", "ModularSceneryParts__Update__BoxXSize", {SceneryPartName, BoxXSize}, 2)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "AQ_Anchor", "AQ_Bench_01", "AQ_Bench_02", "AQ_Bin_01", "AQ_Bin_02". (Lookup Key)
---@param BoxYSize number|nil Common Values = nil, 2.0, 0.22, 0.5, 4.0. 
function ModularScenery.ModularSceneryParts__Update__BoxYSize(SceneryPartName, BoxYSize)
    DatabaseUtils.ExecuteQuery("ModularSceneryParts", "ModularSceneryParts__Update__BoxYSize", {SceneryPartName, BoxYSize}, 2)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "AQ_Anchor", "AQ_Bench_01", "AQ_Bench_02", "AQ_Bin_01", "AQ_Bin_02". (Lookup Key)
---@param BoxZSize number|nil Common Values = nil, 4.0, 0.375, 400.0, 2.0. 
function ModularScenery.ModularSceneryParts__Update__BoxZSize(SceneryPartName, BoxZSize)
    DatabaseUtils.ExecuteQuery("ModularSceneryParts", "ModularSceneryParts__Update__BoxZSize", {SceneryPartName, BoxZSize}, 2)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "Facility_ChangingRoom", "Facility_Restaurant_Kitchen". 
function ModularScenery.PartComplexMembers__Insert(SceneryPartName)
    DatabaseUtils.ExecuteQuery("PartComplexMembers", "PartComplexMembers__Insert", {SceneryPartName}, 1)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "Facility_ChangingRoom", "Facility_Restaurant_Kitchen". (Lookup Key)
---@param MustBelongToComplexOfType string|nil Common Values = "ChangingVillage", "Restaurant". 
function ModularScenery.PartComplexMembers__Update__MustBelongToComplexOfType(SceneryPartName, MustBelongToComplexOfType)
    DatabaseUtils.ExecuteQuery("PartComplexMembers", "PartComplexMembers__Update__MustBelongToComplexOfType", {SceneryPartName, MustBelongToComplexOfType}, 2)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "AQ_Anchor", "AQ_Bench_01", "AQ_Bench_02", "AQ_Bin_01", "AQ_Bin_02". 
function ModularScenery.PartControlPoints__Insert(SceneryPartName)
    DatabaseUtils.ExecuteQuery("PartControlPoints", "PartControlPoints__Insert", {SceneryPartName}, 1)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "AQ_Anchor", "AQ_Bench_01", "AQ_Bench_02", "AQ_Bin_01", "AQ_Bin_02". (Lookup Key)
---@param ControlPointX number Default = 0. Common Values = 0.0, -2.842170943040401e-16, 6.0. 
function ModularScenery.PartControlPoints__Update__ControlPointX(SceneryPartName, ControlPointX)
    DatabaseUtils.ExecuteQuery("PartControlPoints", "PartControlPoints__Update__ControlPointX", {SceneryPartName, ControlPointX}, 2)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "AQ_Anchor", "AQ_Bench_01", "AQ_Bench_02", "AQ_Bin_01", "AQ_Bin_02". (Lookup Key)
---@param ControlPointY number Default = 0. Common Values = 0.0, -0.25, -1.0, -2.0, -0.662266502. 
function ModularScenery.PartControlPoints__Update__ControlPointY(SceneryPartName, ControlPointY)
    DatabaseUtils.ExecuteQuery("PartControlPoints", "PartControlPoints__Update__ControlPointY", {SceneryPartName, ControlPointY}, 2)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "AQ_Anchor", "AQ_Bench_01", "AQ_Bench_02", "AQ_Bin_01", "AQ_Bin_02". (Lookup Key)
---@param ControlPointZ number Default = 0. Common Values = 0.0, -2.0, -1.0, -0.5, -2.8. 
function ModularScenery.PartControlPoints__Update__ControlPointZ(SceneryPartName, ControlPointZ)
    DatabaseUtils.ExecuteQuery("PartControlPoints", "PartControlPoints__Update__ControlPointZ", {SceneryPartName, ControlPointZ}, 2)
end

--- Note: Autogenerated.
---@param PrefabName string Common Values = "Billboard", "BuildingGroup", "ChangingRoom", "Facility", "FacilityComplex". 
function ModularScenery.PartDataPrefabs__Insert(PrefabName)
    DatabaseUtils.ExecuteQuery("PartDataPrefabs", "PartDataPrefabs__Insert", {PrefabName}, 1)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "AQ_Bench_01", "AQ_Bench_02", "AQ_Bin_01", "AQ_Bin_02", "AQ_PicnicBench_01". 
---@param BoxXSize number Common Values = 2.455, 0.77, 2.0, 0.75, 1.0. 
---@param BoxYSize number Common Values = 4.0, 1.866, 0.2, 2.0, 0.399. 
---@param BoxZSize number Common Values = 2.0, 0.6, 1.0, 0.2, 2.3. 
---@param SnapType string Common Values = "Path", "Pool", "Pool_WaveMachine", "Path_LifeguardPost", "Pool_WaterPump". 
function ModularScenery.PathExtraProps__Insert(SceneryPartName, BoxXSize, BoxYSize, BoxZSize, SnapType)
    DatabaseUtils.ExecuteQuery("PathExtraProps", "PathExtraProps__Insert", {SceneryPartName, BoxXSize, BoxYSize, BoxZSize, SnapType}, 5)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "AQ_Bench_01", "AQ_Bench_02", "AQ_Bin_01", "AQ_Bin_02", "AQ_PicnicBench_01". (Lookup Key)
---@param BoxXSize number Common Values = 2.455, 0.77, 2.0, 0.75, 1.0. 
function ModularScenery.PathExtraProps__Update__BoxXSize(SceneryPartName, BoxXSize)
    DatabaseUtils.ExecuteQuery("PathExtraProps", "PathExtraProps__Update__BoxXSize", {SceneryPartName, BoxXSize}, 2)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "AQ_Bench_01", "AQ_Bench_02", "AQ_Bin_01", "AQ_Bin_02", "AQ_PicnicBench_01". (Lookup Key)
---@param BoxYSize number Common Values = 4.0, 1.866, 0.2, 2.0, 0.399. 
function ModularScenery.PathExtraProps__Update__BoxYSize(SceneryPartName, BoxYSize)
    DatabaseUtils.ExecuteQuery("PathExtraProps", "PathExtraProps__Update__BoxYSize", {SceneryPartName, BoxYSize}, 2)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "AQ_Bench_01", "AQ_Bench_02", "AQ_Bin_01", "AQ_Bin_02", "AQ_PicnicBench_01". (Lookup Key)
---@param BoxZSize number Common Values = 2.0, 0.6, 1.0, 0.2, 2.3. 
function ModularScenery.PathExtraProps__Update__BoxZSize(SceneryPartName, BoxZSize)
    DatabaseUtils.ExecuteQuery("PathExtraProps", "PathExtraProps__Update__BoxZSize", {SceneryPartName, BoxZSize}, 2)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "AQ_Bench_01", "AQ_Bench_02", "AQ_Bin_01", "AQ_Bin_02", "AQ_PicnicBench_01". (Lookup Key)
---@param SnapType string Common Values = "Path", "Pool", "Pool_WaveMachine", "Path_LifeguardPost", "Pool_WaterPump". 
function ModularScenery.PathExtraProps__Update__SnapType(SceneryPartName, SnapType)
    DatabaseUtils.ExecuteQuery("PathExtraProps", "PathExtraProps__Update__SnapType", {SceneryPartName, SnapType}, 2)
end

--- Note: Autogenerated.
---@param SnapTypeName string Common Values = "Path", "Path_LifeguardPost", "Pool", "Pool_WaterPump", "Pool_WaveMachine". 
---@param SnapTypeValue integer Common Values = 1, 2, 3, 4, 5. 
function ModularScenery.PathExtraSnapType__Insert(SnapTypeName, SnapTypeValue)
    DatabaseUtils.ExecuteQuery("PathExtraSnapType", "PathExtraSnapType__Insert", {SnapTypeName, SnapTypeValue}, 2)
end

--- Note: Autogenerated.
---@param SnapTypeName string Common Values = "Path", "Path_LifeguardPost", "Pool", "Pool_WaterPump", "Pool_WaveMachine". (Lookup Key)
---@param SnapTypeValue integer Common Values = 1, 2, 3, 4, 5. 
function ModularScenery.PathExtraSnapType__Update__SnapTypeValue(SnapTypeName, SnapTypeValue)
    DatabaseUtils.ExecuteQuery("PathExtraSnapType", "PathExtraSnapType__Update__SnapTypeValue", {SnapTypeName, SnapTypeValue}, 2)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "DebugDryer", "Facility_ChangingRoom", "Facility_Generator_SolarPanel", "Facility_Generator_SolarPanel_Large", "Facility_GuestSpawner_Coach". 
---@param JoinPartResourceName string Common Values = "FacilityJoin", "FacilityJoin_Small_NoControlPanel", "ParkEntranceJoinPart", "FacilityJoin_Large_LeftEntrance", "FacilityJoin_Medium". 
function ModularScenery.PathProps__Insert(SceneryPartName, JoinPartResourceName)
    DatabaseUtils.ExecuteQuery("PathProps", "PathProps__Insert", {SceneryPartName, JoinPartResourceName}, 2)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "DebugDryer", "Facility_ChangingRoom", "Facility_Generator_SolarPanel", "Facility_Generator_SolarPanel_Large", "Facility_GuestSpawner_Coach". (Lookup Key)
---@param JoinPartResourceName string Common Values = "FacilityJoin", "FacilityJoin_Small_NoControlPanel", "ParkEntranceJoinPart", "FacilityJoin_Large_LeftEntrance", "FacilityJoin_Medium". 
function ModularScenery.PathProps__Update__JoinPartResourceName(SceneryPartName, JoinPartResourceName)
    DatabaseUtils.ExecuteQuery("PathProps", "PathProps__Update__JoinPartResourceName", {SceneryPartName, JoinPartResourceName}, 2)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "AQ_Anchor", "AQ_CargoLift_FootBase", "AQ_CargoLift_FootWall", "AQ_Coral_Anemone_01", "AQ_Coral_Anemone_02". 
---@param MinSize number Common Values = 0.5, 0.6, 0.05, 0.25, 0.1. 
---@param MaxSize number Common Values = 3.0, 2.0, 5.0, 1.4, 2.5. 
function ModularScenery.SceneryScaling__Insert(SceneryPartName, MinSize, MaxSize)
    DatabaseUtils.ExecuteQuery("SceneryScaling", "SceneryScaling__Insert", {SceneryPartName, MinSize, MaxSize}, 3)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "AQ_Anchor", "AQ_CargoLift_FootBase", "AQ_CargoLift_FootWall", "AQ_Coral_Anemone_01", "AQ_Coral_Anemone_02". (Lookup Key)
---@param MinSize number Common Values = 0.5, 0.6, 0.05, 0.25, 0.1. 
function ModularScenery.SceneryScaling__Update__MinSize(SceneryPartName, MinSize)
    DatabaseUtils.ExecuteQuery("SceneryScaling", "SceneryScaling__Update__MinSize", {SceneryPartName, MinSize}, 2)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "AQ_Anchor", "AQ_CargoLift_FootBase", "AQ_CargoLift_FootWall", "AQ_Coral_Anemone_01", "AQ_Coral_Anemone_02". (Lookup Key)
---@param MaxSize number Common Values = 3.0, 2.0, 5.0, 1.4, 2.5. 
function ModularScenery.SceneryScaling__Update__MaxSize(SceneryPartName, MaxSize)
    DatabaseUtils.ExecuteQuery("SceneryScaling", "SceneryScaling__Update__MaxSize", {SceneryPartName, MaxSize}, 2)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "AQ_Anchor", "AQ_Bench_01", "AQ_Bench_02", "AQ_Bin_01", "AQ_Bin_02". 
---@param BuildCost integer Common Values = 400, 1800, 200, 1400, 300. 
function ModularScenery.Simulation__Insert(SceneryPartName, BuildCost)
    DatabaseUtils.ExecuteQuery("Simulation", "Simulation__Insert", {SceneryPartName, BuildCost}, 2)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "AQ_Anchor", "AQ_Bench_01", "AQ_Bench_02", "AQ_Bin_01", "AQ_Bin_02". (Lookup Key)
---@param BuildCost integer Common Values = 400, 1800, 200, 1400, 300. 
function ModularScenery.Simulation__Update__BuildCost(SceneryPartName, BuildCost)
    DatabaseUtils.ExecuteQuery("Simulation", "Simulation__Update__BuildCost", {SceneryPartName, BuildCost}, 2)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "AQ_Anchor", "AQ_Bench_01", "AQ_Bench_02", "AQ_Bin_01", "AQ_Bin_02". (Lookup Key)
---@param HourlyRunningCost integer|nil Common Values = 0. 
function ModularScenery.Simulation__Update__HourlyRunningCost(SceneryPartName, HourlyRunningCost)
    DatabaseUtils.ExecuteQuery("Simulation", "Simulation__Update__HourlyRunningCost", {SceneryPartName, HourlyRunningCost}, 2)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "AQ_Anchor", "AQ_Bench_01", "AQ_Bench_02", "AQ_Bin_01", "AQ_Bin_02". (Lookup Key)
---@param ResearchPack integer|nil Common Values = nil, 1000, 1001, 2300, 2301. 
function ModularScenery.Simulation__Update__ResearchPack(SceneryPartName, ResearchPack)
    DatabaseUtils.ExecuteQuery("Simulation", "Simulation__Update__ResearchPack", {SceneryPartName, ResearchPack}, 2)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "AQ_Anchor", "AQ_Bench_01", "AQ_Bench_02", "AQ_Bin_01", "AQ_Bin_02". (Lookup Key)
---@param RequiresUnlockInSandbox boolean|nil Common Values = 0, 1. 
function ModularScenery.Simulation__Update__RequiresUnlockInSandbox(SceneryPartName, RequiresUnlockInSandbox)
    DatabaseUtils.ExecuteQuery("Simulation", "Simulation__Update__RequiresUnlockInSandbox", {SceneryPartName, RequiresUnlockInSandbox}, 2)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "SnapEdge_12m", "SnapEdge_16m", "SnapEdge_1m", "SnapEdge_2m", "SnapEdge_4m". 
---@param Size integer Common Values = 1, 2, 4, 8, 12. 
function ModularScenery.SnapEdgePartData__Insert(SceneryPartName, Size)
    DatabaseUtils.ExecuteQuery("SnapEdgePartData", "SnapEdgePartData__Insert", {SceneryPartName, Size}, 2)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "SnapEdge_12m", "SnapEdge_16m", "SnapEdge_1m", "SnapEdge_2m", "SnapEdge_4m". (Lookup Key)
---@param Size integer Common Values = 1, 2, 4, 8, 12. 
function ModularScenery.SnapEdgePartData__Update__Size(SceneryPartName, Size)
    DatabaseUtils.ExecuteQuery("SnapEdgePartData", "SnapEdgePartData__Update__Size", {SceneryPartName, Size}, 2)
end

--- Note: Autogenerated.
---@param TagGroup string Common Values = "FilterGroup_BuildingPieces_WallSet", "FilterGroup_BrandedPieces_Brand", "FilterGroup_All_BaseMaterial", "FilterGroup_BuildingPieces_Type", "FilterGroup_Nature_Type". 
---@param Tag string Common Values = "Filter_BaseMaterial_Bamboo", "Filter_BaseMaterial_Brick", "Filter_BaseMaterial_Ceramic", "Filter_BaseMaterial_Concrete", "Filter_BaseMaterial_Fabric". 
function ModularScenery.TagGroups__Insert(TagGroup, Tag)
    DatabaseUtils.ExecuteQuery("TagGroups", "TagGroups__Insert", {TagGroup, Tag}, 2)
end

--- Note: Autogenerated.
---@param TagGroup string Common Values = "FilterGroup_BuildingPieces_WallSet", "FilterGroup_BrandedPieces_Brand", "FilterGroup_All_BaseMaterial", "FilterGroup_BuildingPieces_Type", "FilterGroup_Nature_Type". (Lookup Key)
---@param Tag string Common Values = "Filter_BaseMaterial_Bamboo", "Filter_BaseMaterial_Brick", "Filter_BaseMaterial_Ceramic", "Filter_BaseMaterial_Concrete", "Filter_BaseMaterial_Fabric". 
function ModularScenery.TagGroups__Update__Tag(TagGroup, Tag)
    DatabaseUtils.ExecuteQuery("TagGroups", "TagGroups__Update__Tag", {TagGroup, Tag}, 2)
end

--- Note: Autogenerated.
---@param TagGroup string Common Values = "FilterGroup_BuildingPieces_WallSet", "FilterGroup_BrandedPieces_Brand", "FilterGroup_All_BaseMaterial", "FilterGroup_BuildingPieces_Type", "FilterGroup_Nature_Type". (Lookup Key)
---@param Ordering integer Default = 0. Common Values = 0, 1, 5, 2, 3. 
function ModularScenery.TagGroups__Update__Ordering(TagGroup, Ordering)
    DatabaseUtils.ExecuteQuery("TagGroups", "TagGroups__Update__Ordering", {TagGroup, Ordering}, 2)
end

--- Note: Autogenerated.
---@param Name string Common Values = "FilterGroup_All_BaseMaterial", "FilterGroup_All_ContentPack", "FilterGroup_All_GridProperty", "FilterGroup_All_Theme", "FilterGroup_BrandedPieces_Brand". 
---@param TextSymbol string Common Values = "TagGroup_BaseMaterial", "TagGroup_Brand", "TagGroup_Grid", "TagGroup_Nature", "TagGroup_PDLC". 
function ModularScenery.TagGroupsDefinition__Insert(Name, TextSymbol)
    DatabaseUtils.ExecuteQuery("TagGroupsDefinition", "TagGroupsDefinition__Insert", {Name, TextSymbol}, 2)
end

--- Note: Autogenerated.
---@param Name string Common Values = "FilterGroup_All_BaseMaterial", "FilterGroup_All_ContentPack", "FilterGroup_All_GridProperty", "FilterGroup_All_Theme", "FilterGroup_BrandedPieces_Brand". (Lookup Key)
---@param TextSymbol string Common Values = "TagGroup_BaseMaterial", "TagGroup_Brand", "TagGroup_Grid", "TagGroup_Nature", "TagGroup_PDLC". 
function ModularScenery.TagGroupsDefinition__Update__TextSymbol(Name, TextSymbol)
    DatabaseUtils.ExecuteQuery("TagGroupsDefinition", "TagGroupsDefinition__Update__TextSymbol", {Name, TextSymbol}, 2)
end

--- Note: Autogenerated.
---@param Name string Common Values = "FilterGroup_All_BaseMaterial", "FilterGroup_All_ContentPack", "FilterGroup_All_GridProperty", "FilterGroup_All_Theme", "FilterGroup_BrandedPieces_Brand". (Lookup Key)
---@param Ordering integer Default = 0. Common Values = 1, 6, 9, 10, 12. 
function ModularScenery.TagGroupsDefinition__Update__Ordering(Name, Ordering)
    DatabaseUtils.ExecuteQuery("TagGroupsDefinition", "TagGroupsDefinition__Update__Ordering", {Name, Ordering}, 2)
end

--- Note: Autogenerated.
---@param TabGroup string Common Values = "FilterGroup_All_ContentPack", "FilterGroup_BrandedPieces_Brand", "FilterGroup_All_BaseMaterial", "FilterGroup_All_Theme", "FilterGroup_BuildingPieces_Height". 
---@param BrowserTab string Common Values = "scenery", "buildings", "shops". 
function ModularScenery.TagGroupsToBrowserTabs__Insert(TabGroup, BrowserTab)
    DatabaseUtils.ExecuteQuery("TagGroupsToBrowserTabs", "TagGroupsToBrowserTabs__Insert", {TabGroup, BrowserTab}, 2)
end

--- Note: Autogenerated.
---@param TabGroup string Common Values = "FilterGroup_All_ContentPack", "FilterGroup_BrandedPieces_Brand", "FilterGroup_All_BaseMaterial", "FilterGroup_All_Theme", "FilterGroup_BuildingPieces_Height". (Lookup Key)
---@param BrowserTab string Common Values = "scenery", "buildings", "shops". 
function ModularScenery.TagGroupsToBrowserTabs__Update__BrowserTab(TabGroup, BrowserTab)
    DatabaseUtils.ExecuteQuery("TagGroupsToBrowserTabs", "TagGroupsToBrowserTabs__Update__BrowserTab", {TabGroup, BrowserTab}, 2)
end

--- Note: Autogenerated.
---@param TabGroup string Common Values = "FilterGroup_All_ContentPack", "FilterGroup_BrandedPieces_Brand", "FilterGroup_All_BaseMaterial", "FilterGroup_All_Theme", "FilterGroup_BuildingPieces_Height". (Lookup Key)
---@param Ordering integer Default = 0. Common Values = 1, 2, 4, 7, 8. 
function ModularScenery.TagGroupsToBrowserTabs__Update__Ordering(TabGroup, Ordering)
    DatabaseUtils.ExecuteQuery("TagGroupsToBrowserTabs", "TagGroupsToBrowserTabs__Update__Ordering", {TabGroup, Ordering}, 2)
end

--- Note: Autogenerated.
---@param Tag string Common Values = "Code_SceneryType_BodyDryer", "Code_SceneryType_ChangingRoom", "Code_SceneryType_DivingBoard", "Code_SceneryType_GuestServices", "Code_SceneryType_LifeguardPoint". 
---@param TextSymbol string Common Values = "Browser_Cat_Shop_Power_Utility", "Browser_Cat_Shop_Water_Utility", "Tag_Menu_PoolExtra_Accessories", "Browser_Cat_Shop_Info", "Browser_SubCat_Nature_Climber". 
function ModularScenery.TagSet__Insert(Tag, TextSymbol)
    DatabaseUtils.ExecuteQuery("TagSet", "TagSet__Insert", {Tag, TextSymbol}, 2)
end

--- Note: Autogenerated.
---@param Tag string Common Values = "Code_SceneryType_BodyDryer", "Code_SceneryType_ChangingRoom", "Code_SceneryType_DivingBoard", "Code_SceneryType_GuestServices", "Code_SceneryType_LifeguardPoint". (Lookup Key)
---@param TextSymbol string Common Values = "Browser_Cat_Shop_Power_Utility", "Browser_Cat_Shop_Water_Utility", "Tag_Menu_PoolExtra_Accessories", "Browser_Cat_Shop_Info", "Browser_SubCat_Nature_Climber". 
function ModularScenery.TagSet__Update__TextSymbol(Tag, TextSymbol)
    DatabaseUtils.ExecuteQuery("TagSet", "TagSet__Update__TextSymbol", {Tag, TextSymbol}, 2)
end

--- Note: Autogenerated.
---@param Tag string Common Values = "Code_SceneryType_BodyDryer", "Code_SceneryType_ChangingRoom", "Code_SceneryType_DivingBoard", "Code_SceneryType_GuestServices", "Code_SceneryType_LifeguardPoint". (Lookup Key)
---@param IconPath string|nil Common Values = nil. 
function ModularScenery.TagSet__Update__IconPath(Tag, IconPath)
    DatabaseUtils.ExecuteQuery("TagSet", "TagSet__Update__IconPath", {Tag, IconPath}, 2)
end

--- Note: Autogenerated.
---@param ThemeName string Common Values = "Theme_Aquatic", "Theme_Mythology", "Theme_Nature", "Theme_PlanetCoaster", "Theme_Resort". 
---@param Tag string Common Values = "Filter_Theme_Aquatic", "Filter_Theme_Mythology", "Filter_Theme_Nature", "Filter_Theme_PlanetCoaster", "Filter_Theme_Resort". 
---@param LocTag string Common Values = "Tag_Theme_SciFi", "Theme_Aquatic", "Theme_Mythology", "Theme_Nature", "Theme_PlanetCoaster". 
function ModularScenery.ThemeNames__Insert(ThemeName, Tag, LocTag)
    DatabaseUtils.ExecuteQuery("ThemeNames", "ThemeNames__Insert", {ThemeName, Tag, LocTag}, 3)
end

--- Note: Autogenerated.
---@param ThemeName string Common Values = "Theme_Aquatic", "Theme_Mythology", "Theme_Nature", "Theme_PlanetCoaster", "Theme_Resort". (Lookup Key)
---@param Tag string Common Values = "Filter_Theme_Aquatic", "Filter_Theme_Mythology", "Filter_Theme_Nature", "Filter_Theme_PlanetCoaster", "Filter_Theme_Resort". 
function ModularScenery.ThemeNames__Update__Tag(ThemeName, Tag)
    DatabaseUtils.ExecuteQuery("ThemeNames", "ThemeNames__Update__Tag", {ThemeName, Tag}, 2)
end

--- Note: Autogenerated.
---@param ThemeName string Common Values = "Theme_Aquatic", "Theme_Mythology", "Theme_Nature", "Theme_PlanetCoaster", "Theme_Resort". (Lookup Key)
---@param LocTag string Common Values = "Tag_Theme_SciFi", "Theme_Aquatic", "Theme_Mythology", "Theme_Nature", "Theme_PlanetCoaster". 
function ModularScenery.ThemeNames__Update__LocTag(ThemeName, LocTag)
    DatabaseUtils.ExecuteQuery("ThemeNames", "ThemeNames__Update__LocTag", {ThemeName, LocTag}, 2)
end

--- Note: Autogenerated.
---@param ThemeName string Common Values = "Theme_Aquatic", "Theme_Mythology", "Theme_Nature", "Theme_PlanetCoaster", "Theme_Resort". (Lookup Key)
---@param ContentPack string|nil Common Values = "BaseGame". 
function ModularScenery.ThemeNames__Update__ContentPack(ThemeName, ContentPack)
    DatabaseUtils.ExecuteQuery("ThemeNames", "ThemeNames__Update__ContentPack", {ThemeName, ContentPack}, 2)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "AQ_Anchor", "AQ_Bench_01", "AQ_Bench_02", "AQ_Bin_01", "AQ_Bin_02". 
function ModularScenery.Theming__Insert(SceneryPartName)
    DatabaseUtils.ExecuteQuery("Theming", "Theming__Insert", {SceneryPartName}, 1)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "AQ_Anchor", "AQ_Bench_01", "AQ_Bench_02", "AQ_Bin_01", "AQ_Bin_02". (Lookup Key)
---@param Weight integer Default = 0. Common Values = 528, 220, 402, 520, 653. 
function ModularScenery.Theming__Update__Weight(SceneryPartName, Weight)
    DatabaseUtils.ExecuteQuery("Theming", "Theming__Update__Weight", {SceneryPartName, Weight}, 2)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "AQ_Anchor", "AQ_Bench_01", "AQ_Bench_02", "AQ_Bin_01", "AQ_Bin_02". (Lookup Key)
---@param Radius integer Default = 0. Common Values = 2, 1, 4, 3, 5. 
function ModularScenery.Theming__Update__Radius(SceneryPartName, Radius)
    DatabaseUtils.ExecuteQuery("Theming", "Theming__Update__Radius", {SceneryPartName, Radius}, 2)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "AQ_Anchor", "AQ_Bench_01", "AQ_Bench_02", "AQ_Bin_01", "AQ_Bin_02". (Lookup Key)
---@param FalloffRadius integer Default = 0. Common Values = 4, 8, 5, 7, 6. 
function ModularScenery.Theming__Update__FalloffRadius(SceneryPartName, FalloffRadius)
    DatabaseUtils.ExecuteQuery("Theming", "Theming__Update__FalloffRadius", {SceneryPartName, FalloffRadius}, 2)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "AQ_CargoLift", "AQ_Doors_Anim_01", "AQ_Doors_Anim_02", "AQ_FishBeastie", "AQ_SingingEels_Group". 
---@param CostPerTrigger integer Common Values = 200, 0, 500, 600, 400. 
---@param TriggerRunTime number Common Values = 0.0. 
function ModularScenery.TriggerTargetProps__Insert(SceneryPartName, CostPerTrigger, TriggerRunTime)
    DatabaseUtils.ExecuteQuery("TriggerTargetProps", "TriggerTargetProps__Insert", {SceneryPartName, CostPerTrigger, TriggerRunTime}, 3)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "AQ_CargoLift", "AQ_Doors_Anim_01", "AQ_Doors_Anim_02", "AQ_FishBeastie", "AQ_SingingEels_Group". (Lookup Key)
---@param CostPerTrigger integer Common Values = 200, 0, 500, 600, 400. 
function ModularScenery.TriggerTargetProps__Update__CostPerTrigger(SceneryPartName, CostPerTrigger)
    DatabaseUtils.ExecuteQuery("TriggerTargetProps", "TriggerTargetProps__Update__CostPerTrigger", {SceneryPartName, CostPerTrigger}, 2)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "AQ_CargoLift", "AQ_Doors_Anim_01", "AQ_Doors_Anim_02", "AQ_FishBeastie", "AQ_SingingEels_Group". (Lookup Key)
---@param TriggerRunTime number Common Values = 0.0. 
function ModularScenery.TriggerTargetProps__Update__TriggerRunTime(SceneryPartName, TriggerRunTime)
    DatabaseUtils.ExecuteQuery("TriggerTargetProps", "TriggerTargetProps__Update__TriggerRunTime", {SceneryPartName, TriggerRunTime}, 2)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "AQ_Anchor", "AQ_Bench_01", "AQ_Bench_02", "AQ_Bin_01", "AQ_Bin_02". 
---@param LabelTextSymbol string Common Values = "BuildingPartName_AQ_Anchor", "BuildingPartName_AQ_Bench_01", "BuildingPartName_AQ_Bench_02", "BuildingPartName_AQ_Bin_01", "BuildingPartName_AQ_Bin_02". 
---@param DescriptionTextSymbol string Common Values = "BuildingPartDesc_SnapEdge", "BuildingPartDesc_AQ_Anchor", "BuildingPartDesc_AQ_Bench_01", "BuildingPartDesc_AQ_Bench_02", "BuildingPartDesc_AQ_Bin_01". 
function ModularScenery.UIData__Insert(SceneryPartName, LabelTextSymbol, DescriptionTextSymbol)
    DatabaseUtils.ExecuteQuery("UIData", "UIData__Insert", {SceneryPartName, LabelTextSymbol, DescriptionTextSymbol}, 3)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "AQ_Anchor", "AQ_Bench_01", "AQ_Bench_02", "AQ_Bin_01", "AQ_Bin_02". (Lookup Key)
---@param LabelTextSymbol string Common Values = "BuildingPartName_AQ_Anchor", "BuildingPartName_AQ_Bench_01", "BuildingPartName_AQ_Bench_02", "BuildingPartName_AQ_Bin_01", "BuildingPartName_AQ_Bin_02". 
function ModularScenery.UIData__Update__LabelTextSymbol(SceneryPartName, LabelTextSymbol)
    DatabaseUtils.ExecuteQuery("UIData", "UIData__Update__LabelTextSymbol", {SceneryPartName, LabelTextSymbol}, 2)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "AQ_Anchor", "AQ_Bench_01", "AQ_Bench_02", "AQ_Bin_01", "AQ_Bin_02". (Lookup Key)
---@param DescriptionTextSymbol string Common Values = "BuildingPartDesc_SnapEdge", "BuildingPartDesc_AQ_Anchor", "BuildingPartDesc_AQ_Bench_01", "BuildingPartDesc_AQ_Bench_02", "BuildingPartDesc_AQ_Bin_01". 
function ModularScenery.UIData__Update__DescriptionTextSymbol(SceneryPartName, DescriptionTextSymbol)
    DatabaseUtils.ExecuteQuery("UIData", "UIData__Update__DescriptionTextSymbol", {SceneryPartName, DescriptionTextSymbol}, 2)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "AQ_Anchor", "AQ_Bench_01", "AQ_Bench_02", "AQ_Bin_01", "AQ_Bin_02". (Lookup Key)
---@param Icon string|nil Common Values = nil, "PC_Light_02", "PE_MainGate", "ParkEntrance". 
function ModularScenery.UIData__Update__Icon(SceneryPartName, Icon)
    DatabaseUtils.ExecuteQuery("UIData", "UIData__Update__Icon", {SceneryPartName, Icon}, 2)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "AQ_Anchor", "AQ_Bench_01", "AQ_Bench_02", "AQ_Bin_01", "AQ_Bin_02". (Lookup Key)
---@param ReleaseGroup string Default = 7. Common Values = 0, 3, 1, 2, 4. 
function ModularScenery.UIData__Update__ReleaseGroup(SceneryPartName, ReleaseGroup)
    DatabaseUtils.ExecuteQuery("UIData", "UIData__Update__ReleaseGroup", {SceneryPartName, ReleaseGroup}, 2)
end

--- Note: Autogenerated.
---@param DataPrefabName string Common Values = "Facility", "Firework", "Lifeguard", "OnGrid", "ParkEntrance". 
function ModularScenery.UIPartOrdering__Insert(DataPrefabName)
    DatabaseUtils.ExecuteQuery("UIPartOrdering", "UIPartOrdering__Insert", {DataPrefabName}, 1)
end

--- Note: Autogenerated.
---@param DataPrefabName string Common Values = "Facility", "Firework", "Lifeguard", "OnGrid", "ParkEntrance". (Lookup Key)
---@param OrderingValue integer Default = 0. Common Values = 0, 1, 2, 3, 4. 
function ModularScenery.UIPartOrdering__Update__OrderingValue(DataPrefabName, OrderingValue)
    DatabaseUtils.ExecuteQuery("UIPartOrdering", "UIPartOrdering__Update__OrderingValue", {DataPrefabName, OrderingValue}, 2)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "Utility_PowerCable", "Utility_PowerCable_Demolish", "Utility_WaterPipe", "Utility_WaterPipe_Demolish". 
---@param UtilityType string Common Values = "Power", "Water". 
---@param CostPerMeter number Common Values = 0.0, 400.0. 
function ModularScenery.UtilityConnection__Insert(SceneryPartName, UtilityType, CostPerMeter)
    DatabaseUtils.ExecuteQuery("UtilityConnection", "UtilityConnection__Insert", {SceneryPartName, UtilityType, CostPerMeter}, 3)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "Utility_PowerCable", "Utility_PowerCable_Demolish", "Utility_WaterPipe", "Utility_WaterPipe_Demolish". (Lookup Key)
---@param UtilityType string Common Values = "Power", "Water". 
function ModularScenery.UtilityConnection__Update__UtilityType(SceneryPartName, UtilityType)
    DatabaseUtils.ExecuteQuery("UtilityConnection", "UtilityConnection__Update__UtilityType", {SceneryPartName, UtilityType}, 2)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "Utility_PowerCable", "Utility_PowerCable_Demolish", "Utility_WaterPipe", "Utility_WaterPipe_Demolish". (Lookup Key)
---@param CostPerMeter number Common Values = 0.0, 400.0. 
function ModularScenery.UtilityConnection__Update__CostPerMeter(SceneryPartName, CostPerMeter)
    DatabaseUtils.ExecuteQuery("UtilityConnection", "UtilityConnection__Update__CostPerMeter", {SceneryPartName, CostPerMeter}, 2)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "Facility_HaystackDryer_Standard", "Facility_Restaurant_Kitchen", "Facility_Shops_ChiefBeef", "Facility_Shops_ChiefBeef_Counter", "Facility_Shops_CosmicCow". 
---@param UtilityType string Common Values = "Power". 
---@param RequiredUtilityQuantity number Common Values = 5.0, 1.0, 10.0, 15.0, 60.0. 
function ModularScenery.UtilityConsumer__Insert(SceneryPartName, UtilityType, RequiredUtilityQuantity)
    DatabaseUtils.ExecuteQuery("UtilityConsumer", "UtilityConsumer__Insert", {SceneryPartName, UtilityType, RequiredUtilityQuantity}, 3)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "Facility_HaystackDryer_Standard", "Facility_Restaurant_Kitchen", "Facility_Shops_ChiefBeef", "Facility_Shops_ChiefBeef_Counter", "Facility_Shops_CosmicCow". (Lookup Key)
---@param UtilityType string Common Values = "Power". 
function ModularScenery.UtilityConsumer__Update__UtilityType(SceneryPartName, UtilityType)
    DatabaseUtils.ExecuteQuery("UtilityConsumer", "UtilityConsumer__Update__UtilityType", {SceneryPartName, UtilityType}, 2)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "Facility_HaystackDryer_Standard", "Facility_Restaurant_Kitchen", "Facility_Shops_ChiefBeef", "Facility_Shops_ChiefBeef_Counter", "Facility_Shops_CosmicCow". (Lookup Key)
---@param RequiredUtilityQuantity number Common Values = 5.0, 1.0, 10.0, 15.0, 60.0. 
function ModularScenery.UtilityConsumer__Update__RequiredUtilityQuantity(SceneryPartName, RequiredUtilityQuantity)
    DatabaseUtils.ExecuteQuery("UtilityConsumer", "UtilityConsumer__Update__RequiredUtilityQuantity", {SceneryPartName, RequiredUtilityQuantity}, 2)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "Utility_PowerDistributor_Standard", "Utility_WaterDistributor_Small_Standard", "Utility_WaterDistributor_Standard". 
---@param UtilityType string Common Values = "Water", "Power". 
---@param RateOfTransfer number Common Values = 10.0. 
---@param RadiusOfEffect number Common Values = 40.0, 70.0. 
function ModularScenery.UtilityDistribution__Insert(SceneryPartName, UtilityType, RateOfTransfer, RadiusOfEffect)
    DatabaseUtils.ExecuteQuery("UtilityDistribution", "UtilityDistribution__Insert", {SceneryPartName, UtilityType, RateOfTransfer, RadiusOfEffect}, 4)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "Utility_PowerDistributor_Standard", "Utility_WaterDistributor_Small_Standard", "Utility_WaterDistributor_Standard". (Lookup Key)
---@param UtilityType string Common Values = "Water", "Power". 
function ModularScenery.UtilityDistribution__Update__UtilityType(SceneryPartName, UtilityType)
    DatabaseUtils.ExecuteQuery("UtilityDistribution", "UtilityDistribution__Update__UtilityType", {SceneryPartName, UtilityType}, 2)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "Utility_PowerDistributor_Standard", "Utility_WaterDistributor_Small_Standard", "Utility_WaterDistributor_Standard". (Lookup Key)
---@param RateOfTransfer number Common Values = 10.0. 
function ModularScenery.UtilityDistribution__Update__RateOfTransfer(SceneryPartName, RateOfTransfer)
    DatabaseUtils.ExecuteQuery("UtilityDistribution", "UtilityDistribution__Update__RateOfTransfer", {SceneryPartName, RateOfTransfer}, 2)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "Utility_PowerDistributor_Standard", "Utility_WaterDistributor_Small_Standard", "Utility_WaterDistributor_Standard". (Lookup Key)
---@param RadiusOfEffect number Common Values = 40.0, 70.0. 
function ModularScenery.UtilityDistribution__Update__RadiusOfEffect(SceneryPartName, RadiusOfEffect)
    DatabaseUtils.ExecuteQuery("UtilityDistribution", "UtilityDistribution__Update__RadiusOfEffect", {SceneryPartName, RadiusOfEffect}, 2)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "PC_ParkEntrance", "Facility_Generator_SolarPanel", "Facility_Generator_SolarPanel_Large", "Facility_UndergroundWell", "Facility_WaterTower". 
---@param UtilityType string Common Values = "Power", "Water". 
---@param ProductionPerHour number Common Values = 120.0, 80.0, 240.0, 300.0, 800.0. 
---@param PlacedOnGround string Common Values = "true", "false". 
---@param PlacedOnRoof string Common Values = "false". 
---@param PlacedInWater string Common Values = "false". 
---@param IsInDaylight string Common Values = "false", "TRUE". 
---@param IsNotInExtremeWeather string Common Values = "false". 
function ModularScenery.UtilityProduction__Insert(SceneryPartName, UtilityType, ProductionPerHour, PlacedOnGround, PlacedOnRoof, PlacedInWater, IsInDaylight, IsNotInExtremeWeather)
    DatabaseUtils.ExecuteQuery("UtilityProduction", "UtilityProduction__Insert", {SceneryPartName, UtilityType, ProductionPerHour, PlacedOnGround, PlacedOnRoof, PlacedInWater, IsInDaylight, IsNotInExtremeWeather}, 8)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "PC_ParkEntrance", "Facility_Generator_SolarPanel", "Facility_Generator_SolarPanel_Large", "Facility_UndergroundWell", "Facility_WaterTower". (Lookup Key)
---@param UtilityType string Common Values = "Power", "Water". 
function ModularScenery.UtilityProduction__Update__UtilityType(SceneryPartName, UtilityType)
    DatabaseUtils.ExecuteQuery("UtilityProduction", "UtilityProduction__Update__UtilityType", {SceneryPartName, UtilityType}, 2)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "PC_ParkEntrance", "Facility_Generator_SolarPanel", "Facility_Generator_SolarPanel_Large", "Facility_UndergroundWell", "Facility_WaterTower". (Lookup Key)
---@param ProductionPerHour number Common Values = 120.0, 80.0, 240.0, 300.0, 800.0. 
function ModularScenery.UtilityProduction__Update__ProductionPerHour(SceneryPartName, ProductionPerHour)
    DatabaseUtils.ExecuteQuery("UtilityProduction", "UtilityProduction__Update__ProductionPerHour", {SceneryPartName, ProductionPerHour}, 2)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "PC_ParkEntrance", "Facility_Generator_SolarPanel", "Facility_Generator_SolarPanel_Large", "Facility_UndergroundWell", "Facility_WaterTower". (Lookup Key)
---@param CostPerUtilityPerHour number|nil Common Values = 0.0, 160.0, 320.0, 640.0, 1280.0. 
function ModularScenery.UtilityProduction__Update__CostPerUtilityPerHour(SceneryPartName, CostPerUtilityPerHour)
    DatabaseUtils.ExecuteQuery("UtilityProduction", "UtilityProduction__Update__CostPerUtilityPerHour", {SceneryPartName, CostPerUtilityPerHour}, 2)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "PC_ParkEntrance", "Facility_Generator_SolarPanel", "Facility_Generator_SolarPanel_Large", "Facility_UndergroundWell", "Facility_WaterTower". (Lookup Key)
---@param PlacedOnGround string Common Values = "true", "false". 
function ModularScenery.UtilityProduction__Update__PlacedOnGround(SceneryPartName, PlacedOnGround)
    DatabaseUtils.ExecuteQuery("UtilityProduction", "UtilityProduction__Update__PlacedOnGround", {SceneryPartName, PlacedOnGround}, 2)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "PC_ParkEntrance", "Facility_Generator_SolarPanel", "Facility_Generator_SolarPanel_Large", "Facility_UndergroundWell", "Facility_WaterTower". (Lookup Key)
---@param PlacedOnRoof string Common Values = "false". 
function ModularScenery.UtilityProduction__Update__PlacedOnRoof(SceneryPartName, PlacedOnRoof)
    DatabaseUtils.ExecuteQuery("UtilityProduction", "UtilityProduction__Update__PlacedOnRoof", {SceneryPartName, PlacedOnRoof}, 2)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "PC_ParkEntrance", "Facility_Generator_SolarPanel", "Facility_Generator_SolarPanel_Large", "Facility_UndergroundWell", "Facility_WaterTower". (Lookup Key)
---@param PlacedInWater string Common Values = "false". 
function ModularScenery.UtilityProduction__Update__PlacedInWater(SceneryPartName, PlacedInWater)
    DatabaseUtils.ExecuteQuery("UtilityProduction", "UtilityProduction__Update__PlacedInWater", {SceneryPartName, PlacedInWater}, 2)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "PC_ParkEntrance", "Facility_Generator_SolarPanel", "Facility_Generator_SolarPanel_Large", "Facility_UndergroundWell", "Facility_WaterTower". (Lookup Key)
---@param IsInDaylight string Common Values = "false", "TRUE". 
function ModularScenery.UtilityProduction__Update__IsInDaylight(SceneryPartName, IsInDaylight)
    DatabaseUtils.ExecuteQuery("UtilityProduction", "UtilityProduction__Update__IsInDaylight", {SceneryPartName, IsInDaylight}, 2)
end

--- Note: Autogenerated.
---@param SceneryPartName string Common Values = "PC_ParkEntrance", "Facility_Generator_SolarPanel", "Facility_Generator_SolarPanel_Large", "Facility_UndergroundWell", "Facility_WaterTower". (Lookup Key)
---@param IsNotInExtremeWeather string Common Values = "false". 
function ModularScenery.UtilityProduction__Update__IsNotInExtremeWeather(SceneryPartName, IsNotInExtremeWeather)
    DatabaseUtils.ExecuteQuery("UtilityProduction", "UtilityProduction__Update__IsNotInExtremeWeather", {SceneryPartName, IsNotInExtremeWeather}, 2)
end

--- Note: Autogenerated.
---@param UtilityType string Common Values = "None", "Power", "Water". 
---@param EnumValue integer Common Values = 0, 1, 2. 
function ModularScenery.UtilityTypes__Insert(UtilityType, EnumValue)
    DatabaseUtils.ExecuteQuery("UtilityTypes", "UtilityTypes__Insert", {UtilityType, EnumValue}, 2)
end

--- Note: Autogenerated.
---@param UtilityType string Common Values = "None", "Power", "Water". (Lookup Key)
---@param EnumValue integer Common Values = 0, 1, 2. 
function ModularScenery.UtilityTypes__Update__EnumValue(UtilityType, EnumValue)
    DatabaseUtils.ExecuteQuery("UtilityTypes", "UtilityTypes__Update__EnumValue", {UtilityType, EnumValue}, 2)
end

--- Note: Autogenerated.
---@param WaterConsumerType string Common Values = "ClothedRide", "Pool", "SwimsuitRide", "Toilets". 
---@param WaterConsumerEnum integer Common Values = 0, 1, 2, 3. 
---@param CleanlinessScalar number Common Values = 0.125, 0.166, 0.5, 1.0. 
---@param VolumeMultiplier number Common Values = 0.1, 1.5. 
function ModularScenery.WaterCleanliness__Insert(WaterConsumerType, WaterConsumerEnum, CleanlinessScalar, VolumeMultiplier)
    DatabaseUtils.ExecuteQuery("WaterCleanliness", "WaterCleanliness__Insert", {WaterConsumerType, WaterConsumerEnum, CleanlinessScalar, VolumeMultiplier}, 4)
end

--- Note: Autogenerated.
---@param WaterConsumerType string Common Values = "ClothedRide", "Pool", "SwimsuitRide", "Toilets". (Lookup Key)
---@param WaterConsumerEnum integer Common Values = 0, 1, 2, 3. 
function ModularScenery.WaterCleanliness__Update__WaterConsumerEnum(WaterConsumerType, WaterConsumerEnum)
    DatabaseUtils.ExecuteQuery("WaterCleanliness", "WaterCleanliness__Update__WaterConsumerEnum", {WaterConsumerType, WaterConsumerEnum}, 2)
end

--- Note: Autogenerated.
---@param WaterConsumerType string Common Values = "ClothedRide", "Pool", "SwimsuitRide", "Toilets". (Lookup Key)
---@param CleanlinessScalar number Common Values = 0.125, 0.166, 0.5, 1.0. 
function ModularScenery.WaterCleanliness__Update__CleanlinessScalar(WaterConsumerType, CleanlinessScalar)
    DatabaseUtils.ExecuteQuery("WaterCleanliness", "WaterCleanliness__Update__CleanlinessScalar", {WaterConsumerType, CleanlinessScalar}, 2)
end

--- Note: Autogenerated.
---@param WaterConsumerType string Common Values = "ClothedRide", "Pool", "SwimsuitRide", "Toilets". (Lookup Key)
---@param VolumeMultiplier number Common Values = 0.1, 1.5. 
function ModularScenery.WaterCleanliness__Update__VolumeMultiplier(WaterConsumerType, VolumeMultiplier)
    DatabaseUtils.ExecuteQuery("WaterCleanliness", "WaterCleanliness__Update__VolumeMultiplier", {WaterConsumerType, VolumeMultiplier}, 2)
end


return ModularScenery
