---
--- NOTE: THIS FILE IS AUTOGENERATED.
--- PLEASE NOTE THAT THIS IS SUBJECT TO CHANGE
--- BETWEEN EACH VERSION. IF BROKEN BY AN UPDATE,
--- REGENERATE VIA THE EXT FOLDER.
--- 
local global = _G
local ipairs = global.ipairs
local DatabaseUtils = require("forgeutils.internal.database.databaseutils")

local logger = require("forgeutils.logger").Get("TrackedRides")

---@class forgeutils.internal.database.TrackedRides
--- Note: Autogenerated!
--- This is a generated lua binding layer for the TrackedRides database.
local TrackedRides = {}

---@private
--- This method is called after data is merged
TrackedRides.InsertToDBs = function()
    TrackedRides.BindPreparedStatements()
end

TrackedRides.tPreparedStatements = {
    "TrackedRides_BlueprintTags", 
    "TrackedRides_BrowserEntries", 
    "TrackedRides_BrowserMenus", 
    "TrackedRides_BrowserTooltips", 
    "TrackedRides_CinematicCameraWeights", 
    "TrackedRides_Class", 
    "TrackedRides_ContentPacks", 
    "TrackedRides_DefaultFlexiColours", 
    "TrackedRides_ElementConversion", 
    "TrackedRides_ElementData", 
    "TrackedRides_ElementLists", 
    "TrackedRides_ElementParamValueLabels", 
    "TrackedRides_ElementParams", 
    "TrackedRides_ElementTypes", 
    "TrackedRides_ElementUsesRideParams", 
    "TrackedRides_FilterGroupDefinitions", 
    "TrackedRides_FilterGroups", 
    "TrackedRides_FlumePlatforms", 
    "TrackedRides_MetadataTags", 
    "TrackedRides_RideData", 
    "TrackedRides_RideFlumePlatforms", 
    "TrackedRides_RideMetadataTags", 
    "TrackedRides_RideParams", 
    "TrackedRides_RideTrains", 
    "TrackedRides_RideTrains_Extra", 
    "TrackedRides_Simulation", 
    "TrackedRides_TrackParamEnum", 
    "TrackedRides_TransitionList", 
    "TrackedRides_UtilityConsumer", 
    "TrackedRides_UtilityTypes", 
    "TrackedRides_Trains"
}

---@private
function TrackedRides.BindPreparedStatements()
    logger:DebugQuery("BindPreparedStatements()")
    for _, filename in ipairs(TrackedRides.tPreparedStatements) do
        DatabaseUtils.BindPreparedStatement("TrackedRides", filename)
    end
end


--- Note: Autogenerated.
---@param Ride string Common Values = "RiverRapids", "CC_FamilyLaunchCoaster", "CC_HopTheGaps", "CC_MouseHunt", "CC_Speed". 
---@param Tag string Common Values = "Coasters", "Filter_AgeGroup_AllAges", "Filter_AgeGroup_TeenAdult", "TrackedRides", "Menu_Coaster_ChainLift". 
function TrackedRides.BlueprintTags__Insert(Ride, Tag)
    DatabaseUtils.ExecuteQuery("BlueprintTags", "BlueprintTags__Insert", {Ride, Tag}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "RiverRapids", "CC_FamilyLaunchCoaster", "CC_HopTheGaps", "CC_MouseHunt", "CC_Speed". (Lookup Key)
---@param Tag string Common Values = "Coasters", "Filter_AgeGroup_AllAges", "Filter_AgeGroup_TeenAdult", "TrackedRides", "Menu_Coaster_ChainLift". 
function TrackedRides.BlueprintTags__Update__Tag(Ride, Tag)
    DatabaseUtils.ExecuteQuery("BlueprintTags", "BlueprintTags__Update__Tag", {Ride, Tag}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "AmericanArrow", "Barghest", "BodyFlume", "BodySlide", "BodySlideWide". 
---@param Label string Common Values = "Coaster_Model_Wooden", "Coaster_Model_LaunchedLSM", "Coaster_Model_Looping", "Coaster_Model_SitDown4Seat", "Coaster_Model_SitDown6Seat". 
---@param Description string Common Values = "Coaster_Aethon_Desc", "Coaster_AmericanArrow_Desc", "Coaster_Barghest_Desc", "Coaster_Boa_Desc", "Coaster_CC_Anubis_Desc". 
function TrackedRides.BrowserEntries__Insert(Ride, Label, Description)
    DatabaseUtils.ExecuteQuery("BrowserEntries", "BrowserEntries__Insert", {Ride, Label, Description}, 3)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "AmericanArrow", "Barghest", "BodyFlume", "BodySlide", "BodySlideWide". (Lookup Key)
---@param Label string Common Values = "Coaster_Model_Wooden", "Coaster_Model_LaunchedLSM", "Coaster_Model_Looping", "Coaster_Model_SitDown4Seat", "Coaster_Model_SitDown6Seat". 
function TrackedRides.BrowserEntries__Update__Label(Ride, Label)
    DatabaseUtils.ExecuteQuery("BrowserEntries", "BrowserEntries__Update__Label", {Ride, Label}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "AmericanArrow", "Barghest", "BodyFlume", "BodySlide", "BodySlideWide". (Lookup Key)
---@param Icon string|nil Common Values = "CC_Aethon", "CC_AmericanArrow", "CC_Anubis", "CC_Bakasura", "CC_Barghest". 
function TrackedRides.BrowserEntries__Update__Icon(Ride, Icon)
    DatabaseUtils.ExecuteQuery("BrowserEntries", "BrowserEntries__Update__Icon", {Ride, Icon}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "AmericanArrow", "Barghest", "BodyFlume", "BodySlide", "BodySlideWide". (Lookup Key)
---@param Description string Common Values = "Coaster_Aethon_Desc", "Coaster_AmericanArrow_Desc", "Coaster_Barghest_Desc", "Coaster_Boa_Desc", "Coaster_CC_Anubis_Desc". 
function TrackedRides.BrowserEntries__Update__Description(Ride, Description)
    DatabaseUtils.ExecuteQuery("BrowserEntries", "BrowserEntries__Update__Description", {Ride, Description}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "AmericanArrow", "Barghest", "BodyFlume", "BodySlide", "BodySlideWide". (Lookup Key)
---@param ReleaseGroup integer Default = 1. Common Values = 0, 1, 3. 
function TrackedRides.BrowserEntries__Update__ReleaseGroup(Ride, ReleaseGroup)
    DatabaseUtils.ExecuteQuery("BrowserEntries", "BrowserEntries__Update__ReleaseGroup", {Ride, ReleaseGroup}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "AmericanArrow", "Barghest", "BodyFlume", "BodySlide", "BodySlideWide". (Lookup Key)
---@param Manufacturer string|nil Common Values = "Coaster_Manufacturer_ValaisNidwalden", "Coaster_Manufacturer_Outamax", "Coaster_Manufacturer_Vector", "Coaster_Manufacturer_BigMsRides", "Coaster_Manufacturer_DartKinetics". 
function TrackedRides.BrowserEntries__Update__Manufacturer(Ride, Manufacturer)
    DatabaseUtils.ExecuteQuery("BrowserEntries", "BrowserEntries__Update__Manufacturer", {Ride, Manufacturer}, 2)
end

--- Note: Autogenerated.
---@param Name string Common Values = "Coasters", "FlumePlatform", "Menu_Coaster_AlternateLift", "Menu_Coaster_ChainLift", "Menu_Coaster_Launched". 
---@param Ordering integer Common Values = 1, 2, 3, 4, 5. 
function TrackedRides.BrowserMenus__Insert(Name, Ordering)
    DatabaseUtils.ExecuteQuery("BrowserMenus", "BrowserMenus__Insert", {Name, Ordering}, 2)
end

--- Note: Autogenerated.
---@param Name string Common Values = "Coasters", "FlumePlatform", "Menu_Coaster_AlternateLift", "Menu_Coaster_ChainLift", "Menu_Coaster_Launched". (Lookup Key)
---@param Label string|nil Common Values = "ObjectBrowser_Beaches", "ObjectBrowser_Coaster_Launched", "ObjectBrowser_Coaster_SteelInverted", "ObjectBrowser_Coaster_SteelMisc", "ObjectBrowser_Coaster_SteelWing". 
function TrackedRides.BrowserMenus__Update__Label(Name, Label)
    DatabaseUtils.ExecuteQuery("BrowserMenus", "BrowserMenus__Update__Label", {Name, Label}, 2)
end

--- Note: Autogenerated.
---@param Name string Common Values = "Coasters", "FlumePlatform", "Menu_Coaster_AlternateLift", "Menu_Coaster_ChainLift", "Menu_Coaster_Launched". (Lookup Key)
---@param Icon string|nil Common Values = "objectBrowserSpecial", "objectBrowserWater", "objectBrowserPoweredRides", "objectBrowserAlternateLiftCoaster", "objectBrowserChainLiftCoaster". 
function TrackedRides.BrowserMenus__Update__Icon(Name, Icon)
    DatabaseUtils.ExecuteQuery("BrowserMenus", "BrowserMenus__Update__Icon", {Name, Icon}, 2)
end

--- Note: Autogenerated.
---@param Name string Common Values = "Coasters", "FlumePlatform", "Menu_Coaster_AlternateLift", "Menu_Coaster_ChainLift", "Menu_Coaster_Launched". (Lookup Key)
---@param Ordering integer Common Values = 1, 2, 3, 4, 5. 
function TrackedRides.BrowserMenus__Update__Ordering(Name, Ordering)
    DatabaseUtils.ExecuteQuery("BrowserMenus", "BrowserMenus__Update__Ordering", {Name, Ordering}, 2)
end

--- Note: Autogenerated.
---@param Name string Common Values = "Coasters", "FlumePlatform", "Menu_Coaster_AlternateLift", "Menu_Coaster_ChainLift", "Menu_Coaster_Launched". (Lookup Key)
---@param Parent string|nil Common Values = "Coasters", nil, "Pools", "TrackedRides", "FlumePlatform". 
function TrackedRides.BrowserMenus__Update__Parent(Name, Parent)
    DatabaseUtils.ExecuteQuery("BrowserMenus", "BrowserMenus__Update__Parent", {Name, Parent}, 2)
end

--- Note: Autogenerated.
---@param Name string Common Values = "Coasters", "FlumePlatform", "Menu_Coaster_AlternateLift", "Menu_Coaster_ChainLift", "Menu_Coaster_Launched". (Lookup Key)
---@param IsCoaster boolean|nil Common Values = 0, 1. 
function TrackedRides.BrowserMenus__Update__IsCoaster(Name, IsCoaster)
    DatabaseUtils.ExecuteQuery("BrowserMenus", "BrowserMenus__Update__IsCoaster", {Name, IsCoaster}, 2)
end

--- Note: Autogenerated.
---@param Name string Common Values = "Coasters", "FlumePlatform", "Menu_Coaster_AlternateLift", "Menu_Coaster_ChainLift", "Menu_Coaster_Launched". (Lookup Key)
---@param AudioOpenSound string|nil Common Values = "Gui_MenuBarTab_Coasters", "Gui_MenuBarTab_Coasters_AltLift", "Gui_MenuBarTab_Coasters_ChainLift", "Gui_MenuBarTab_Coasters_Launch", "Gui_MenuBarTab_Coasters_Special". 
function TrackedRides.BrowserMenus__Update__AudioOpenSound(Name, AudioOpenSound)
    DatabaseUtils.ExecuteQuery("BrowserMenus", "BrowserMenus__Update__AudioOpenSound", {Name, AudioOpenSound}, 2)
end

--- Note: Autogenerated.
---@param Name string Common Values = "Coasters", "FlumePlatform", "Menu_Coaster_AlternateLift", "Menu_Coaster_ChainLift", "Menu_Coaster_Launched". (Lookup Key)
---@param IsWaterSlide boolean|nil Default = 0. Common Values = 0, 1. 
function TrackedRides.BrowserMenus__Update__IsWaterSlide(Name, IsWaterSlide)
    DatabaseUtils.ExecuteQuery("BrowserMenus", "BrowserMenus__Update__IsWaterSlide", {Name, IsWaterSlide}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "AmericanArrow", "Barghest", "CC_Aethon", "CC_Anubis", "CC_Bakasura". 
---@param Tooltip string Common Values = "TrackFeature_ForEveryone", "TrackFeature_CannotInvert", "TrackFeature_ChainLift", "TrackFeature_CanInvert", "TrackFeature_ForAdultsAndTeensOnly". 
function TrackedRides.BrowserTooltips__Insert(Ride, Tooltip)
    DatabaseUtils.ExecuteQuery("BrowserTooltips", "BrowserTooltips__Insert", {Ride, Tooltip}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "AmericanArrow", "Barghest", "CC_Aethon", "CC_Anubis", "CC_Bakasura". (Lookup Key)
---@param Tooltip string Common Values = "TrackFeature_ForEveryone", "TrackFeature_CannotInvert", "TrackFeature_ChainLift", "TrackFeature_CanInvert", "TrackFeature_ForAdultsAndTeensOnly". 
function TrackedRides.BrowserTooltips__Update__Tooltip(Ride, Tooltip)
    DatabaseUtils.ExecuteQuery("BrowserTooltips", "BrowserTooltips__Update__Tooltip", {Ride, Tooltip}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "PTR_Speed". 
function TrackedRides.CinematicCameraWeights__Insert(Ride)
    DatabaseUtils.ExecuteQuery("CinematicCameraWeights", "CinematicCameraWeights__Insert", {Ride}, 1)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "PTR_Speed". (Lookup Key)
---@param Car integer Default = 0. Common Values = 0. 
function TrackedRides.CinematicCameraWeights__Update__Car(Ride, Car)
    DatabaseUtils.ExecuteQuery("CinematicCameraWeights", "CinematicCameraWeights__Update__Car", {Ride, Car}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "PTR_Speed". (Lookup Key)
---@param CarFacing integer Default = 0. Common Values = 10. 
function TrackedRides.CinematicCameraWeights__Update__CarFacing(Ride, CarFacing)
    DatabaseUtils.ExecuteQuery("CinematicCameraWeights", "CinematicCameraWeights__Update__CarFacing", {Ride, CarFacing}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "PTR_Speed". (Lookup Key)
---@param FixFollow integer Default = 30. Common Values = 0. 
function TrackedRides.CinematicCameraWeights__Update__FixFollow(Ride, FixFollow)
    DatabaseUtils.ExecuteQuery("CinematicCameraWeights", "CinematicCameraWeights__Update__FixFollow", {Ride, FixFollow}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "PTR_Speed". (Lookup Key)
---@param FrontBumper integer Default = 0. Common Values = 10. 
function TrackedRides.CinematicCameraWeights__Update__FrontBumper(Ride, FrontBumper)
    DatabaseUtils.ExecuteQuery("CinematicCameraWeights", "CinematicCameraWeights__Update__FrontBumper", {Ride, FrontBumper}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "PTR_Speed". (Lookup Key)
---@param GroundFollow integer Default = 30. Common Values = 0. 
function TrackedRides.CinematicCameraWeights__Update__GroundFollow(Ride, GroundFollow)
    DatabaseUtils.ExecuteQuery("CinematicCameraWeights", "CinematicCameraWeights__Update__GroundFollow", {Ride, GroundFollow}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "PTR_Speed". (Lookup Key)
---@param Orbit integer Default = 0. Common Values = 0. 
function TrackedRides.CinematicCameraWeights__Update__Orbit(Ride, Orbit)
    DatabaseUtils.ExecuteQuery("CinematicCameraWeights", "CinematicCameraWeights__Update__Orbit", {Ride, Orbit}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "PTR_Speed". (Lookup Key)
---@param Seat integer Default = 0. Common Values = 0. 
function TrackedRides.CinematicCameraWeights__Update__Seat(Ride, Seat)
    DatabaseUtils.ExecuteQuery("CinematicCameraWeights", "CinematicCameraWeights__Update__Seat", {Ride, Seat}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "PTR_Speed". (Lookup Key)
---@param SeatFacing integer Default = 0. Common Values = 10. 
function TrackedRides.CinematicCameraWeights__Update__SeatFacing(Ride, SeatFacing)
    DatabaseUtils.ExecuteQuery("CinematicCameraWeights", "CinematicCameraWeights__Update__SeatFacing", {Ride, SeatFacing}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "PTR_Speed". (Lookup Key)
---@param SlideFollow integer Default = 30. Common Values = 0. 
function TrackedRides.CinematicCameraWeights__Update__SlideFollow(Ride, SlideFollow)
    DatabaseUtils.ExecuteQuery("CinematicCameraWeights", "CinematicCameraWeights__Update__SlideFollow", {Ride, SlideFollow}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "PTR_Speed". (Lookup Key)
---@param Wing integer Default = 0. Common Values = 10. 
function TrackedRides.CinematicCameraWeights__Update__Wing(Ride, Wing)
    DatabaseUtils.ExecuteQuery("CinematicCameraWeights", "CinematicCameraWeights__Update__Wing", {Ride, Wing}, 2)
end

--- Note: Autogenerated.
---@param Type string Common Values = "Family", "Junior", "Thrill". 
function TrackedRides.Class__Insert(Type)
    DatabaseUtils.ExecuteQuery("Class", "Class__Insert", {Type}, 1)
end

--- Note: Autogenerated.
---@param Name string Common Values = "BaseGame", "Deluxe", "PDLC1", "PermanentLocked", "Preorder". 
---@param EnumValue string Common Values = 0, 1, 2, 4, 8. 
function TrackedRides.ContentPacks__Insert(Name, EnumValue)
    DatabaseUtils.ExecuteQuery("ContentPacks", "ContentPacks__Insert", {Name, EnumValue}, 2)
end

--- Note: Autogenerated.
---@param Name string Common Values = "BaseGame", "Deluxe", "PDLC1", "PermanentLocked", "Preorder". (Lookup Key)
---@param EnumValue string Common Values = 0, 1, 2, 4, 8. 
function TrackedRides.ContentPacks__Update__EnumValue(Name, EnumValue)
    DatabaseUtils.ExecuteQuery("ContentPacks", "ContentPacks__Update__EnumValue", {Name, EnumValue}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "BodyFlume", "BodySlide", "BodySlideWide", "InnerTubeFlume", "InnerTubeFlumeDouble". 
---@param MaterialCustomisationProviderSlot integer Common Values = 0, 3, 1, 2, 4. 
---@param Red integer Common Values = 72, 38, 26, 60, 255. 
---@param Green integer Common Values = 37, 26, 25, 68, 69. 
---@param Blue integer Common Values = 37, 1, 40, 26, 74. 
function TrackedRides.DefaultFlexiColours__Insert(Ride, MaterialCustomisationProviderSlot, Red, Green, Blue)
    DatabaseUtils.ExecuteQuery("DefaultFlexiColours", "DefaultFlexiColours__Insert", {Ride, MaterialCustomisationProviderSlot, Red, Green, Blue}, 5)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "BodyFlume", "BodySlide", "BodySlideWide", "InnerTubeFlume", "InnerTubeFlumeDouble". (Lookup Key)
---@param SemanticTag string Default = "". Common Values = "Track1", "Track2", "Track3", "Track4", "Flume001". 
function TrackedRides.DefaultFlexiColours__Update__SemanticTag(Ride, SemanticTag)
    DatabaseUtils.ExecuteQuery("DefaultFlexiColours", "DefaultFlexiColours__Update__SemanticTag", {Ride, SemanticTag}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "BodyFlume", "BodySlide", "BodySlideWide", "InnerTubeFlume", "InnerTubeFlumeDouble". (Lookup Key)
---@param MaterialCustomisationProviderSlot integer Common Values = 0, 3, 1, 2, 4. 
function TrackedRides.DefaultFlexiColours__Update__MaterialCustomisationProviderSlot(Ride, MaterialCustomisationProviderSlot)
    DatabaseUtils.ExecuteQuery("DefaultFlexiColours", "DefaultFlexiColours__Update__MaterialCustomisationProviderSlot", {Ride, MaterialCustomisationProviderSlot}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "BodyFlume", "BodySlide", "BodySlideWide", "InnerTubeFlume", "InnerTubeFlumeDouble". (Lookup Key)
---@param Red integer Common Values = 72, 38, 26, 60, 255. 
function TrackedRides.DefaultFlexiColours__Update__Red(Ride, Red)
    DatabaseUtils.ExecuteQuery("DefaultFlexiColours", "DefaultFlexiColours__Update__Red", {Ride, Red}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "BodyFlume", "BodySlide", "BodySlideWide", "InnerTubeFlume", "InnerTubeFlumeDouble". (Lookup Key)
---@param Green integer Common Values = 37, 26, 25, 68, 69. 
function TrackedRides.DefaultFlexiColours__Update__Green(Ride, Green)
    DatabaseUtils.ExecuteQuery("DefaultFlexiColours", "DefaultFlexiColours__Update__Green", {Ride, Green}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "BodyFlume", "BodySlide", "BodySlideWide", "InnerTubeFlume", "InnerTubeFlumeDouble". (Lookup Key)
---@param Blue integer Common Values = 37, 1, 40, 26, 74. 
function TrackedRides.DefaultFlexiColours__Update__Blue(Ride, Blue)
    DatabaseUtils.ExecuteQuery("DefaultFlexiColours", "DefaultFlexiColours__Update__Blue", {Ride, Blue}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "BodyFlume", "InnerTubeFlume", "InnerTubeFlumeDouble", "MatFlume", "RaftFlume". 
---@param Element string Common Values = "station_water_slide", "station_water_slide_transparent", "station_runout_lane_deep", "station_runout_lane_shallow". 
---@param ConvertToElement string Common Values = "station_water_slide_alt", "station_water_slide_alt_transparent", "station_runout_lane_deep_body_flume", "station_runout_lane_deep_mat_flume", "station_runout_lane_shallow_body_flume". 
function TrackedRides.ElementConversion__Insert(Ride, Element, ConvertToElement)
    DatabaseUtils.ExecuteQuery("ElementConversion", "ElementConversion__Insert", {Ride, Element, ConvertToElement}, 3)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "BodyFlume", "InnerTubeFlume", "InnerTubeFlumeDouble", "MatFlume", "RaftFlume". (Lookup Key)
---@param Element string Common Values = "station_water_slide", "station_water_slide_transparent", "station_runout_lane_deep", "station_runout_lane_shallow". 
function TrackedRides.ElementConversion__Update__Element(Ride, Element)
    DatabaseUtils.ExecuteQuery("ElementConversion", "ElementConversion__Update__Element", {Ride, Element}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "BodyFlume", "InnerTubeFlume", "InnerTubeFlumeDouble", "MatFlume", "RaftFlume". (Lookup Key)
---@param ConvertToElement string Common Values = "station_water_slide_alt", "station_water_slide_alt_transparent", "station_runout_lane_deep_body_flume", "station_runout_lane_deep_mat_flume", "station_runout_lane_shallow_body_flume". 
function TrackedRides.ElementConversion__Update__ConvertToElement(Ride, ConvertToElement)
    DatabaseUtils.ExecuteQuery("ElementConversion", "ElementConversion__Update__ConvertToElement", {Ride, ConvertToElement}, 2)
end

--- Note: Autogenerated.
---@param Name string Common Values = "Alternate_Spline_BigTimber", "Barghest_ChainLiftBot", "Barghest_ChainLiftMid", "Barghest_ChainLiftTop_01", "Barghest_ChainLiftTop_02". 
---@param Type string Common Values = "Utilities", "Station", "Rolls", "Loops", "End". 
---@param Cost integer Common Values = 1200, 10800, 5400, 72000, 4320. 
---@param DisabledText string Common Values = "TrackElementDisabled_CannotPlace", "TrackElementDisabled_CanOnlyPlaceNextToStationOfSameType", "TrackElementDisabled_CannotPlaceOnCurvedOrBanked", "TrackElementDisabled_CannotPlaceOnCurvedOrBankedOrOverlySloped", "TrackElementDisabled_CannotPlaceOnBankedOrSloped". 
---@param Ordering number Common Values = 1000.0, 1001.0, 1002.0, 1003.0, 1004.0. 
function TrackedRides.ElementData__Insert(Name, Type, Cost, DisabledText, Ordering)
    DatabaseUtils.ExecuteQuery("ElementData", "ElementData__Insert", {Name, Type, Cost, DisabledText, Ordering}, 5)
end

--- Note: Autogenerated.
---@param Name string Common Values = "Alternate_Spline_BigTimber", "Barghest_ChainLiftBot", "Barghest_ChainLiftMid", "Barghest_ChainLiftTop_01", "Barghest_ChainLiftTop_02". (Lookup Key)
---@param Type string Common Values = "Utilities", "Station", "Rolls", "Loops", "End". 
function TrackedRides.ElementData__Update__Type(Name, Type)
    DatabaseUtils.ExecuteQuery("ElementData", "ElementData__Update__Type", {Name, Type}, 2)
end

--- Note: Autogenerated.
---@param Name string Common Values = "Alternate_Spline_BigTimber", "Barghest_ChainLiftBot", "Barghest_ChainLiftMid", "Barghest_ChainLiftTop_01", "Barghest_ChainLiftTop_02". (Lookup Key)
---@param Label string|nil Common Values = "TrimBrakes", "StationLeftLeft", "StationLeftRight", "StationRightLeft", "StationRightRight". 
function TrackedRides.ElementData__Update__Label(Name, Label)
    DatabaseUtils.ExecuteQuery("ElementData", "ElementData__Update__Label", {Name, Label}, 2)
end

--- Note: Autogenerated.
---@param Name string Common Values = "Alternate_Spline_BigTimber", "Barghest_ChainLiftBot", "Barghest_ChainLiftMid", "Barghest_ChainLiftTop_01", "Barghest_ChainLiftTop_02". (Lookup Key)
---@param Icon string|nil Common Values = "CoasterEditorIconTrimBrakes", "CoasterEditorIconStationLeftLeft", "CoasterEditorIconStationLeftRight", "CoasterEditorIconStationRightLeft", "CoasterEditorIconStationRightRight". 
function TrackedRides.ElementData__Update__Icon(Name, Icon)
    DatabaseUtils.ExecuteQuery("ElementData", "ElementData__Update__Icon", {Name, Icon}, 2)
end

--- Note: Autogenerated.
---@param Name string Common Values = "Alternate_Spline_BigTimber", "Barghest_ChainLiftBot", "Barghest_ChainLiftMid", "Barghest_ChainLiftTop_01", "Barghest_ChainLiftTop_02". (Lookup Key)
---@param Cost integer Common Values = 1200, 10800, 5400, 72000, 4320. 
function TrackedRides.ElementData__Update__Cost(Name, Cost)
    DatabaseUtils.ExecuteQuery("ElementData", "ElementData__Update__Cost", {Name, Cost}, 2)
end

--- Note: Autogenerated.
---@param Name string Common Values = "Alternate_Spline_BigTimber", "Barghest_ChainLiftBot", "Barghest_ChainLiftMid", "Barghest_ChainLiftTop_01", "Barghest_ChainLiftTop_02". (Lookup Key)
---@param RequiredPower number Default = 0.0. Common Values = 0.0, 0.45, 1.0, 0.5, 0.4. 
function TrackedRides.ElementData__Update__RequiredPower(Name, RequiredPower)
    DatabaseUtils.ExecuteQuery("ElementData", "ElementData__Update__RequiredPower", {Name, RequiredPower}, 2)
end

--- Note: Autogenerated.
---@param Name string Common Values = "Alternate_Spline_BigTimber", "Barghest_ChainLiftBot", "Barghest_ChainLiftMid", "Barghest_ChainLiftTop_01", "Barghest_ChainLiftTop_02". (Lookup Key)
---@param LeadsInto string|nil Common Values = nil, "flume_spline", "log_default", "TK_302_ShortTrack", "bucket_default". 
function TrackedRides.ElementData__Update__LeadsInto(Name, LeadsInto)
    DatabaseUtils.ExecuteQuery("ElementData", "ElementData__Update__LeadsInto", {Name, LeadsInto}, 2)
end

--- Note: Autogenerated.
---@param Name string Common Values = "Alternate_Spline_BigTimber", "Barghest_ChainLiftBot", "Barghest_ChainLiftMid", "Barghest_ChainLiftTop_01", "Barghest_ChainLiftTop_02". (Lookup Key)
---@param Wear integer Default = 0. Common Values = 0, 360, 90, 120, 40. 
function TrackedRides.ElementData__Update__Wear(Name, Wear)
    DatabaseUtils.ExecuteQuery("ElementData", "ElementData__Update__Wear", {Name, Wear}, 2)
end

--- Note: Autogenerated.
---@param Name string Common Values = "Alternate_Spline_BigTimber", "Barghest_ChainLiftBot", "Barghest_ChainLiftMid", "Barghest_ChainLiftTop_01", "Barghest_ChainLiftTop_02". (Lookup Key)
---@param DisabledText string Common Values = "TrackElementDisabled_CannotPlace", "TrackElementDisabled_CanOnlyPlaceNextToStationOfSameType", "TrackElementDisabled_CannotPlaceOnCurvedOrBanked", "TrackElementDisabled_CannotPlaceOnCurvedOrBankedOrOverlySloped", "TrackElementDisabled_CannotPlaceOnBankedOrSloped". 
function TrackedRides.ElementData__Update__DisabledText(Name, DisabledText)
    DatabaseUtils.ExecuteQuery("ElementData", "ElementData__Update__DisabledText", {Name, DisabledText}, 2)
end

--- Note: Autogenerated.
---@param Name string Common Values = "Alternate_Spline_BigTimber", "Barghest_ChainLiftBot", "Barghest_ChainLiftMid", "Barghest_ChainLiftTop_01", "Barghest_ChainLiftTop_02". (Lookup Key)
---@param Ordering number Common Values = 1000.0, 1001.0, 1002.0, 1003.0, 1004.0. 
function TrackedRides.ElementData__Update__Ordering(Name, Ordering)
    DatabaseUtils.ExecuteQuery("ElementData", "ElementData__Update__Ordering", {Name, Ordering}, 2)
end

--- Note: Autogenerated.
---@param Name string Common Values = "Alternate_Spline_BigTimber", "Barghest_ChainLiftBot", "Barghest_ChainLiftMid", "Barghest_ChainLiftTop_01", "Barghest_ChainLiftTop_02". (Lookup Key)
---@param LeadsOutOf string|nil Common Values = nil, "log_default", "TK_302_ShortTrack", "TK_004_Drop_Mid", "bucket_default". 
function TrackedRides.ElementData__Update__LeadsOutOf(Name, LeadsOutOf)
    DatabaseUtils.ExecuteQuery("ElementData", "ElementData__Update__LeadsOutOf", {Name, LeadsOutOf}, 2)
end

--- Note: Autogenerated.
---@param Name string Common Values = "Alternate_Spline_BigTimber", "Barghest_ChainLiftBot", "Barghest_ChainLiftMid", "Barghest_ChainLiftTop_01", "Barghest_ChainLiftTop_02". (Lookup Key)
---@param CanGoUnderwater boolean|nil Default = 0. Common Values = 0, nil. 
function TrackedRides.ElementData__Update__CanGoUnderwater(Name, CanGoUnderwater)
    DatabaseUtils.ExecuteQuery("ElementData", "ElementData__Update__CanGoUnderwater", {Name, CanGoUnderwater}, 2)
end

--- Note: Autogenerated.
---@param Name string Common Values = "Alternate_Spline_BigTimber", "Barghest_ChainLiftBot", "Barghest_ChainLiftMid", "Barghest_ChainLiftTop_01", "Barghest_ChainLiftTop_02". (Lookup Key)
---@param DescriptionText string|nil Common Values = nil. 
function TrackedRides.ElementData__Update__DescriptionText(Name, DescriptionText)
    DatabaseUtils.ExecuteQuery("ElementData", "ElementData__Update__DescriptionText", {Name, DescriptionText}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "CC_Infinite", "Barghest", "CC_Bolt", "CC_PowerUp", "Torque". 
---@param Element string Common Values = "station_leftleft", "station_leftright", "station_rightleft", "station_rightright", "station_leftoff". 
function TrackedRides.ElementLists__Insert(Ride, Element)
    DatabaseUtils.ExecuteQuery("ElementLists", "ElementLists__Insert", {Ride, Element}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "CC_Infinite", "Barghest", "CC_Bolt", "CC_PowerUp", "Torque". (Lookup Key)
---@param Element string Common Values = "station_leftleft", "station_leftright", "station_rightleft", "station_rightright", "station_leftoff". 
function TrackedRides.ElementLists__Update__Element(Ride, Element)
    DatabaseUtils.ExecuteQuery("ElementLists", "ElementLists__Update__Element", {Ride, Element}, 2)
end

--- Note: Autogenerated.
---@param LabelSetName string Common Values = "TK_004_Turntable90L_Rev_StartToEnd", "TK_004_Turntable90L_StartToEnd", "TK_004_Turntable90R_Rev_StartToEnd", "TK_004_Turntable90R_StartToEnd", "TK_501_DropTrack_R_StartToEnd". 
---@param ParamValue integer Common Values = 3, 4, 5, 6, 1. 
---@param LocString string Common Values = "TrackParamValueLabel_TurntableAnimation_270Degrees", "TrackParamValueLabel_TurntableAnimation_90Degrees", "TrackParamValueLabel_DropTrackAnimation_FakeOutThenDrop", "TrackParamValueLabel_DropTrackAnimation_SimpleDrop". 
function TrackedRides.ElementParamValueLabels__Insert(LabelSetName, ParamValue, LocString)
    DatabaseUtils.ExecuteQuery("ElementParamValueLabels", "ElementParamValueLabels__Insert", {LabelSetName, ParamValue, LocString}, 3)
end

--- Note: Autogenerated.
---@param LabelSetName string Common Values = "TK_004_Turntable90L_Rev_StartToEnd", "TK_004_Turntable90L_StartToEnd", "TK_004_Turntable90R_Rev_StartToEnd", "TK_004_Turntable90R_StartToEnd", "TK_501_DropTrack_R_StartToEnd". (Lookup Key)
---@param ParamValue integer Common Values = 3, 4, 5, 6, 1. 
function TrackedRides.ElementParamValueLabels__Update__ParamValue(LabelSetName, ParamValue)
    DatabaseUtils.ExecuteQuery("ElementParamValueLabels", "ElementParamValueLabels__Update__ParamValue", {LabelSetName, ParamValue}, 2)
end

--- Note: Autogenerated.
---@param LabelSetName string Common Values = "TK_004_Turntable90L_Rev_StartToEnd", "TK_004_Turntable90L_StartToEnd", "TK_004_Turntable90R_Rev_StartToEnd", "TK_004_Turntable90R_StartToEnd", "TK_501_DropTrack_R_StartToEnd". (Lookup Key)
---@param LocString string Common Values = "TrackParamValueLabel_TurntableAnimation_270Degrees", "TrackParamValueLabel_TurntableAnimation_90Degrees", "TrackParamValueLabel_DropTrackAnimation_FakeOutThenDrop", "TrackParamValueLabel_DropTrackAnimation_SimpleDrop". 
function TrackedRides.ElementParamValueLabels__Update__LocString(LabelSetName, LocString)
    DatabaseUtils.ExecuteQuery("ElementParamValueLabels", "ElementParamValueLabels__Update__LocString", {LabelSetName, LocString}, 2)
end

--- Note: Autogenerated.
---@param Element string Common Values = "TK_040_ShuttleLaunch_station_leftoff", "TK_040_ShuttleLaunch_station_lefton", "TK_040_ShuttleLaunch_station_rightoff", "TK_040_ShuttleLaunch_station_righton", "TK_040_ShuttleLaunch_station_leftleft". 
---@param Param string Common Values = "CurveRangeDegrees", "LengthRangeMetres", "ScaleRange", "StationEntranceSide", "SlopeRangeDegrees". 
---@param Min number Common Values = 1.0, 0.0, -90.0, 4.0, -1.0. 
---@param Max number Common Values = 1.0, 0.0, 90.0, 10.0, 20.0. 
---@param Initial number Common Values = 0.0, 1.0, 4.0, -1.0, 0.5. 
---@param Step number Common Values = 0.0, 1.0, 0.1, 0.5, 2.0. 
function TrackedRides.ElementParams__Insert(Element, Param, Min, Max, Initial, Step)
    DatabaseUtils.ExecuteQuery("ElementParams", "ElementParams__Insert", {Element, Param, Min, Max, Initial, Step}, 6)
end

--- Note: Autogenerated.
---@param Element string Common Values = "TK_040_ShuttleLaunch_station_leftoff", "TK_040_ShuttleLaunch_station_lefton", "TK_040_ShuttleLaunch_station_rightoff", "TK_040_ShuttleLaunch_station_righton", "TK_040_ShuttleLaunch_station_leftleft". (Lookup Key)
---@param Param string Common Values = "CurveRangeDegrees", "LengthRangeMetres", "ScaleRange", "StationEntranceSide", "SlopeRangeDegrees". 
function TrackedRides.ElementParams__Update__Param(Element, Param)
    DatabaseUtils.ExecuteQuery("ElementParams", "ElementParams__Update__Param", {Element, Param}, 2)
end

--- Note: Autogenerated.
---@param Element string Common Values = "TK_040_ShuttleLaunch_station_leftoff", "TK_040_ShuttleLaunch_station_lefton", "TK_040_ShuttleLaunch_station_rightoff", "TK_040_ShuttleLaunch_station_righton", "TK_040_ShuttleLaunch_station_leftleft". (Lookup Key)
---@param Min number Common Values = 1.0, 0.0, -90.0, 4.0, -1.0. 
function TrackedRides.ElementParams__Update__Min(Element, Min)
    DatabaseUtils.ExecuteQuery("ElementParams", "ElementParams__Update__Min", {Element, Min}, 2)
end

--- Note: Autogenerated.
---@param Element string Common Values = "TK_040_ShuttleLaunch_station_leftoff", "TK_040_ShuttleLaunch_station_lefton", "TK_040_ShuttleLaunch_station_rightoff", "TK_040_ShuttleLaunch_station_righton", "TK_040_ShuttleLaunch_station_leftleft". (Lookup Key)
---@param Max number Common Values = 1.0, 0.0, 90.0, 10.0, 20.0. 
function TrackedRides.ElementParams__Update__Max(Element, Max)
    DatabaseUtils.ExecuteQuery("ElementParams", "ElementParams__Update__Max", {Element, Max}, 2)
end

--- Note: Autogenerated.
---@param Element string Common Values = "TK_040_ShuttleLaunch_station_leftoff", "TK_040_ShuttleLaunch_station_lefton", "TK_040_ShuttleLaunch_station_rightoff", "TK_040_ShuttleLaunch_station_righton", "TK_040_ShuttleLaunch_station_leftleft". (Lookup Key)
---@param Initial number Common Values = 0.0, 1.0, 4.0, -1.0, 0.5. 
function TrackedRides.ElementParams__Update__Initial(Element, Initial)
    DatabaseUtils.ExecuteQuery("ElementParams", "ElementParams__Update__Initial", {Element, Initial}, 2)
end

--- Note: Autogenerated.
---@param Element string Common Values = "TK_040_ShuttleLaunch_station_leftoff", "TK_040_ShuttleLaunch_station_lefton", "TK_040_ShuttleLaunch_station_rightoff", "TK_040_ShuttleLaunch_station_righton", "TK_040_ShuttleLaunch_station_leftleft". (Lookup Key)
---@param Step number Common Values = 0.0, 1.0, 0.1, 0.5, 2.0. 
function TrackedRides.ElementParams__Update__Step(Element, Step)
    DatabaseUtils.ExecuteQuery("ElementParams", "ElementParams__Update__Step", {Element, Step}, 2)
end

--- Note: Autogenerated.
---@param Element string Common Values = "TK_040_ShuttleLaunch_station_leftoff", "TK_040_ShuttleLaunch_station_lefton", "TK_040_ShuttleLaunch_station_rightoff", "TK_040_ShuttleLaunch_station_righton", "TK_040_ShuttleLaunch_station_leftleft". (Lookup Key)
---@param LabelOverride string|nil Common Values = nil, "TrackEditParam_DualDirectionBoostSpeed", "TrackEditParam_DualDirectionBrakeSpeed", "TrackEditParam_TrackMeshIndex_Roof", "". 
function TrackedRides.ElementParams__Update__LabelOverride(Element, LabelOverride)
    DatabaseUtils.ExecuteQuery("ElementParams", "ElementParams__Update__LabelOverride", {Element, LabelOverride}, 2)
end

--- Note: Autogenerated.
---@param Element string Common Values = "TK_040_ShuttleLaunch_station_leftoff", "TK_040_ShuttleLaunch_station_lefton", "TK_040_ShuttleLaunch_station_rightoff", "TK_040_ShuttleLaunch_station_righton", "TK_040_ShuttleLaunch_station_leftleft". (Lookup Key)
---@param ValueLabelSetName string|nil Common Values = nil, "TK_004_Turntable90L_Rev_StartToEnd", "TK_004_Turntable90L_StartToEnd", "TK_004_Turntable90R_Rev_StartToEnd", "TK_004_Turntable90R_StartToEnd". 
function TrackedRides.ElementParams__Update__ValueLabelSetName(Element, ValueLabelSetName)
    DatabaseUtils.ExecuteQuery("ElementParams", "ElementParams__Update__ValueLabelSetName", {Element, ValueLabelSetName}, 2)
end

--- Note: Autogenerated.
---@param Type string Common Values = "End", "Flumes", "Loops", "NonInverted", "Rolls". 
---@param Ordering integer Common Values = 1, 2, 3, 4, 5. 
function TrackedRides.ElementTypes__Insert(Type, Ordering)
    DatabaseUtils.ExecuteQuery("ElementTypes", "ElementTypes__Insert", {Type, Ordering}, 2)
end

--- Note: Autogenerated.
---@param Type string Common Values = "End", "Flumes", "Loops", "NonInverted", "Rolls". (Lookup Key)
---@param Icon string|nil Common Values = "CoasterEditorIconStation", "CoasterEditorTabLoops", "CoasterEditorTabUtilities", "CoasterEditorTabNoninverted", "CoasterEditorTabRolls". 
function TrackedRides.ElementTypes__Update__Icon(Type, Icon)
    DatabaseUtils.ExecuteQuery("ElementTypes", "ElementTypes__Update__Icon", {Type, Icon}, 2)
end

--- Note: Autogenerated.
---@param Type string Common Values = "End", "Flumes", "Loops", "NonInverted", "Rolls". (Lookup Key)
---@param Ordering integer Common Values = 1, 2, 3, 4, 5. 
function TrackedRides.ElementTypes__Update__Ordering(Type, Ordering)
    DatabaseUtils.ExecuteQuery("ElementTypes", "ElementTypes__Update__Ordering", {Type, Ordering}, 2)
end

--- Note: Autogenerated.
---@param Element string Common Values = "TK_205_Rails", "TK_205_StopStart", "train_default", "default_StopStart", "train_alt01". 
---@param Param string Common Values = "DropSupports", "TunnelRadius", "OptionalCatwalk", "MaxSpinRate", "DefaultStationLength". 
function TrackedRides.ElementUsesRideParams__Insert(Element, Param)
    DatabaseUtils.ExecuteQuery("ElementUsesRideParams", "ElementUsesRideParams__Insert", {Element, Param}, 2)
end

--- Note: Autogenerated.
---@param Element string Common Values = "TK_205_Rails", "TK_205_StopStart", "train_default", "default_StopStart", "train_alt01". (Lookup Key)
---@param Param string Common Values = "DropSupports", "TunnelRadius", "OptionalCatwalk", "MaxSpinRate", "DefaultStationLength". 
function TrackedRides.ElementUsesRideParams__Update__Param(Element, Param)
    DatabaseUtils.ExecuteQuery("ElementUsesRideParams", "ElementUsesRideParams__Update__Param", {Element, Param}, 2)
end

--- Note: Autogenerated.
---@param Name string Common Values = "Coaster_Invert", "Coaster_Manufacturer", "Coaster_Motion", "PDLC", "Ride_Age_Guests". 
---@param TextSymbol string Common Values = "InfoPanel_Manufacturer", "TagGroup_Coaster_Invert", "TagGroup_Coaster_Motion", "TagGroup_PDLC", "TagGroup_Ride_Age_Guests". 
function TrackedRides.FilterGroupDefinitions__Insert(Name, TextSymbol)
    DatabaseUtils.ExecuteQuery("FilterGroupDefinitions", "FilterGroupDefinitions__Insert", {Name, TextSymbol}, 2)
end

--- Note: Autogenerated.
---@param Name string Common Values = "Coaster_Invert", "Coaster_Manufacturer", "Coaster_Motion", "PDLC", "Ride_Age_Guests". (Lookup Key)
---@param TextSymbol string Common Values = "InfoPanel_Manufacturer", "TagGroup_Coaster_Invert", "TagGroup_Coaster_Motion", "TagGroup_PDLC", "TagGroup_Ride_Age_Guests". 
function TrackedRides.FilterGroupDefinitions__Update__TextSymbol(Name, TextSymbol)
    DatabaseUtils.ExecuteQuery("FilterGroupDefinitions", "FilterGroupDefinitions__Update__TextSymbol", {Name, TextSymbol}, 2)
end

--- Note: Autogenerated.
---@param Name string Common Values = "Coaster_Invert", "Coaster_Manufacturer", "Coaster_Motion", "PDLC", "Ride_Age_Guests". (Lookup Key)
---@param Ordering integer Default = 0. Common Values = 0, 6, 7, 9, 10. 
function TrackedRides.FilterGroupDefinitions__Update__Ordering(Name, Ordering)
    DatabaseUtils.ExecuteQuery("FilterGroupDefinitions", "FilterGroupDefinitions__Update__Ordering", {Name, Ordering}, 2)
end

--- Note: Autogenerated.
---@param GroupName string Common Values = "Coaster_Manufacturer", "Coaster_Motion", "Coaster_Invert", "PDLC", "Ride_Age_Guests". 
---@param TagName string Common Values = "Coaster_Manufacturer_Anton", "Coaster_Manufacturer_BigMsRides", "Coaster_Manufacturer_CityPeninsula", "Coaster_Manufacturer_DartKinetics", "Coaster_Manufacturer_DeepSeaContinental". 
function TrackedRides.FilterGroups__Insert(GroupName, TagName)
    DatabaseUtils.ExecuteQuery("FilterGroups", "FilterGroups__Insert", {GroupName, TagName}, 2)
end

--- Note: Autogenerated.
---@param GroupName string Common Values = "Coaster_Manufacturer", "Coaster_Motion", "Coaster_Invert", "PDLC", "Ride_Age_Guests". (Lookup Key)
---@param TagName string Common Values = "Coaster_Manufacturer_Anton", "Coaster_Manufacturer_BigMsRides", "Coaster_Manufacturer_CityPeninsula", "Coaster_Manufacturer_DartKinetics", "Coaster_Manufacturer_DeepSeaContinental". 
function TrackedRides.FilterGroups__Update__TagName(GroupName, TagName)
    DatabaseUtils.ExecuteQuery("FilterGroups", "FilterGroups__Update__TagName", {GroupName, TagName}, 2)
end

--- Note: Autogenerated.
---@param GroupName string Common Values = "Coaster_Manufacturer", "Coaster_Motion", "Coaster_Invert", "PDLC", "Ride_Age_Guests". (Lookup Key)
---@param Ordering integer Default = 0. Common Values = 1, 2, 3, 4, 5. 
function TrackedRides.FilterGroups__Update__Ordering(GroupName, Ordering)
    DatabaseUtils.ExecuteQuery("FilterGroups", "FilterGroups__Update__Ordering", {GroupName, Ordering}, 2)
end

--- Note: Autogenerated.
---@param Platform string Common Values = "Flume_Platform_Section". 
---@param Label string Common Values = "Flume_Platform_Small". 
---@param Description string Common Values = "Flume_Platform_Small_Desc". 
---@param Cost integer Common Values = 1000. 
---@param ContentPack string Common Values = "BaseGame". 
---@param ResearchLevel integer Common Values = 0. 
function TrackedRides.FlumePlatforms__Insert(Platform, Label, Description, Cost, ContentPack, ResearchLevel)
    DatabaseUtils.ExecuteQuery("FlumePlatforms", "FlumePlatforms__Insert", {Platform, Label, Description, Cost, ContentPack, ResearchLevel}, 6)
end

--- Note: Autogenerated.
---@param Platform string Common Values = "Flume_Platform_Section". (Lookup Key)
---@param Label string Common Values = "Flume_Platform_Small". 
function TrackedRides.FlumePlatforms__Update__Label(Platform, Label)
    DatabaseUtils.ExecuteQuery("FlumePlatforms", "FlumePlatforms__Update__Label", {Platform, Label}, 2)
end

--- Note: Autogenerated.
---@param Platform string Common Values = "Flume_Platform_Section". (Lookup Key)
---@param Icon string|nil Common Values = nil. 
function TrackedRides.FlumePlatforms__Update__Icon(Platform, Icon)
    DatabaseUtils.ExecuteQuery("FlumePlatforms", "FlumePlatforms__Update__Icon", {Platform, Icon}, 2)
end

--- Note: Autogenerated.
---@param Platform string Common Values = "Flume_Platform_Section". (Lookup Key)
---@param Description string Common Values = "Flume_Platform_Small_Desc". 
function TrackedRides.FlumePlatforms__Update__Description(Platform, Description)
    DatabaseUtils.ExecuteQuery("FlumePlatforms", "FlumePlatforms__Update__Description", {Platform, Description}, 2)
end

--- Note: Autogenerated.
---@param Platform string Common Values = "Flume_Platform_Section". (Lookup Key)
---@param Cost integer Common Values = 1000. 
function TrackedRides.FlumePlatforms__Update__Cost(Platform, Cost)
    DatabaseUtils.ExecuteQuery("FlumePlatforms", "FlumePlatforms__Update__Cost", {Platform, Cost}, 2)
end

--- Note: Autogenerated.
---@param Platform string Common Values = "Flume_Platform_Section". (Lookup Key)
---@param ContentPack string Common Values = "BaseGame". 
function TrackedRides.FlumePlatforms__Update__ContentPack(Platform, ContentPack)
    DatabaseUtils.ExecuteQuery("FlumePlatforms", "FlumePlatforms__Update__ContentPack", {Platform, ContentPack}, 2)
end

--- Note: Autogenerated.
---@param Platform string Common Values = "Flume_Platform_Section". (Lookup Key)
---@param ResearchLevel integer Common Values = 0. 
function TrackedRides.FlumePlatforms__Update__ResearchLevel(Platform, ResearchLevel)
    DatabaseUtils.ExecuteQuery("FlumePlatforms", "FlumePlatforms__Update__ResearchLevel", {Platform, ResearchLevel}, 2)
end

--- Note: Autogenerated.
---@param Platform string Common Values = "Flume_Platform_Section". (Lookup Key)
---@param SupportBasePrefab string|nil Common Values = "Flume_Platform_Section_SupportBase". 
function TrackedRides.FlumePlatforms__Update__SupportBasePrefab(Platform, SupportBasePrefab)
    DatabaseUtils.ExecuteQuery("FlumePlatforms", "FlumePlatforms__Update__SupportBasePrefab", {Platform, SupportBasePrefab}, 2)
end

--- Note: Autogenerated.
---@param Platform string Common Values = "Flume_Platform_Section". (Lookup Key)
---@param Width number Default = 4. Common Values = 4.0. 
function TrackedRides.FlumePlatforms__Update__Width(Platform, Width)
    DatabaseUtils.ExecuteQuery("FlumePlatforms", "FlumePlatforms__Update__Width", {Platform, Width}, 2)
end

--- Note: Autogenerated.
---@param Platform string Common Values = "Flume_Platform_Section". (Lookup Key)
---@param Length number Default = 4. Common Values = 4.0. 
function TrackedRides.FlumePlatforms__Update__Length(Platform, Length)
    DatabaseUtils.ExecuteQuery("FlumePlatforms", "FlumePlatforms__Update__Length", {Platform, Length}, 2)
end

--- Note: Autogenerated.
---@param Tag string Common Values = "Coaster", "Coaster_Manufacturer_Anton", "Coaster_Manufacturer_BigMsRides", "Coaster_Manufacturer_CityPeninsula", "Coaster_Manufacturer_DartKinetics". 
function TrackedRides.MetadataTags__Insert(Tag)
    DatabaseUtils.ExecuteQuery("MetadataTags", "MetadataTags__Insert", {Tag}, 1)
end

--- Note: Autogenerated.
---@param Tag string Common Values = "Coaster", "Coaster_Manufacturer_Anton", "Coaster_Manufacturer_BigMsRides", "Coaster_Manufacturer_CityPeninsula", "Coaster_Manufacturer_DartKinetics". (Lookup Key)
---@param TextSymbol string|nil Common Values = "ObjectBrowser_Coaster_Special", "Tag_Blueprint_Coaster", "Tag_Blueprint_PoweredRide", "Tag_Blueprint_TrackRide", "Tag_Blueprint_TransportRide". 
function TrackedRides.MetadataTags__Update__TextSymbol(Tag, TextSymbol)
    DatabaseUtils.ExecuteQuery("MetadataTags", "MetadataTags__Update__TextSymbol", {Tag, TextSymbol}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "AmericanArrow", "Barghest", "BodyFlume", "BodySlide", "BodySlideWide". 
---@param TrackCost number Common Values = 1.0, 0.25, 0.5. 
---@param Wear number Common Values = 5.0, 4.0, 3.0. 
---@param MaxTrackHeightFeet number Common Values = 199.0, 99.0, 20.0, 399.0, 299.0. 
---@param SplineElement string Common Values = "default_spline", "train_default", "flume_spline", "boomerang_default", "log_default". 
---@param StationElement string Common Values = "station_leftleft", "station_water_slide", "station_log_leftleft", "SpinCoaster_Station_leftleft", "station_boomerang_leftleft". 
---@param BlockSection boolean Common Values = 1, 0. 
---@param ContentPack string Common Values = "BaseGame", "Deluxe", "PDLC1", "Preorder". 
function TrackedRides.RideData__Insert(Ride, TrackCost, Wear, MaxTrackHeightFeet, SplineElement, StationElement, BlockSection, ContentPack)
    DatabaseUtils.ExecuteQuery("RideData", "RideData__Insert", {Ride, TrackCost, Wear, MaxTrackHeightFeet, SplineElement, StationElement, BlockSection, ContentPack}, 8)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "AmericanArrow", "Barghest", "BodyFlume", "BodySlide", "BodySlideWide". (Lookup Key)
---@param Track string|nil Common Values = "02_Vekoma_Track", "01_Box_Spline_Track", "22_Classic_Wooden", 4, 16. 
function TrackedRides.RideData__Update__Track(Ride, Track)
    DatabaseUtils.ExecuteQuery("RideData", "RideData__Update__Track", {Ride, Track}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "AmericanArrow", "Barghest", "BodyFlume", "BodySlide", "BodySlideWide". (Lookup Key)
---@param Name string|nil Common Values = "Manic Mouse", "Multiverse", "Omnicoaster", "SpinCoaster", "Vector". 
function TrackedRides.RideData__Update__Name(Ride, Name)
    DatabaseUtils.ExecuteQuery("RideData", "RideData__Update__Name", {Ride, Name}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "AmericanArrow", "Barghest", "BodyFlume", "BodySlide", "BodySlideWide". (Lookup Key)
---@param Class string|nil Common Values = "Thrill", "Family", "Junior". 
function TrackedRides.RideData__Update__Class(Ride, Class)
    DatabaseUtils.ExecuteQuery("RideData", "RideData__Update__Class", {Ride, Class}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "AmericanArrow", "Barghest", "BodyFlume", "BodySlide", "BodySlideWide". (Lookup Key)
---@param TrackCost number Common Values = 1.0, 0.25, 0.5. 
function TrackedRides.RideData__Update__TrackCost(Ride, TrackCost)
    DatabaseUtils.ExecuteQuery("RideData", "RideData__Update__TrackCost", {Ride, TrackCost}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "AmericanArrow", "Barghest", "BodyFlume", "BodySlide", "BodySlideWide". (Lookup Key)
---@param SpecificPowerMultiplier number Default = 1.0. Common Values = 1.0, 5.0, 0.2. 
function TrackedRides.RideData__Update__SpecificPowerMultiplier(Ride, SpecificPowerMultiplier)
    DatabaseUtils.ExecuteQuery("RideData", "RideData__Update__SpecificPowerMultiplier", {Ride, SpecificPowerMultiplier}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "AmericanArrow", "Barghest", "BodyFlume", "BodySlide", "BodySlideWide". (Lookup Key)
---@param Wear number Common Values = 5.0, 4.0, 3.0. 
function TrackedRides.RideData__Update__Wear(Ride, Wear)
    DatabaseUtils.ExecuteQuery("RideData", "RideData__Update__Wear", {Ride, Wear}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "AmericanArrow", "Barghest", "BodyFlume", "BodySlide", "BodySlideWide". (Lookup Key)
---@param MaxTrackHeightFeet number Common Values = 199.0, 99.0, 20.0, 399.0, 299.0. 
function TrackedRides.RideData__Update__MaxTrackHeightFeet(Ride, MaxTrackHeightFeet)
    DatabaseUtils.ExecuteQuery("RideData", "RideData__Update__MaxTrackHeightFeet", {Ride, MaxTrackHeightFeet}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "AmericanArrow", "Barghest", "BodyFlume", "BodySlide", "BodySlideWide". (Lookup Key)
---@param PlatformHeight number Default = 2. Common Values = 2.0, 0.25, 0.1, 5.0, 0.3. 
function TrackedRides.RideData__Update__PlatformHeight(Ride, PlatformHeight)
    DatabaseUtils.ExecuteQuery("RideData", "RideData__Update__PlatformHeight", {Ride, PlatformHeight}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "AmericanArrow", "Barghest", "BodyFlume", "BodySlide", "BodySlideWide". (Lookup Key)
---@param HeightAbovePlatform number Default = 0. Common Values = 0.0, -0.07, -0.58, -0.23, -0.31. 
function TrackedRides.RideData__Update__HeightAbovePlatform(Ride, HeightAbovePlatform)
    DatabaseUtils.ExecuteQuery("RideData", "RideData__Update__HeightAbovePlatform", {Ride, HeightAbovePlatform}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "AmericanArrow", "Barghest", "BodyFlume", "BodySlide", "BodySlideWide". (Lookup Key)
---@param TrackGapWidth number Default = 2. Common Values = 1.65, 2.3, 1.8363, 2.0, 1.2. 
function TrackedRides.RideData__Update__TrackGapWidth(Ride, TrackGapWidth)
    DatabaseUtils.ExecuteQuery("RideData", "RideData__Update__TrackGapWidth", {Ride, TrackGapWidth}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "AmericanArrow", "Barghest", "BodyFlume", "BodySlide", "BodySlideWide". (Lookup Key)
---@param TrackBlockWidth number Default = 4. Common Values = 8.0, 12.0, 16.0. 
function TrackedRides.RideData__Update__TrackBlockWidth(Ride, TrackBlockWidth)
    DatabaseUtils.ExecuteQuery("RideData", "RideData__Update__TrackBlockWidth", {Ride, TrackBlockWidth}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "AmericanArrow", "Barghest", "BodyFlume", "BodySlide", "BodySlideWide". (Lookup Key)
---@param PlatformBlockWidth number Default = 4. Common Values = 4.0, 0.0. 
function TrackedRides.RideData__Update__PlatformBlockWidth(Ride, PlatformBlockWidth)
    DatabaseUtils.ExecuteQuery("RideData", "RideData__Update__PlatformBlockWidth", {Ride, PlatformBlockWidth}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "AmericanArrow", "Barghest", "BodyFlume", "BodySlide", "BodySlideWide". (Lookup Key)
---@param SplineElement string Common Values = "default_spline", "train_default", "flume_spline", "boomerang_default", "log_default". 
function TrackedRides.RideData__Update__SplineElement(Ride, SplineElement)
    DatabaseUtils.ExecuteQuery("RideData", "RideData__Update__SplineElement", {Ride, SplineElement}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "AmericanArrow", "Barghest", "BodyFlume", "BodySlide", "BodySlideWide". (Lookup Key)
---@param StationElement string Common Values = "station_leftleft", "station_water_slide", "station_log_leftleft", "SpinCoaster_Station_leftleft", "station_boomerang_leftleft". 
function TrackedRides.RideData__Update__StationElement(Ride, StationElement)
    DatabaseUtils.ExecuteQuery("RideData", "RideData__Update__StationElement", {Ride, StationElement}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "AmericanArrow", "Barghest", "BodyFlume", "BodySlide", "BodySlideWide". (Lookup Key)
---@param ChainElement string|nil Common Values = "default_chainlift", "train_default", "", "default_LSM", "friction_wheel_lift". 
function TrackedRides.RideData__Update__ChainElement(Ride, ChainElement)
    DatabaseUtils.ExecuteQuery("RideData", "RideData__Update__ChainElement", {Ride, ChainElement}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "AmericanArrow", "Barghest", "BodyFlume", "BodySlide", "BodySlideWide". (Lookup Key)
---@param StationWidth number Default = 8. Common Values = 8.0, 1.2, 2.65, 2.2, 4.4. 
function TrackedRides.RideData__Update__StationWidth(Ride, StationWidth)
    DatabaseUtils.ExecuteQuery("RideData", "RideData__Update__StationWidth", {Ride, StationWidth}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "AmericanArrow", "Barghest", "BodyFlume", "BodySlide", "BodySlideWide". (Lookup Key)
---@param AudioType string|nil Default = Metal. Common Values = "Metal", "Stone", "WaterSlide", "Wood", "Hybrid". 
function TrackedRides.RideData__Update__AudioType(Ride, AudioType)
    DatabaseUtils.ExecuteQuery("RideData", "RideData__Update__AudioType", {Ride, AudioType}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "AmericanArrow", "Barghest", "BodyFlume", "BodySlide", "BodySlideWide". (Lookup Key)
---@param BlockSection boolean Common Values = 1, 0. 
function TrackedRides.RideData__Update__BlockSection(Ride, BlockSection)
    DatabaseUtils.ExecuteQuery("RideData", "RideData__Update__BlockSection", {Ride, BlockSection}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "AmericanArrow", "Barghest", "BodyFlume", "BodySlide", "BodySlideWide". (Lookup Key)
---@param MaxSlopeDeltaDegrees number Default = 90. Common Values = 90.0, 60.0, 45.0. 
function TrackedRides.RideData__Update__MaxSlopeDeltaDegrees(Ride, MaxSlopeDeltaDegrees)
    DatabaseUtils.ExecuteQuery("RideData", "RideData__Update__MaxSlopeDeltaDegrees", {Ride, MaxSlopeDeltaDegrees}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "AmericanArrow", "Barghest", "BodyFlume", "BodySlide", "BodySlideWide". (Lookup Key)
---@param MaxBankDeltaDegrees number Default = 90. Common Values = 90.0, 60.0, 30.0. 
function TrackedRides.RideData__Update__MaxBankDeltaDegrees(Ride, MaxBankDeltaDegrees)
    DatabaseUtils.ExecuteQuery("RideData", "RideData__Update__MaxBankDeltaDegrees", {Ride, MaxBankDeltaDegrees}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "AmericanArrow", "Barghest", "BodyFlume", "BodySlide", "BodySlideWide". (Lookup Key)
---@param BuildBackwards boolean Default = 0. Common Values = 0, 1. 
function TrackedRides.RideData__Update__BuildBackwards(Ride, BuildBackwards)
    DatabaseUtils.ExecuteQuery("RideData", "RideData__Update__BuildBackwards", {Ride, BuildBackwards}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "AmericanArrow", "Barghest", "BodyFlume", "BodySlide", "BodySlideWide". (Lookup Key)
---@param ContentPack string Common Values = "BaseGame", "Deluxe", "PDLC1", "Preorder". 
function TrackedRides.RideData__Update__ContentPack(Ride, ContentPack)
    DatabaseUtils.ExecuteQuery("RideData", "RideData__Update__ContentPack", {Ride, ContentPack}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "AmericanArrow", "Barghest", "BodyFlume", "BodySlide", "BodySlideWide". (Lookup Key)
---@param HeightOffsetOnWater number|nil Default = 0. Common Values = 0.0, 0.8. 
function TrackedRides.RideData__Update__HeightOffsetOnWater(Ride, HeightOffsetOnWater)
    DatabaseUtils.ExecuteQuery("RideData", "RideData__Update__HeightOffsetOnWater", {Ride, HeightOffsetOnWater}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "AmericanArrow", "Barghest", "BodyFlume", "BodySlide", "BodySlideWide". (Lookup Key)
---@param TrainTypeName string|nil Default = Car. Common Values = "Car", "Raft", "Boat", "Bus", "Gondola". 
function TrackedRides.RideData__Update__TrainTypeName(Ride, TrainTypeName)
    DatabaseUtils.ExecuteQuery("RideData", "RideData__Update__TrainTypeName", {Ride, TrainTypeName}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "AmericanArrow", "Barghest", "BodyFlume", "BodySlide", "BodySlideWide". (Lookup Key)
---@param GroupTrainTypeName string|nil Default = Train. Common Values = "Train", "Raft", "Boat", "Bus", "Group". 
function TrackedRides.RideData__Update__GroupTrainTypeName(Ride, GroupTrainTypeName)
    DatabaseUtils.ExecuteQuery("RideData", "RideData__Update__GroupTrainTypeName", {Ride, GroupTrainTypeName}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "AmericanArrow", "Barghest", "BodyFlume", "BodySlide", "BodySlideWide". (Lookup Key)
---@param CustomPlatformSpatial number|nil Default = 0. Common Values = 0.0. 
function TrackedRides.RideData__Update__CustomPlatformSpatial(Ride, CustomPlatformSpatial)
    DatabaseUtils.ExecuteQuery("RideData", "RideData__Update__CustomPlatformSpatial", {Ride, CustomPlatformSpatial}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "AmericanArrow", "Barghest", "BodyFlume", "BodySlide", "BodySlideWide". (Lookup Key)
---@param DefaultStationRailCount integer|nil Default = 1. Common Values = 1, 2. 
function TrackedRides.RideData__Update__DefaultStationRailCount(Ride, DefaultStationRailCount)
    DatabaseUtils.ExecuteQuery("RideData", "RideData__Update__DefaultStationRailCount", {Ride, DefaultStationRailCount}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "AmericanArrow", "Barghest", "BodyFlume", "BodySlide", "BodySlideWide". (Lookup Key)
---@param MaxStationCount integer|nil Default = 0. Common Values = 0, 2. 
function TrackedRides.RideData__Update__MaxStationCount(Ride, MaxStationCount)
    DatabaseUtils.ExecuteQuery("RideData", "RideData__Update__MaxStationCount", {Ride, MaxStationCount}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "AmericanArrow", "Barghest", "BodyFlume", "BodySlide", "BodySlideWide". (Lookup Key)
---@param LastTrackElement string|nil Common Values = nil, "", "Track_InnerTube_Flume_EndZone", "Track_Body_Flume_EndZone", "Track_Body_Slide_EndZone". 
function TrackedRides.RideData__Update__LastTrackElement(Ride, LastTrackElement)
    DatabaseUtils.ExecuteQuery("RideData", "RideData__Update__LastTrackElement", {Ride, LastTrackElement}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "AmericanArrow", "Barghest", "BodyFlume", "BodySlide", "BodySlideWide". (Lookup Key)
---@param ShuttleMode boolean Default = 0. Common Values = 0, 1. 
function TrackedRides.RideData__Update__ShuttleMode(Ride, ShuttleMode)
    DatabaseUtils.ExecuteQuery("RideData", "RideData__Update__ShuttleMode", {Ride, ShuttleMode}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "AmericanArrow", "Barghest", "BodyFlume", "BodySlide", "BodySlideWide". (Lookup Key)
---@param FlumePlacementOffset number Default = 0. Common Values = 0.0, 0.4, 1.6, 2.75. 
function TrackedRides.RideData__Update__FlumePlacementOffset(Ride, FlumePlacementOffset)
    DatabaseUtils.ExecuteQuery("RideData", "RideData__Update__FlumePlacementOffset", {Ride, FlumePlacementOffset}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "BodyFlume", "BodySlide", "BodySlideWide", "InnerTubeFlume", "InnerTubeFlumeDouble". 
---@param Platform string Common Values = "Flume_Platform_Section". 
function TrackedRides.RideFlumePlatforms__Insert(Ride, Platform)
    DatabaseUtils.ExecuteQuery("RideFlumePlatforms", "RideFlumePlatforms__Insert", {Ride, Platform}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "BodyFlume", "BodySlide", "BodySlideWide", "InnerTubeFlume", "InnerTubeFlumeDouble". (Lookup Key)
---@param Platform string Common Values = "Flume_Platform_Section". 
function TrackedRides.RideFlumePlatforms__Update__Platform(Ride, Platform)
    DatabaseUtils.ExecuteQuery("RideFlumePlatforms", "RideFlumePlatforms__Update__Platform", {Ride, Platform}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "CC_Bolt", "Barghest", "CC_F25", "CC_Infinite", "CC_Omnicoaster". 
---@param Tag string Common Values = "Filter_PDLC_None", "Type_TrackedRide_Coaster", "Filter_AgeGroup_AllAges", "Filter_Invert_NonInvert", "Filter_Propulsion_ChainLift". 
function TrackedRides.RideMetadataTags__Insert(Ride, Tag)
    DatabaseUtils.ExecuteQuery("RideMetadataTags", "RideMetadataTags__Insert", {Ride, Tag}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "CC_Bolt", "Barghest", "CC_F25", "CC_Infinite", "CC_Omnicoaster". (Lookup Key)
---@param Tag string Common Values = "Filter_PDLC_None", "Type_TrackedRide_Coaster", "Filter_AgeGroup_AllAges", "Filter_Invert_NonInvert", "Filter_Propulsion_ChainLift". 
function TrackedRides.RideMetadataTags__Update__Tag(Ride, Tag)
    DatabaseUtils.ExecuteQuery("RideMetadataTags", "RideMetadataTags__Update__Tag", {Ride, Tag}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "PTR_Tracker", "InnerTubeFlume", "InnerTubeFlumeDouble", "PTR_FDVision", "RaftFlume". 
---@param Param string Common Values = "DefaultStationLength", "DropSupports", "LengthRangeMetres", "SlopeRangeDegrees", "TunnelRadius". 
---@param Min number Common Values = 0.0, 4.0, -90.0, -50000.0, -2.0. 
---@param Max number Common Values = 1.0, 90.0, 7.0, 0.0, 20.0. 
---@param Initial number Common Values = 0.0, 5.0, 12.0, 16.0, 20.0. 
---@param Step number Common Values = 0.0, 1.0, 15.0, 4.0, 2.0. 
function TrackedRides.RideParams__Insert(Ride, Param, Min, Max, Initial, Step)
    DatabaseUtils.ExecuteQuery("RideParams", "RideParams__Insert", {Ride, Param, Min, Max, Initial, Step}, 6)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "PTR_Tracker", "InnerTubeFlume", "InnerTubeFlumeDouble", "PTR_FDVision", "RaftFlume". (Lookup Key)
---@param Param string Common Values = "DefaultStationLength", "DropSupports", "LengthRangeMetres", "SlopeRangeDegrees", "TunnelRadius". 
function TrackedRides.RideParams__Update__Param(Ride, Param)
    DatabaseUtils.ExecuteQuery("RideParams", "RideParams__Update__Param", {Ride, Param}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "PTR_Tracker", "InnerTubeFlume", "InnerTubeFlumeDouble", "PTR_FDVision", "RaftFlume". (Lookup Key)
---@param Min number Common Values = 0.0, 4.0, -90.0, -50000.0, -2.0. 
function TrackedRides.RideParams__Update__Min(Ride, Min)
    DatabaseUtils.ExecuteQuery("RideParams", "RideParams__Update__Min", {Ride, Min}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "PTR_Tracker", "InnerTubeFlume", "InnerTubeFlumeDouble", "PTR_FDVision", "RaftFlume". (Lookup Key)
---@param Max number Common Values = 1.0, 90.0, 7.0, 0.0, 20.0. 
function TrackedRides.RideParams__Update__Max(Ride, Max)
    DatabaseUtils.ExecuteQuery("RideParams", "RideParams__Update__Max", {Ride, Max}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "PTR_Tracker", "InnerTubeFlume", "InnerTubeFlumeDouble", "PTR_FDVision", "RaftFlume". (Lookup Key)
---@param Initial number Common Values = 0.0, 5.0, 12.0, 16.0, 20.0. 
function TrackedRides.RideParams__Update__Initial(Ride, Initial)
    DatabaseUtils.ExecuteQuery("RideParams", "RideParams__Update__Initial", {Ride, Initial}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "PTR_Tracker", "InnerTubeFlume", "InnerTubeFlumeDouble", "PTR_FDVision", "RaftFlume". (Lookup Key)
---@param Step number Common Values = 0.0, 1.0, 15.0, 4.0, 2.0. 
function TrackedRides.RideParams__Update__Step(Ride, Step)
    DatabaseUtils.ExecuteQuery("RideParams", "RideParams__Update__Step", {Ride, Step}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "PTR_Tracker", "InnerTubeFlume", "InnerTubeFlumeDouble", "PTR_FDVision", "RaftFlume". (Lookup Key)
---@param LabelOverride string|nil Common Values = nil, "TrackEditParam_CabinPitch", "TrackEditParam_CabinPitchSet", "TrackEditParam_OptionalRailing". 
function TrackedRides.RideParams__Update__LabelOverride(Ride, LabelOverride)
    DatabaseUtils.ExecuteQuery("RideParams", "RideParams__Update__LabelOverride", {Ride, LabelOverride}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "PTR_Tracker", "InnerTubeFlume", "InnerTubeFlumeDouble", "PTR_FDVision", "RaftFlume". (Lookup Key)
---@param ValueLabelSetName string|nil Common Values = nil. 
function TrackedRides.RideParams__Update__ValueLabelSetName(Ride, ValueLabelSetName)
    DatabaseUtils.ExecuteQuery("RideParams", "RideParams__Update__ValueLabelSetName", {Ride, ValueLabelSetName}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "PTR_Tracker", "InnerTubeFlume", "InnerTubeFlumeDouble", "PTR_FDVision", "RaftFlume". (Lookup Key)
---@param AbsoluteMin number|nil Common Values = nil, -50000.0, 4.0. 
function TrackedRides.RideParams__Update__AbsoluteMin(Ride, AbsoluteMin)
    DatabaseUtils.ExecuteQuery("RideParams", "RideParams__Update__AbsoluteMin", {Ride, AbsoluteMin}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "PTR_Tracker", "InnerTubeFlume", "InnerTubeFlumeDouble", "PTR_FDVision", "RaftFlume". (Lookup Key)
---@param AbsoluteMax number|nil Common Values = nil, 50000.0. 
function TrackedRides.RideParams__Update__AbsoluteMax(Ride, AbsoluteMax)
    DatabaseUtils.ExecuteQuery("RideParams", "RideParams__Update__AbsoluteMax", {Ride, AbsoluteMax}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "CC_BlackFalcon", "CC_Dragon", "CC_ManicMouse", "CC_SitdownCoaster", "CC_Sprint500". 
---@param Train string Common Values = "Rage", "Aethon", "AmericanArrow", "Bakasura", "Barghest". 
---@param Sort integer Common Values = 0, 290, 291, 380, 381. 
function TrackedRides.RideTrains__Insert(Ride, Train, Sort)
    DatabaseUtils.ExecuteQuery("RideTrains", "RideTrains__Insert", {Ride, Train, Sort}, 3)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "CC_BlackFalcon", "CC_Dragon", "CC_ManicMouse", "CC_SitdownCoaster", "CC_Sprint500". (Lookup Key)
---@param Train string Common Values = "Rage", "Aethon", "AmericanArrow", "Bakasura", "Barghest". 
function TrackedRides.RideTrains__Update__Train(Ride, Train)
    DatabaseUtils.ExecuteQuery("RideTrains", "RideTrains__Update__Train", {Ride, Train}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "CC_BlackFalcon", "CC_Dragon", "CC_ManicMouse", "CC_SitdownCoaster", "CC_Sprint500". (Lookup Key)
---@param Sort integer Common Values = 0, 290, 291, 380, 381. 
function TrackedRides.RideTrains__Update__Sort(Ride, Sort)
    DatabaseUtils.ExecuteQuery("RideTrains", "RideTrains__Update__Sort", {Ride, Sort}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "CC_BlackFalcon", "CC_Dragon", "CC_ManicMouse", "CC_SitdownCoaster", "CC_Sprint500". (Lookup Key)
---@param SceneryAttachmentGroup integer|nil Common Values = nil. 
function TrackedRides.RideTrains__Update__SceneryAttachmentGroup(Ride, SceneryAttachmentGroup)
    DatabaseUtils.ExecuteQuery("RideTrains", "RideTrains__Update__SceneryAttachmentGroup", {Ride, SceneryAttachmentGroup}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "CC_BlackFalcon", "CC_Enigma", "CC_F25", "CC_LoonyTurns", "CC_Splashdown". 
---@param Train string Common Values = "CC_Tiamat", "CC_Zenith", "Invincible", "Barghest", "CC_Enigma". 
---@param Sort integer Common Values = 280, 340, 360, 120, 210. 
function TrackedRides.RideTrains_Extra__Insert(Ride, Train, Sort)
    DatabaseUtils.ExecuteQuery("RideTrains_Extra", "RideTrains_Extra__Insert", {Ride, Train, Sort}, 3)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "CC_BlackFalcon", "CC_Enigma", "CC_F25", "CC_LoonyTurns", "CC_Splashdown". (Lookup Key)
---@param Train string Common Values = "CC_Tiamat", "CC_Zenith", "Invincible", "Barghest", "CC_Enigma". 
function TrackedRides.RideTrains_Extra__Update__Train(Ride, Train)
    DatabaseUtils.ExecuteQuery("RideTrains_Extra", "RideTrains_Extra__Update__Train", {Ride, Train}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "CC_BlackFalcon", "CC_Enigma", "CC_F25", "CC_LoonyTurns", "CC_Splashdown". (Lookup Key)
---@param Sort integer Common Values = 280, 340, 360, 120, 210. 
function TrackedRides.RideTrains_Extra__Update__Sort(Ride, Sort)
    DatabaseUtils.ExecuteQuery("RideTrains_Extra", "RideTrains_Extra__Update__Sort", {Ride, Sort}, 2)
end

--- Note: Autogenerated.
---@param Ride string Common Values = "CC_BlackFalcon", "CC_Enigma", "CC_F25", "CC_LoonyTurns", "CC_Splashdown". (Lookup Key)
---@param SceneryAttachmentGroup integer|nil Common Values = nil. 
function TrackedRides.RideTrains_Extra__Update__SceneryAttachmentGroup(Ride, SceneryAttachmentGroup)
    DatabaseUtils.ExecuteQuery("RideTrains_Extra", "RideTrains_Extra__Update__SceneryAttachmentGroup", {Ride, SceneryAttachmentGroup}, 2)
end

--- Note: Autogenerated.
---@param Name string Common Values = "AmericanArrow", "Barghest", "BodyFlume", "BodySlide", "BodySlideWide". 
---@param ExcitementRating number Common Values = 5.0. 
---@param IntensityRating number Common Values = 5.0. 
---@param NauseaRating number Common Values = 2.0, 5.0. 
---@param Prestige integer Common Values = 100. 
---@param TicketCost integer Common Values = 1000, 200, 500, 1200, 600. 
function TrackedRides.Simulation__Insert(Name, ExcitementRating, IntensityRating, NauseaRating, Prestige, TicketCost)
    DatabaseUtils.ExecuteQuery("Simulation", "Simulation__Insert", {Name, ExcitementRating, IntensityRating, NauseaRating, Prestige, TicketCost}, 6)
end

--- Note: Autogenerated.
---@param Name string Common Values = "AmericanArrow", "Barghest", "BodyFlume", "BodySlide", "BodySlideWide". (Lookup Key)
---@param ExcitementRating number Common Values = 5.0. 
function TrackedRides.Simulation__Update__ExcitementRating(Name, ExcitementRating)
    DatabaseUtils.ExecuteQuery("Simulation", "Simulation__Update__ExcitementRating", {Name, ExcitementRating}, 2)
end

--- Note: Autogenerated.
---@param Name string Common Values = "AmericanArrow", "Barghest", "BodyFlume", "BodySlide", "BodySlideWide". (Lookup Key)
---@param IntensityRating number Common Values = 5.0. 
function TrackedRides.Simulation__Update__IntensityRating(Name, IntensityRating)
    DatabaseUtils.ExecuteQuery("Simulation", "Simulation__Update__IntensityRating", {Name, IntensityRating}, 2)
end

--- Note: Autogenerated.
---@param Name string Common Values = "AmericanArrow", "Barghest", "BodyFlume", "BodySlide", "BodySlideWide". (Lookup Key)
---@param NauseaRating number Common Values = 2.0, 5.0. 
function TrackedRides.Simulation__Update__NauseaRating(Name, NauseaRating)
    DatabaseUtils.ExecuteQuery("Simulation", "Simulation__Update__NauseaRating", {Name, NauseaRating}, 2)
end

--- Note: Autogenerated.
---@param Name string Common Values = "AmericanArrow", "Barghest", "BodyFlume", "BodySlide", "BodySlideWide". (Lookup Key)
---@param Prestige integer Common Values = 100. 
function TrackedRides.Simulation__Update__Prestige(Name, Prestige)
    DatabaseUtils.ExecuteQuery("Simulation", "Simulation__Update__Prestige", {Name, Prestige}, 2)
end

--- Note: Autogenerated.
---@param Name string Common Values = "AmericanArrow", "Barghest", "BodyFlume", "BodySlide", "BodySlideWide". (Lookup Key)
---@param TicketCost integer Common Values = 1000, 200, 500, 1200, 600. 
function TrackedRides.Simulation__Update__TicketCost(Name, TicketCost)
    DatabaseUtils.ExecuteQuery("Simulation", "Simulation__Update__TicketCost", {Name, TicketCost}, 2)
end

--- Note: Autogenerated.
---@param Name string Common Values = "AmericanArrow", "Barghest", "BodyFlume", "BodySlide", "BodySlideWide". (Lookup Key)
---@param SupportsChildGuests boolean Default = 1. Common Values = 1, 0. 
function TrackedRides.Simulation__Update__SupportsChildGuests(Name, SupportsChildGuests)
    DatabaseUtils.ExecuteQuery("Simulation", "Simulation__Update__SupportsChildGuests", {Name, SupportsChildGuests}, 2)
end

--- Note: Autogenerated.
---@param Name string Common Values = "AmericanArrow", "Barghest", "BodyFlume", "BodySlide", "BodySlideWide". (Lookup Key)
---@param MaximumGroupSize integer|nil Common Values = nil, 4. 
function TrackedRides.Simulation__Update__MaximumGroupSize(Name, MaximumGroupSize)
    DatabaseUtils.ExecuteQuery("Simulation", "Simulation__Update__MaximumGroupSize", {Name, MaximumGroupSize}, 2)
end

--- Note: Autogenerated.
---@param Name string Common Values = "AmericanArrow", "Barghest", "BodyFlume", "BodySlide", "BodySlideWide". (Lookup Key)
---@param IsTransport boolean Default = 0. Common Values = 0, 1. 
function TrackedRides.Simulation__Update__IsTransport(Name, IsTransport)
    DatabaseUtils.ExecuteQuery("Simulation", "Simulation__Update__IsTransport", {Name, IsTransport}, 2)
end

--- Note: Autogenerated.
---@param Name string Common Values = "AmericanArrow", "Barghest", "BodyFlume", "BodySlide", "BodySlideWide". (Lookup Key)
---@param ResearchPack integer|nil Common Values = nil, 2600, 2200, 2201, 2202. 
function TrackedRides.Simulation__Update__ResearchPack(Name, ResearchPack)
    DatabaseUtils.ExecuteQuery("Simulation", "Simulation__Update__ResearchPack", {Name, ResearchPack}, 2)
end

--- Note: Autogenerated.
---@param Name string Common Values = "AmericanArrow", "Barghest", "BodyFlume", "BodySlide", "BodySlideWide". (Lookup Key)
---@param IsBoomerang boolean|nil Default = 0. Common Values = 0, 1. 
function TrackedRides.Simulation__Update__IsBoomerang(Name, IsBoomerang)
    DatabaseUtils.ExecuteQuery("Simulation", "Simulation__Update__IsBoomerang", {Name, IsBoomerang}, 2)
end

--- Note: Autogenerated.
---@param Name string Common Values = "AmericanArrow", "Barghest", "BodyFlume", "BodySlide", "BodySlideWide". (Lookup Key)
---@param IsLoopedAsDefault boolean|nil Default = 0. Common Values = 0, 1. 
function TrackedRides.Simulation__Update__IsLoopedAsDefault(Name, IsLoopedAsDefault)
    DatabaseUtils.ExecuteQuery("Simulation", "Simulation__Update__IsLoopedAsDefault", {Name, IsLoopedAsDefault}, 2)
end

--- Note: Autogenerated.
---@param Name string Common Values = "AmericanArrow", "Barghest", "BodyFlume", "BodySlide", "BodySlideWide". (Lookup Key)
---@param RequiresEndLoops boolean|nil Default = 0. Common Values = 0, 1. 
function TrackedRides.Simulation__Update__RequiresEndLoops(Name, RequiresEndLoops)
    DatabaseUtils.ExecuteQuery("Simulation", "Simulation__Update__RequiresEndLoops", {Name, RequiresEndLoops}, 2)
end

--- Note: Autogenerated.
---@param Name string Common Values = "AmericanArrow", "Barghest", "BodyFlume", "BodySlide", "BodySlideWide". (Lookup Key)
---@param IsNonStop boolean Default = 0. Common Values = 0, 1. 
function TrackedRides.Simulation__Update__IsNonStop(Name, IsNonStop)
    DatabaseUtils.ExecuteQuery("Simulation", "Simulation__Update__IsNonStop", {Name, IsNonStop}, 2)
end

--- Note: Autogenerated.
---@param Name string Common Values = "AmericanArrow", "Barghest", "BodyFlume", "BodySlide", "BodySlideWide". (Lookup Key)
---@param AllowsFreeEnds boolean|nil Default = 0. Common Values = 0. 
function TrackedRides.Simulation__Update__AllowsFreeEnds(Name, AllowsFreeEnds)
    DatabaseUtils.ExecuteQuery("Simulation", "Simulation__Update__AllowsFreeEnds", {Name, AllowsFreeEnds}, 2)
end

--- Note: Autogenerated.
---@param Name string Common Values = "AmericanArrow", "Barghest", "BodyFlume", "BodySlide", "BodySlideWide". (Lookup Key)
---@param IsWaterSlide boolean Default = 0. Common Values = 0, 1. 
function TrackedRides.Simulation__Update__IsWaterSlide(Name, IsWaterSlide)
    DatabaseUtils.ExecuteQuery("Simulation", "Simulation__Update__IsWaterSlide", {Name, IsWaterSlide}, 2)
end

--- Note: Autogenerated.
---@param Name string Common Values = "AmericanArrow", "Barghest", "BodyFlume", "BodySlide", "BodySlideWide". (Lookup Key)
---@param IsChildOnly boolean Default = 0. Common Values = 0. 
function TrackedRides.Simulation__Update__IsChildOnly(Name, IsChildOnly)
    DatabaseUtils.ExecuteQuery("Simulation", "Simulation__Update__IsChildOnly", {Name, IsChildOnly}, 2)
end

--- Note: Autogenerated.
---@param Name string Common Values = "AmericanArrow", "Barghest", "BodyFlume", "BodySlide", "BodySlideWide". (Lookup Key)
---@param ServiceInterval number|nil Default = 1800. Common Values = 2400.0. 
function TrackedRides.Simulation__Update__ServiceInterval(Name, ServiceInterval)
    DatabaseUtils.ExecuteQuery("Simulation", "Simulation__Update__ServiceInterval", {Name, ServiceInterval}, 2)
end

--- Note: Autogenerated.
---@param Name string Common Values = "AllowedOnWater", "AltBoosterAcceleration", "AltBoosterMaxSpeed", "AnimatedTrackBoostEnabled", "AnimatedTrackEndToStartAnimationType". 
---@param Enum integer Common Values = 0, 1, 2, 3, 4. 
---@param Sort integer Common Values = 200, 300, 301, 302, 303. 
function TrackedRides.TrackParamEnum__Insert(Name, Enum, Sort)
    DatabaseUtils.ExecuteQuery("TrackParamEnum", "TrackParamEnum__Insert", {Name, Enum, Sort}, 3)
end

--- Note: Autogenerated.
---@param Name string Common Values = "AllowedOnWater", "AltBoosterAcceleration", "AltBoosterMaxSpeed", "AnimatedTrackBoostEnabled", "AnimatedTrackEndToStartAnimationType". (Lookup Key)
---@param Enum integer Common Values = 0, 1, 2, 3, 4. 
function TrackedRides.TrackParamEnum__Update__Enum(Name, Enum)
    DatabaseUtils.ExecuteQuery("TrackParamEnum", "TrackParamEnum__Update__Enum", {Name, Enum}, 2)
end

--- Note: Autogenerated.
---@param Name string Common Values = "AllowedOnWater", "AltBoosterAcceleration", "AltBoosterMaxSpeed", "AnimatedTrackBoostEnabled", "AnimatedTrackEndToStartAnimationType". (Lookup Key)
---@param Icon string|nil Common Values = "CoasterEditorIconRuler", "CoasterEditorIconAngle". 
function TrackedRides.TrackParamEnum__Update__Icon(Name, Icon)
    DatabaseUtils.ExecuteQuery("TrackParamEnum", "TrackParamEnum__Update__Icon", {Name, Icon}, 2)
end

--- Note: Autogenerated.
---@param Name string Common Values = "AllowedOnWater", "AltBoosterAcceleration", "AltBoosterMaxSpeed", "AnimatedTrackBoostEnabled", "AnimatedTrackEndToStartAnimationType". (Lookup Key)
---@param Units string|nil Common Values = "PERCENTAGE", "METERS", "DEGREES", "METER_PER_SEC", "". 
function TrackedRides.TrackParamEnum__Update__Units(Name, Units)
    DatabaseUtils.ExecuteQuery("TrackParamEnum", "TrackParamEnum__Update__Units", {Name, Units}, 2)
end

--- Note: Autogenerated.
---@param Name string Common Values = "AllowedOnWater", "AltBoosterAcceleration", "AltBoosterMaxSpeed", "AnimatedTrackBoostEnabled", "AnimatedTrackEndToStartAnimationType". (Lookup Key)
---@param Multiplier number Default = 1. Common Values = 1.0, 0.01745329251994, -0.017453292519943295, -0.01745329251994, 0.017453292519943295. 
function TrackedRides.TrackParamEnum__Update__Multiplier(Name, Multiplier)
    DatabaseUtils.ExecuteQuery("TrackParamEnum", "TrackParamEnum__Update__Multiplier", {Name, Multiplier}, 2)
end

--- Note: Autogenerated.
---@param Name string Common Values = "AllowedOnWater", "AltBoosterAcceleration", "AltBoosterMaxSpeed", "AnimatedTrackBoostEnabled", "AnimatedTrackEndToStartAnimationType". (Lookup Key)
---@param Deadzone number Default = 0. Common Values = 0.0, 5.0. 
function TrackedRides.TrackParamEnum__Update__Deadzone(Name, Deadzone)
    DatabaseUtils.ExecuteQuery("TrackParamEnum", "TrackParamEnum__Update__Deadzone", {Name, Deadzone}, 2)
end

--- Note: Autogenerated.
---@param Name string Common Values = "AllowedOnWater", "AltBoosterAcceleration", "AltBoosterMaxSpeed", "AnimatedTrackBoostEnabled", "AnimatedTrackEndToStartAnimationType". (Lookup Key)
---@param Sort integer Common Values = 200, 300, 301, 302, 303. 
function TrackedRides.TrackParamEnum__Update__Sort(Name, Sort)
    DatabaseUtils.ExecuteQuery("TrackParamEnum", "TrackParamEnum__Update__Sort", {Name, Sort}, 2)
end

--- Note: Autogenerated.
---@param TrackedRideName string|nil Common Values = "CC_BigTimber", "CC_Multidimension", "CC_Multiverse", "CC_Omnicoaster", "CC_SitdownCoaster". 
function TrackedRides.TransitionList__Insert(TrackedRideName)
    DatabaseUtils.ExecuteQuery("TransitionList", "TransitionList__Insert", {TrackedRideName}, 1)
end

--- Note: Autogenerated.
---@param RideName string Common Values = "AmericanArrow", "Barghest", "BodyFlume", "BodySlide", "BodySlideWide". 
---@param UtilityType string Common Values = "Power", "Water". 
---@param RequiredUtilityQuantity number Common Values = 0.0, 60.0, 70.0, 80.0, 90.0. 
function TrackedRides.UtilityConsumer__Insert(RideName, UtilityType, RequiredUtilityQuantity)
    DatabaseUtils.ExecuteQuery("UtilityConsumer", "UtilityConsumer__Insert", {RideName, UtilityType, RequiredUtilityQuantity}, 3)
end

--- Note: Autogenerated.
---@param RideName string Common Values = "AmericanArrow", "Barghest", "BodyFlume", "BodySlide", "BodySlideWide". (Lookup Key)
---@param UtilityType string Common Values = "Power", "Water". 
function TrackedRides.UtilityConsumer__Update__UtilityType(RideName, UtilityType)
    DatabaseUtils.ExecuteQuery("UtilityConsumer", "UtilityConsumer__Update__UtilityType", {RideName, UtilityType}, 2)
end

--- Note: Autogenerated.
---@param RideName string Common Values = "AmericanArrow", "Barghest", "BodyFlume", "BodySlide", "BodySlideWide". (Lookup Key)
---@param RequiredUtilityQuantity number Common Values = 0.0, 60.0, 70.0, 80.0, 90.0. 
function TrackedRides.UtilityConsumer__Update__RequiredUtilityQuantity(RideName, RequiredUtilityQuantity)
    DatabaseUtils.ExecuteQuery("UtilityConsumer", "UtilityConsumer__Update__RequiredUtilityQuantity", {RideName, RequiredUtilityQuantity}, 2)
end

--- Note: Autogenerated.
---@param UtilityType string Common Values = "None", "Power", "Water". 
---@param EnumValue integer Common Values = 0, 1, 2. 
function TrackedRides.UtilityTypes__Insert(UtilityType, EnumValue)
    DatabaseUtils.ExecuteQuery("UtilityTypes", "UtilityTypes__Insert", {UtilityType, EnumValue}, 2)
end

--- Note: Autogenerated.
---@param UtilityType string Common Values = "None", "Power", "Water". (Lookup Key)
---@param EnumValue integer Common Values = 0, 1, 2. 
function TrackedRides.UtilityTypes__Update__EnumValue(UtilityType, EnumValue)
    DatabaseUtils.ExecuteQuery("UtilityTypes", "UtilityTypes__Update__EnumValue", {UtilityType, EnumValue}, 2)
end

--- Note: Autogenerated.
---@param Train string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". 
---@param NumCars integer Common Values = 1, 10, 8, 5, 2. 
---@param MinCars integer Common Values = 1, 2, 3, 5, 6. 
---@param MaxCars integer Common Values = 1, 10, 8, 5, 2. 
---@param IsDefaultTrainForRide boolean Common Values = 1, 0. 
function TrackedRides.Trains__Insert(Train, NumCars, MinCars, MaxCars, IsDefaultTrainForRide)
    DatabaseUtils.ExecuteQuery("Trains", "Trains__Insert", {Train, NumCars, MinCars, MaxCars, IsDefaultTrainForRide}, 5)
end

--- Note: Autogenerated.
---@param Train string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". (Lookup Key)
---@param Ride string|nil Common Values = "CC_BlackFalcon", "CC_Dragon", "CC_ManicMouse", "CC_SitdownCoaster", "CC_Sprint500". 
function TrackedRides.Trains__Update__Ride(Train, Ride)
    DatabaseUtils.ExecuteQuery("Trains", "Trains__Update__Ride", {Train, Ride}, 2)
end

--- Note: Autogenerated.
---@param Train string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". (Lookup Key)
---@param NumCars integer Common Values = 1, 10, 8, 5, 2. 
function TrackedRides.Trains__Update__NumCars(Train, NumCars)
    DatabaseUtils.ExecuteQuery("Trains", "Trains__Update__NumCars", {Train, NumCars}, 2)
end

--- Note: Autogenerated.
---@param Train string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". (Lookup Key)
---@param MinCars integer Common Values = 1, 2, 3, 5, 6. 
function TrackedRides.Trains__Update__MinCars(Train, MinCars)
    DatabaseUtils.ExecuteQuery("Trains", "Trains__Update__MinCars", {Train, MinCars}, 2)
end

--- Note: Autogenerated.
---@param Train string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". (Lookup Key)
---@param MaxCars integer Common Values = 1, 10, 8, 5, 2. 
function TrackedRides.Trains__Update__MaxCars(Train, MaxCars)
    DatabaseUtils.ExecuteQuery("Trains", "Trains__Update__MaxCars", {Train, MaxCars}, 2)
end

--- Note: Autogenerated.
---@param Train string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". (Lookup Key)
---@param Powered_MinSpeed number|nil Default = 0. Common Values = 0.0, 1.34112, 2.2352, 0.44704, 2.235. 
function TrackedRides.Trains__Update__Powered_MinSpeed(Train, Powered_MinSpeed)
    DatabaseUtils.ExecuteQuery("Trains", "Trains__Update__Powered_MinSpeed", {Train, Powered_MinSpeed}, 2)
end

--- Note: Autogenerated.
---@param Train string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". (Lookup Key)
---@param Powered_MaxSpeed number|nil Default = 0. Common Values = 0.0, 6.7056, 4.4704, 8.9408, 0.44704. 
function TrackedRides.Trains__Update__Powered_MaxSpeed(Train, Powered_MaxSpeed)
    DatabaseUtils.ExecuteQuery("Trains", "Trains__Update__Powered_MaxSpeed", {Train, Powered_MaxSpeed}, 2)
end

--- Note: Autogenerated.
---@param Train string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". (Lookup Key)
---@param Powered_DefaultSpeed number|nil Default = 0. Common Values = 0.0, 2.2352, 0.44704, 4.47, 6.706. 
function TrackedRides.Trains__Update__Powered_DefaultSpeed(Train, Powered_DefaultSpeed)
    DatabaseUtils.ExecuteQuery("Trains", "Trains__Update__Powered_DefaultSpeed", {Train, Powered_DefaultSpeed}, 2)
end

--- Note: Autogenerated.
---@param Train string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". (Lookup Key)
---@param Powered_SpeedRangeMinDelta number|nil Default = 0. Common Values = 0.0, 0.44704, 1.34112, 1.7, 0.447. 
function TrackedRides.Trains__Update__Powered_SpeedRangeMinDelta(Train, Powered_SpeedRangeMinDelta)
    DatabaseUtils.ExecuteQuery("Trains", "Trains__Update__Powered_SpeedRangeMinDelta", {Train, Powered_SpeedRangeMinDelta}, 2)
end

--- Note: Autogenerated.
---@param Train string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". (Lookup Key)
---@param Powered_SpeedRangeMaxDelta number|nil Default = 0. Common Values = 0.0, 0.44704, 1.34112, 2.2352, 0.447. 
function TrackedRides.Trains__Update__Powered_SpeedRangeMaxDelta(Train, Powered_SpeedRangeMaxDelta)
    DatabaseUtils.ExecuteQuery("Trains", "Trains__Update__Powered_SpeedRangeMaxDelta", {Train, Powered_SpeedRangeMaxDelta}, 2)
end

--- Note: Autogenerated.
---@param Train string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". (Lookup Key)
---@param AllowCrashTestDummies boolean|nil Default = 1. Common Values = 1, 0. 
function TrackedRides.Trains__Update__AllowCrashTestDummies(Train, AllowCrashTestDummies)
    DatabaseUtils.ExecuteQuery("Trains", "Trains__Update__AllowCrashTestDummies", {Train, AllowCrashTestDummies}, 2)
end

--- Note: Autogenerated.
---@param Train string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". (Lookup Key)
---@param IsRacing boolean Default = 0. Common Values = 0, 1. 
function TrackedRides.Trains__Update__IsRacing(Train, IsRacing)
    DatabaseUtils.ExecuteQuery("Trains", "Trains__Update__IsRacing", {Train, IsRacing}, 2)
end

--- Note: Autogenerated.
---@param Train string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". (Lookup Key)
---@param NumPassesThroughStation integer Default = 1. Common Values = 1, 3, 2. 
function TrackedRides.Trains__Update__NumPassesThroughStation(Train, NumPassesThroughStation)
    DatabaseUtils.ExecuteQuery("Trains", "Trains__Update__NumPassesThroughStation", {Train, NumPassesThroughStation}, 2)
end

--- Note: Autogenerated.
---@param Train string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". (Lookup Key)
---@param MinNumPassesThroughStation integer Default = 1. Common Values = 1, 3, 2. 
function TrackedRides.Trains__Update__MinNumPassesThroughStation(Train, MinNumPassesThroughStation)
    DatabaseUtils.ExecuteQuery("Trains", "Trains__Update__MinNumPassesThroughStation", {Train, MinNumPassesThroughStation}, 2)
end

--- Note: Autogenerated.
---@param Train string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". (Lookup Key)
---@param MaxNumPassesThroughStation integer Default = 1. Common Values = 3, 1, 10, 7. 
function TrackedRides.Trains__Update__MaxNumPassesThroughStation(Train, MaxNumPassesThroughStation)
    DatabaseUtils.ExecuteQuery("Trains", "Trains__Update__MaxNumPassesThroughStation", {Train, MaxNumPassesThroughStation}, 2)
end

--- Note: Autogenerated.
---@param Train string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". (Lookup Key)
---@param HardMaxTrains integer Default = 20. Common Values = 20, 1, 99. 
function TrackedRides.Trains__Update__HardMaxTrains(Train, HardMaxTrains)
    DatabaseUtils.ExecuteQuery("Trains", "Trains__Update__HardMaxTrains", {Train, HardMaxTrains}, 2)
end

--- Note: Autogenerated.
---@param Train string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". (Lookup Key)
---@param Powered_Behaviour integer Default = 0. Common Values = 0, 1. 
function TrackedRides.Trains__Update__Powered_Behaviour(Train, Powered_Behaviour)
    DatabaseUtils.ExecuteQuery("Trains", "Trains__Update__Powered_Behaviour", {Train, Powered_Behaviour}, 2)
end

--- Note: Autogenerated.
---@param Train string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". (Lookup Key)
---@param Powered_CanChangeBehaviour boolean Default = 0. Common Values = 0, 1. 
function TrackedRides.Trains__Update__Powered_CanChangeBehaviour(Train, Powered_CanChangeBehaviour)
    DatabaseUtils.ExecuteQuery("Trains", "Trains__Update__Powered_CanChangeBehaviour", {Train, Powered_CanChangeBehaviour}, 2)
end

--- Note: Autogenerated.
---@param Train string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". (Lookup Key)
---@param IsDefaultTrainForRide boolean Common Values = 1, 0. 
function TrackedRides.Trains__Update__IsDefaultTrainForRide(Train, IsDefaultTrainForRide)
    DatabaseUtils.ExecuteQuery("Trains", "Trains__Update__IsDefaultTrainForRide", {Train, IsDefaultTrainForRide}, 2)
end


return TrackedRides
