---
--- NOTE: THIS FILE IS AUTOGENERATED.
--- PLEASE NOTE THAT THIS IS SUBJECT TO CHANGE
--- BETWEEN EACH VERSION. IF BROKEN BY AN UPDATE,
--- REGENERATE VIA THE SCRIPT IN SQLBINDINGFOLDER.
--- 
local global = _G
local ipairs = global.ipairs
local DatabaseUtils = require("forgeutils.internal.database.databaseutils")

local logger = require("forgeutils.logger").Get("TrackedRideCars")

---@class forgeutils.internal.database.TrackedRideCars
--- Note: Autogenerated!
--- This is a generated lua binding layer for the TrackedRideCars database.
local TrackedRideCars = {}

---@private
--- This method is called after data is merged
TrackedRideCars.InsertToDBs = function()
    TrackedRideCars.BindPreparedStatements()
end

TrackedRideCars.tPreparedStatements = {
    "TrackedRideCars_Cars", 
    "TrackedRideCars_CatchTrains", 
    "TrackedRideCars_RacingTrains", 
    "TrackedRideCars_Trains", 
    "TrackedRideCars_TransitionList", 
    "TrackedRideCars_WhichCar"
}

---@private
function TrackedRideCars.BindPreparedStatements()
    logger:DebugQuery("BindPreparedStatements()")
    for _, filename in ipairs(TrackedRideCars.tPreparedStatements) do
        DatabaseUtils.BindPreparedStatement("TrackedRideCars", filename)
    end
end


--- Note: Autogenerated.
--- Selector for table Cars.
---@param TrainID string Common Values = "Speed", "PTR_PoweredCoaster", "AmericanArrow", "CC_Bolt", "CC_TiltCoaster". 
---@param CarID string Common Values = "BodyFlumeCarF", "BodySlideCarF", "CC_AethonCarF", "CC_AethonCarM", "CC_AethonCarR". 
---@return table|nil data
function TrackedRideCars.Cars__Select(TrainID, CarID)
    local results = DatabaseUtils.ExecuteQuery("TrackedRideCars", "Cars__Select", {TrainID, CarID}, 2)
    if results == nil then
        return nil
    end
    local result = results[1]
    if result == nil then
        return nil
    end
    return {
        TrainID = result[1] or nil,
        WhichCar = result[2] or nil,
        CarOrder = result[3] or nil,
        CarID = result[4] or nil,
        Prefab = result[5] or nil,
        Mass = result[6] or nil,
        PlatformPrefab = result[7] or nil,
        IsPowered = result[8] or nil,
    }
end

--- Note: Autogenerated.
--- Inserter for table Cars.
---@param TrainID string Common Values = "Speed", "PTR_PoweredCoaster", "AmericanArrow", "CC_Bolt", "CC_TiltCoaster". 
---@param CarID string Common Values = "BodyFlumeCarF", "BodySlideCarF", "CC_AethonCarF", "CC_AethonCarM", "CC_AethonCarR". 
---@param Mass number Common Values = 100.0, 140.0, 700.0, 1200.0, 800.0. 
---@return nil
function TrackedRideCars.Cars__Insert(TrainID, CarID, Mass)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "Cars__Insert", {TrainID, CarID, Mass}, 3)
end

--- Note: Autogenerated.
--- Updates field "WhichCar" in Cars. Common Values = "Front", "Middle", "Rear". 
---@param TrainID string Common Values = "Speed", "PTR_PoweredCoaster", "AmericanArrow", "CC_Bolt", "CC_TiltCoaster".  (Lookup Key)
---@param CarID string Common Values = "BodyFlumeCarF", "BodySlideCarF", "CC_AethonCarF", "CC_AethonCarM", "CC_AethonCarR".  (Lookup Key)
---@param WhichCar string|nil Common Values = "Front", "Middle", "Rear". 
---@return nil
function TrackedRideCars.Cars__Update__WhichCar(TrainID, CarID, WhichCar)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "Cars__Update__WhichCar", {TrainID, CarID, WhichCar}, 3)
end

--- Note: Autogenerated.
--- Updates field "CarOrder" in Cars. Default = "0". Common Values = 0, 1, 2, 3, 4. 
---@param TrainID string Common Values = "Speed", "PTR_PoweredCoaster", "AmericanArrow", "CC_Bolt", "CC_TiltCoaster".  (Lookup Key)
---@param CarID string Common Values = "BodyFlumeCarF", "BodySlideCarF", "CC_AethonCarF", "CC_AethonCarM", "CC_AethonCarR".  (Lookup Key)
---@param CarOrder integer|nil Default = "0". Common Values = 0, 1, 2, 3, 4. 
---@return nil
function TrackedRideCars.Cars__Update__CarOrder(TrainID, CarID, CarOrder)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "Cars__Update__CarOrder", {TrainID, CarID, CarOrder}, 3)
end

--- Note: Autogenerated.
--- Updates field "Prefab" in Cars. Common Values = "CC_BakasuraCarF_Art", "TR_GondolaCarF_Game", "BodyFlumeCarF_Art", "BodySlideCarF_Art", "CC_AethonCarF_Art". 
---@param TrainID string Common Values = "Speed", "PTR_PoweredCoaster", "AmericanArrow", "CC_Bolt", "CC_TiltCoaster".  (Lookup Key)
---@param CarID string Common Values = "BodyFlumeCarF", "BodySlideCarF", "CC_AethonCarF", "CC_AethonCarM", "CC_AethonCarR".  (Lookup Key)
---@param Prefab string|nil Common Values = "CC_BakasuraCarF_Art", "TR_GondolaCarF_Game", "BodyFlumeCarF_Art", "BodySlideCarF_Art", "CC_AethonCarF_Art". 
---@return nil
function TrackedRideCars.Cars__Update__Prefab(TrainID, CarID, Prefab)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "Cars__Update__Prefab", {TrainID, CarID, Prefab}, 3)
end

--- Note: Autogenerated.
--- Updates field "Mass" in Cars. Common Values = 100.0, 140.0, 700.0, 1200.0, 800.0. 
---@param TrainID string Common Values = "Speed", "PTR_PoweredCoaster", "AmericanArrow", "CC_Bolt", "CC_TiltCoaster".  (Lookup Key)
---@param CarID string Common Values = "BodyFlumeCarF", "BodySlideCarF", "CC_AethonCarF", "CC_AethonCarM", "CC_AethonCarR".  (Lookup Key)
---@param Mass number Common Values = 100.0, 140.0, 700.0, 1200.0, 800.0. 
---@return nil
function TrackedRideCars.Cars__Update__Mass(TrainID, CarID, Mass)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "Cars__Update__Mass", {TrainID, CarID, Mass}, 3)
end

--- Note: Autogenerated.
--- Updates field "PlatformPrefab" in Cars. Common Values = nil, "StationPlatform_CC_Stingray_Front", "StationPlatform_CC_Stingray_Mid", "StationPlatform_CC_Stingray_Rear", "StationPlatform_CC_Aethon_Front". 
---@param TrainID string Common Values = "Speed", "PTR_PoweredCoaster", "AmericanArrow", "CC_Bolt", "CC_TiltCoaster".  (Lookup Key)
---@param CarID string Common Values = "BodyFlumeCarF", "BodySlideCarF", "CC_AethonCarF", "CC_AethonCarM", "CC_AethonCarR".  (Lookup Key)
---@param PlatformPrefab string|nil Common Values = nil, "StationPlatform_CC_Stingray_Front", "StationPlatform_CC_Stingray_Mid", "StationPlatform_CC_Stingray_Rear", "StationPlatform_CC_Aethon_Front". 
---@return nil
function TrackedRideCars.Cars__Update__PlatformPrefab(TrainID, CarID, PlatformPrefab)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "Cars__Update__PlatformPrefab", {TrainID, CarID, PlatformPrefab}, 3)
end

--- Note: Autogenerated.
--- Updates field "IsPowered" in Cars. Default = "0". Common Values = 0, 1. 
---@param TrainID string Common Values = "Speed", "PTR_PoweredCoaster", "AmericanArrow", "CC_Bolt", "CC_TiltCoaster".  (Lookup Key)
---@param CarID string Common Values = "BodyFlumeCarF", "BodySlideCarF", "CC_AethonCarF", "CC_AethonCarM", "CC_AethonCarR".  (Lookup Key)
---@param IsPowered boolean|nil Default = "0". Common Values = 0, 1. 
---@return nil
function TrackedRideCars.Cars__Update__IsPowered(TrainID, CarID, IsPowered)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "Cars__Update__IsPowered", {TrainID, CarID, IsPowered}, 3)
end

--- Note: Autogenerated.
--- Selector for table CatchTrains.
---@param TrainID string Common Values = "TK_010_CableHookCar", "TK_010_CatchCar", "TK_014_CatchCar_001", "TK_014_CatchCar_002", "TK_015_CatchCar". 
---@return table|nil data
function TrackedRideCars.CatchTrains__Select(TrainID)
    local results = DatabaseUtils.ExecuteQuery("TrackedRideCars", "CatchTrains__Select", {TrainID}, 1)
    if results == nil then
        return nil
    end
    local result = results[1]
    if result == nil then
        return nil
    end
    return {
        TrainID = result[1] or nil,
        ShouldWait = result[2] or nil,
        CatchOnReturn = result[3] or nil,
        MatchSpeed = result[4] or nil,
        CatchOnFinalLap = result[5] or nil,
    }
end

--- Note: Autogenerated.
--- Inserter for table CatchTrains.
---@param TrainID string Common Values = "TK_010_CableHookCar", "TK_010_CatchCar", "TK_014_CatchCar_001", "TK_014_CatchCar_002", "TK_015_CatchCar". 
---@return nil
function TrackedRideCars.CatchTrains__Insert(TrainID)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "CatchTrains__Insert", {TrainID}, 1)
end

--- Note: Autogenerated.
--- Updates field "ShouldWait" in CatchTrains. Default = "0". Common Values = 0, 1. 
---@param TrainID string Common Values = "TK_010_CableHookCar", "TK_010_CatchCar", "TK_014_CatchCar_001", "TK_014_CatchCar_002", "TK_015_CatchCar".  (Lookup Key)
---@param ShouldWait boolean Default = "0". Common Values = 0, 1. 
---@return nil
function TrackedRideCars.CatchTrains__Update__ShouldWait(TrainID, ShouldWait)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "CatchTrains__Update__ShouldWait", {TrainID, ShouldWait}, 2)
end

--- Note: Autogenerated.
--- Updates field "CatchOnReturn" in CatchTrains. Default = "0". Common Values = 0, 1. 
---@param TrainID string Common Values = "TK_010_CableHookCar", "TK_010_CatchCar", "TK_014_CatchCar_001", "TK_014_CatchCar_002", "TK_015_CatchCar".  (Lookup Key)
---@param CatchOnReturn boolean Default = "0". Common Values = 0, 1. 
---@return nil
function TrackedRideCars.CatchTrains__Update__CatchOnReturn(TrainID, CatchOnReturn)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "CatchTrains__Update__CatchOnReturn", {TrainID, CatchOnReturn}, 2)
end

--- Note: Autogenerated.
--- Updates field "MatchSpeed" in CatchTrains. Default = "0". Common Values = 0, 1. 
---@param TrainID string Common Values = "TK_010_CableHookCar", "TK_010_CatchCar", "TK_014_CatchCar_001", "TK_014_CatchCar_002", "TK_015_CatchCar".  (Lookup Key)
---@param MatchSpeed boolean Default = "0". Common Values = 0, 1. 
---@return nil
function TrackedRideCars.CatchTrains__Update__MatchSpeed(TrainID, MatchSpeed)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "CatchTrains__Update__MatchSpeed", {TrainID, MatchSpeed}, 2)
end

--- Note: Autogenerated.
--- Updates field "CatchOnFinalLap" in CatchTrains. Default = "0". Common Values = 0, 1. 
---@param TrainID string Common Values = "TK_010_CableHookCar", "TK_010_CatchCar", "TK_014_CatchCar_001", "TK_014_CatchCar_002", "TK_015_CatchCar".  (Lookup Key)
---@param CatchOnFinalLap boolean Default = "0". Common Values = 0, 1. 
---@return nil
function TrackedRideCars.CatchTrains__Update__CatchOnFinalLap(TrainID, CatchOnFinalLap)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "CatchTrains__Update__CatchOnFinalLap", {TrainID, CatchOnFinalLap}, 2)
end

--- Note: Autogenerated.
--- Selector for table RacingTrains.
---@param TrainID string Common Values = "Speed". 
---@return table|nil data
function TrackedRideCars.RacingTrains__Select(TrainID)
    local results = DatabaseUtils.ExecuteQuery("TrackedRideCars", "RacingTrains__Select", {TrainID}, 1)
    if results == nil then
        return nil
    end
    local result = results[1]
    if result == nil then
        return nil
    end
    return {
        TrainID = result[1] or nil,
        PitOffset = result[2] or nil,
        PitFront = result[3] or nil,
        PitStep = result[4] or nil,
        StartingOffset = result[5] or nil,
        StartingFront = result[6] or nil,
        StartingStep = result[7] or nil,
    }
end

--- Note: Autogenerated.
--- Inserter for table RacingTrains.
---@param TrainID string Common Values = "Speed". 
---@return nil
function TrackedRideCars.RacingTrains__Insert(TrainID)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "RacingTrains__Insert", {TrainID}, 1)
end

--- Note: Autogenerated.
--- Updates field "PitOffset" in RacingTrains. Common Values = 5.067. 
---@param TrainID string Common Values = "Speed".  (Lookup Key)
---@param PitOffset number|nil Common Values = 5.067. 
---@return nil
function TrackedRideCars.RacingTrains__Update__PitOffset(TrainID, PitOffset)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "RacingTrains__Update__PitOffset", {TrainID, PitOffset}, 2)
end

--- Note: Autogenerated.
--- Updates field "PitFront" in RacingTrains. Common Values = 7.0. 
---@param TrainID string Common Values = "Speed".  (Lookup Key)
---@param PitFront number|nil Common Values = 7.0. 
---@return nil
function TrackedRideCars.RacingTrains__Update__PitFront(TrainID, PitFront)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "RacingTrains__Update__PitFront", {TrainID, PitFront}, 2)
end

--- Note: Autogenerated.
--- Updates field "PitStep" in RacingTrains. Common Values = 4.5. 
---@param TrainID string Common Values = "Speed".  (Lookup Key)
---@param PitStep number|nil Common Values = 4.5. 
---@return nil
function TrackedRideCars.RacingTrains__Update__PitStep(TrainID, PitStep)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "RacingTrains__Update__PitStep", {TrainID, PitStep}, 2)
end

--- Note: Autogenerated.
--- Updates field "StartingOffset" in RacingTrains. Common Values = 1.8. 
---@param TrainID string Common Values = "Speed".  (Lookup Key)
---@param StartingOffset number|nil Common Values = 1.8. 
---@return nil
function TrackedRideCars.RacingTrains__Update__StartingOffset(TrainID, StartingOffset)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "RacingTrains__Update__StartingOffset", {TrainID, StartingOffset}, 2)
end

--- Note: Autogenerated.
--- Updates field "StartingFront" in RacingTrains. Common Values = 3.5. 
---@param TrainID string Common Values = "Speed".  (Lookup Key)
---@param StartingFront number|nil Common Values = 3.5. 
---@return nil
function TrackedRideCars.RacingTrains__Update__StartingFront(TrainID, StartingFront)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "RacingTrains__Update__StartingFront", {TrainID, StartingFront}, 2)
end

--- Note: Autogenerated.
--- Updates field "StartingStep" in RacingTrains. Common Values = 4.4. 
---@param TrainID string Common Values = "Speed".  (Lookup Key)
---@param StartingStep number|nil Common Values = 4.4. 
---@return nil
function TrackedRideCars.RacingTrains__Update__StartingStep(TrainID, StartingStep)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "RacingTrains__Update__StartingStep", {TrainID, StartingStep}, 2)
end

--- Note: Autogenerated.
--- Selector for table Trains.
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". 
---@return table|nil data
function TrackedRideCars.Trains__Select(TrainID)
    local results = DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Select", {TrainID}, 1)
    if results == nil then
        return nil
    end
    local result = results[1]
    if result == nil then
        return nil
    end
    return {
        TrainID = result[1] or nil,
        StaticFriction = result[2] or nil,
        AirResistance = result[3] or nil,
        DynamicFriction = result[4] or nil,
        DynamicFriction_Alternate = result[5] or nil,
        LuaScoringModule = result[6] or nil,
        BaseExcitement = result[7] or nil,
        BaseFear = result[8] or nil,
        BaseNausea = result[9] or nil,
        CanAddOffStation = result[10] or nil,
        AudioSpeedThreshold = result[11] or nil,
        AudioAccnThreshold = result[12] or nil,
        AudioWeightThreshold = result[13] or nil,
        AudioLateralThreshold = result[14] or nil,
        AudioUseFrontAxelForFlanges = result[15] or nil,
        AudioIgnoreFrontCarForFlanges = result[16] or nil,
        AudioIgnoreRearCarForFlanges = result[17] or nil,
        AudioIgnoreMidCarsForFlanges = result[18] or nil,
        AudioChainLiftPrefix = result[19] or nil,
        AudioBrakePrefix = result[20] or nil,
        DefaultRideMusic = result[21] or nil,
        UniqueEngineSound = result[22] or nil,
        PlayMusicContinuously = result[23] or nil,
        PlayMusicOnAllCarsSimultaneously = result[24] or nil,
        AudioGuestsUseExcitement = result[25] or nil,
        AudioGuestsUseFear = result[26] or nil,
        AudioGuestsUseSpecialBehaviour = result[27] or nil,
        UseTransportRideMusic = result[28] or nil,
        TreatAsCoaster = result[29] or nil,
        AudioMaxRange = result[30] or nil,
        CatchTrainType = result[31] or nil,
        NumCatchCars = result[32] or nil,
        ReverseCatchTrainType = result[33] or nil,
        NumReverseCatchCars = result[34] or nil,
        SplitCatchTrainType = result[35] or nil,
        SplitNormalTrainDelay = result[36] or nil,
        AudioPrefixOverride = result[37] or nil,
        UseMirrorCarRotation = result[38] or nil,
        ForceCarAttachOffsetYToZero = result[39] or nil,
        ForceCarAttachOffsetYToValue = result[40] or nil,
        AudioCabinIsEnclosed = result[41] or nil,
        IsWaterSlideTrain = result[42] or nil,
    }
end

--- Note: Autogenerated.
--- Inserter for table Trains.
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". 
---@param CanAddOffStation boolean Common Values = 0, 1. 
---@return nil
function TrackedRideCars.Trains__Insert(TrainID, CanAddOffStation)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Insert", {TrainID, CanAddOffStation}, 2)
end

--- Note: Autogenerated.
--- Updates field "StaticFriction" in Trains. Default = "0.06". Common Values = 0.06, 0.0. 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param StaticFriction number|nil Default = "0.06". Common Values = 0.06, 0.0. 
---@return nil
function TrackedRideCars.Trains__Update__StaticFriction(TrainID, StaticFriction)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__StaticFriction", {TrainID, StaticFriction}, 2)
end

--- Note: Autogenerated.
--- Updates field "AirResistance" in Trains. Default = "0.02". Common Values = 0.02, 0.4, 0.04, 0.36, 0.39. 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param AirResistance number|nil Default = "0.02". Common Values = 0.02, 0.4, 0.04, 0.36, 0.39. 
---@return nil
function TrackedRideCars.Trains__Update__AirResistance(TrainID, AirResistance)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__AirResistance", {TrainID, AirResistance}, 2)
end

--- Note: Autogenerated.
--- Updates field "DynamicFriction" in Trains. Default = "0.04". Common Values = 0.03, 0.035, 0.039, 0.04, 0.08. 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param DynamicFriction number|nil Default = "0.04". Common Values = 0.03, 0.035, 0.039, 0.04, 0.08. 
---@return nil
function TrackedRideCars.Trains__Update__DynamicFriction(TrainID, DynamicFriction)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__DynamicFriction", {TrainID, DynamicFriction}, 2)
end

--- Note: Autogenerated.
--- Updates field "DynamicFriction_Alternate" in Trains. Common Values = nil, 0.6, 0.11, 0.05, "". 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param DynamicFriction_Alternate number|nil Common Values = nil, 0.6, 0.11, 0.05, "". 
---@return nil
function TrackedRideCars.Trains__Update__DynamicFriction_Alternate(TrainID, DynamicFriction_Alternate)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__DynamicFriction_Alternate", {TrainID, DynamicFriction_Alternate}, 2)
end

--- Note: Autogenerated.
--- Updates field "LuaScoringModule" in Trains. Default = "DefaultScoring". Common Values = "CoasterScoring", "NonInvertedCoasterScoring", "DefaultScoring", "SwimsuitFlumeScoring", "CascadeScoring". 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param LuaScoringModule string|nil Default = "DefaultScoring". Common Values = "CoasterScoring", "NonInvertedCoasterScoring", "DefaultScoring", "SwimsuitFlumeScoring", "CascadeScoring". 
---@return nil
function TrackedRideCars.Trains__Update__LuaScoringModule(TrainID, LuaScoringModule)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__LuaScoringModule", {TrainID, LuaScoringModule}, 2)
end

--- Note: Autogenerated.
--- Updates field "BaseExcitement" in Trains. Common Values = nil, 4.0, 3.0, 4.5, 6.0. 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param BaseExcitement number|nil Common Values = nil, 4.0, 3.0, 4.5, 6.0. 
---@return nil
function TrackedRideCars.Trains__Update__BaseExcitement(TrainID, BaseExcitement)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__BaseExcitement", {TrainID, BaseExcitement}, 2)
end

--- Note: Autogenerated.
--- Updates field "BaseFear" in Trains. Common Values = nil, 2.0, 1.0, 2.5, "". 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param BaseFear number|nil Common Values = nil, 2.0, 1.0, 2.5, "". 
---@return nil
function TrackedRideCars.Trains__Update__BaseFear(TrainID, BaseFear)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__BaseFear", {TrainID, BaseFear}, 2)
end

--- Note: Autogenerated.
--- Updates field "BaseNausea" in Trains. Common Values = nil, 1.0, "". 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param BaseNausea number|nil Common Values = nil, 1.0, "". 
---@return nil
function TrackedRideCars.Trains__Update__BaseNausea(TrainID, BaseNausea)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__BaseNausea", {TrainID, BaseNausea}, 2)
end

--- Note: Autogenerated.
--- Updates field "CanAddOffStation" in Trains. Common Values = 0, 1. 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param CanAddOffStation boolean Common Values = 0, 1. 
---@return nil
function TrackedRideCars.Trains__Update__CanAddOffStation(TrainID, CanAddOffStation)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__CanAddOffStation", {TrainID, CanAddOffStation}, 2)
end

--- Note: Autogenerated.
--- Updates field "AudioSpeedThreshold" in Trains. Default = "25". Common Values = 25.0. 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param AudioSpeedThreshold number|nil Default = "25". Common Values = 25.0. 
---@return nil
function TrackedRideCars.Trains__Update__AudioSpeedThreshold(TrainID, AudioSpeedThreshold)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__AudioSpeedThreshold", {TrainID, AudioSpeedThreshold}, 2)
end

--- Note: Autogenerated.
--- Updates field "AudioAccnThreshold" in Trains. Default = "30". Common Values = 30.0. 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param AudioAccnThreshold number|nil Default = "30". Common Values = 30.0. 
---@return nil
function TrackedRideCars.Trains__Update__AudioAccnThreshold(TrainID, AudioAccnThreshold)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__AudioAccnThreshold", {TrainID, AudioAccnThreshold}, 2)
end

--- Note: Autogenerated.
--- Updates field "AudioWeightThreshold" in Trains. Default = "100". Common Values = 100.0. 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param AudioWeightThreshold number|nil Default = "100". Common Values = 100.0. 
---@return nil
function TrackedRideCars.Trains__Update__AudioWeightThreshold(TrainID, AudioWeightThreshold)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__AudioWeightThreshold", {TrainID, AudioWeightThreshold}, 2)
end

--- Note: Autogenerated.
--- Updates field "AudioLateralThreshold" in Trains. Default = "50". Common Values = 50.0. 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param AudioLateralThreshold number|nil Default = "50". Common Values = 50.0. 
---@return nil
function TrackedRideCars.Trains__Update__AudioLateralThreshold(TrainID, AudioLateralThreshold)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__AudioLateralThreshold", {TrainID, AudioLateralThreshold}, 2)
end

--- Note: Autogenerated.
--- Updates field "AudioUseFrontAxelForFlanges" in Trains. Default = "0". Common Values = 0.0. 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param AudioUseFrontAxelForFlanges number|nil Default = "0". Common Values = 0.0. 
---@return nil
function TrackedRideCars.Trains__Update__AudioUseFrontAxelForFlanges(TrainID, AudioUseFrontAxelForFlanges)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__AudioUseFrontAxelForFlanges", {TrainID, AudioUseFrontAxelForFlanges}, 2)
end

--- Note: Autogenerated.
--- Updates field "AudioIgnoreFrontCarForFlanges" in Trains. Default = "0". Common Values = 0.0, 1.0. 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param AudioIgnoreFrontCarForFlanges number|nil Default = "0". Common Values = 0.0, 1.0. 
---@return nil
function TrackedRideCars.Trains__Update__AudioIgnoreFrontCarForFlanges(TrainID, AudioIgnoreFrontCarForFlanges)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__AudioIgnoreFrontCarForFlanges", {TrainID, AudioIgnoreFrontCarForFlanges}, 2)
end

--- Note: Autogenerated.
--- Updates field "AudioIgnoreRearCarForFlanges" in Trains. Default = "1". Common Values = 1.0, 0.0. 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param AudioIgnoreRearCarForFlanges number|nil Default = "1". Common Values = 1.0, 0.0. 
---@return nil
function TrackedRideCars.Trains__Update__AudioIgnoreRearCarForFlanges(TrainID, AudioIgnoreRearCarForFlanges)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__AudioIgnoreRearCarForFlanges", {TrainID, AudioIgnoreRearCarForFlanges}, 2)
end

--- Note: Autogenerated.
--- Updates field "AudioIgnoreMidCarsForFlanges" in Trains. Default = "1". Common Values = 1.0, 0.0. 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param AudioIgnoreMidCarsForFlanges number|nil Default = "1". Common Values = 1.0, 0.0. 
---@return nil
function TrackedRideCars.Trains__Update__AudioIgnoreMidCarsForFlanges(TrainID, AudioIgnoreMidCarsForFlanges)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__AudioIgnoreMidCarsForFlanges", {TrainID, AudioIgnoreMidCarsForFlanges}, 2)
end

--- Note: Autogenerated.
--- Updates field "AudioChainLiftPrefix" in Trains. Default = "CL". Common Values = "Mtl", "FWL", "SlideConveyor", "Wood", "Hyb". 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param AudioChainLiftPrefix string|nil Default = "CL". Common Values = "Mtl", "FWL", "SlideConveyor", "Wood", "Hyb". 
---@return nil
function TrackedRideCars.Trains__Update__AudioChainLiftPrefix(TrainID, AudioChainLiftPrefix)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__AudioChainLiftPrefix", {TrainID, AudioChainLiftPrefix}, 2)
end

--- Note: Autogenerated.
--- Updates field "AudioBrakePrefix" in Trains. Default = "Fri". Common Values = "Fri", "Mag", "SlideBrake", "SFri", "WdFr". 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param AudioBrakePrefix string|nil Default = "Fri". Common Values = "Fri", "Mag", "SlideBrake", "SFri", "WdFr". 
---@return nil
function TrackedRideCars.Trains__Update__AudioBrakePrefix(TrainID, AudioBrakePrefix)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__AudioBrakePrefix", {TrainID, AudioBrakePrefix}, 2)
end

--- Note: Autogenerated.
--- Updates field "DefaultRideMusic" in Trains. Default = "NO_MUSIC". Common Values = "NO_MUSIC", "GondolaLift_TRMusic". 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param DefaultRideMusic string|nil Default = "NO_MUSIC". Common Values = "NO_MUSIC", "GondolaLift_TRMusic". 
---@return nil
function TrackedRideCars.Trains__Update__DefaultRideMusic(TrainID, DefaultRideMusic)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__DefaultRideMusic", {TrainID, DefaultRideMusic}, 2)
end

--- Note: Autogenerated.
--- Updates field "UniqueEngineSound" in Trains. Default = "0". Common Values = 0.0, 1.0. 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param UniqueEngineSound number|nil Default = "0". Common Values = 0.0, 1.0. 
---@return nil
function TrackedRideCars.Trains__Update__UniqueEngineSound(TrainID, UniqueEngineSound)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__UniqueEngineSound", {TrainID, UniqueEngineSound}, 2)
end

--- Note: Autogenerated.
--- Updates field "PlayMusicContinuously" in Trains. Default = "0". Common Values = 0, 1. 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param PlayMusicContinuously boolean|nil Default = "0". Common Values = 0, 1. 
---@return nil
function TrackedRideCars.Trains__Update__PlayMusicContinuously(TrainID, PlayMusicContinuously)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__PlayMusicContinuously", {TrainID, PlayMusicContinuously}, 2)
end

--- Note: Autogenerated.
--- Updates field "PlayMusicOnAllCarsSimultaneously" in Trains. Default = "0". Common Values = 0, 1. 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param PlayMusicOnAllCarsSimultaneously boolean|nil Default = "0". Common Values = 0, 1. 
---@return nil
function TrackedRideCars.Trains__Update__PlayMusicOnAllCarsSimultaneously(TrainID, PlayMusicOnAllCarsSimultaneously)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__PlayMusicOnAllCarsSimultaneously", {TrainID, PlayMusicOnAllCarsSimultaneously}, 2)
end

--- Note: Autogenerated.
--- Updates field "AudioGuestsUseExcitement" in Trains. Default = "1". Common Values = 1, 0. 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param AudioGuestsUseExcitement boolean Default = "1". Common Values = 1, 0. 
---@return nil
function TrackedRideCars.Trains__Update__AudioGuestsUseExcitement(TrainID, AudioGuestsUseExcitement)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__AudioGuestsUseExcitement", {TrainID, AudioGuestsUseExcitement}, 2)
end

--- Note: Autogenerated.
--- Updates field "AudioGuestsUseFear" in Trains. Default = "1". Common Values = 1, 0. 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param AudioGuestsUseFear boolean Default = "1". Common Values = 1, 0. 
---@return nil
function TrackedRideCars.Trains__Update__AudioGuestsUseFear(TrainID, AudioGuestsUseFear)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__AudioGuestsUseFear", {TrainID, AudioGuestsUseFear}, 2)
end

--- Note: Autogenerated.
--- Updates field "AudioGuestsUseSpecialBehaviour" in Trains. Default = "1". Common Values = 1, 0. 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param AudioGuestsUseSpecialBehaviour boolean Default = "1". Common Values = 1, 0. 
---@return nil
function TrackedRideCars.Trains__Update__AudioGuestsUseSpecialBehaviour(TrainID, AudioGuestsUseSpecialBehaviour)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__AudioGuestsUseSpecialBehaviour", {TrainID, AudioGuestsUseSpecialBehaviour}, 2)
end

--- Note: Autogenerated.
--- Updates field "UseTransportRideMusic" in Trains. Default = "0". Common Values = 0, 1. 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param UseTransportRideMusic boolean Default = "0". Common Values = 0, 1. 
---@return nil
function TrackedRideCars.Trains__Update__UseTransportRideMusic(TrainID, UseTransportRideMusic)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__UseTransportRideMusic", {TrainID, UseTransportRideMusic}, 2)
end

--- Note: Autogenerated.
--- Updates field "TreatAsCoaster" in Trains. Default = "1". Common Values = 1, 0. 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param TreatAsCoaster boolean Default = "1". Common Values = 1, 0. 
---@return nil
function TrackedRideCars.Trains__Update__TreatAsCoaster(TrainID, TreatAsCoaster)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__TreatAsCoaster", {TrainID, TreatAsCoaster}, 2)
end

--- Note: Autogenerated.
--- Updates field "AudioMaxRange" in Trains. Default = "500". Common Values = 500.0, 300.0, 35.0, 75.0, 200.0. 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param AudioMaxRange number|nil Default = "500". Common Values = 500.0, 300.0, 35.0, 75.0, 200.0. 
---@return nil
function TrackedRideCars.Trains__Update__AudioMaxRange(TrainID, AudioMaxRange)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__AudioMaxRange", {TrainID, AudioMaxRange}, 2)
end

--- Note: Autogenerated.
--- Updates field "CatchTrainType" in Trains. Common Values = nil, "TK_010_CatchCar", "TK_019_CableHookCar", 0, "TK_010_CableHookCar". 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param CatchTrainType string|nil Common Values = nil, "TK_010_CatchCar", "TK_019_CableHookCar", 0, "TK_010_CableHookCar". 
---@return nil
function TrackedRideCars.Trains__Update__CatchTrainType(TrainID, CatchTrainType)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__CatchTrainType", {TrainID, CatchTrainType}, 2)
end

--- Note: Autogenerated.
--- Updates field "NumCatchCars" in Trains. Default = "0". Common Values = 0, 1, 2. 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param NumCatchCars integer Default = "0". Common Values = 0, 1, 2. 
---@return nil
function TrackedRideCars.Trains__Update__NumCatchCars(TrainID, NumCatchCars)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__NumCatchCars", {TrainID, NumCatchCars}, 2)
end

--- Note: Autogenerated.
--- Updates field "ReverseCatchTrainType" in Trains. Common Values = nil, "TK_014_CatchCar_001", 0, "TK_015_CatchCar_Rev". 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param ReverseCatchTrainType string|nil Common Values = nil, "TK_014_CatchCar_001", 0, "TK_015_CatchCar_Rev". 
---@return nil
function TrackedRideCars.Trains__Update__ReverseCatchTrainType(TrainID, ReverseCatchTrainType)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__ReverseCatchTrainType", {TrainID, ReverseCatchTrainType}, 2)
end

--- Note: Autogenerated.
--- Updates field "NumReverseCatchCars" in Trains. Default = "0". Common Values = 0, 1. 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param NumReverseCatchCars integer Default = "0". Common Values = 0, 1. 
---@return nil
function TrackedRideCars.Trains__Update__NumReverseCatchCars(TrainID, NumReverseCatchCars)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__NumReverseCatchCars", {TrainID, NumReverseCatchCars}, 2)
end

--- Note: Autogenerated.
--- Updates field "SplitCatchTrainType" in Trains. Common Values = nil, "TK_014_CatchCar_002", 0. 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param SplitCatchTrainType string|nil Common Values = nil, "TK_014_CatchCar_002", 0. 
---@return nil
function TrackedRideCars.Trains__Update__SplitCatchTrainType(TrainID, SplitCatchTrainType)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__SplitCatchTrainType", {TrainID, SplitCatchTrainType}, 2)
end

--- Note: Autogenerated.
--- Updates field "SplitNormalTrainDelay" in Trains. Default = "0". Common Values = 0.0, 3.0, 1.0. 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param SplitNormalTrainDelay number Default = "0". Common Values = 0.0, 3.0, 1.0. 
---@return nil
function TrackedRideCars.Trains__Update__SplitNormalTrainDelay(TrainID, SplitNormalTrainDelay)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__SplitNormalTrainDelay", {TrainID, SplitNormalTrainDelay}, 2)
end

--- Note: Autogenerated.
--- Updates field "AudioPrefixOverride" in Trains. Common Values = nil, "BigM_WaterCoaster", "HPC_HybridSteel", "HPC_HybridTopped", "Move_MineTrain". 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param AudioPrefixOverride string|nil Common Values = nil, "BigM_WaterCoaster", "HPC_HybridSteel", "HPC_HybridTopped", "Move_MineTrain". 
---@return nil
function TrackedRideCars.Trains__Update__AudioPrefixOverride(TrainID, AudioPrefixOverride)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__AudioPrefixOverride", {TrainID, AudioPrefixOverride}, 2)
end

--- Note: Autogenerated.
--- Updates field "UseMirrorCarRotation" in Trains. Default = "0". Common Values = 0. 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param UseMirrorCarRotation boolean|nil Default = "0". Common Values = 0. 
---@return nil
function TrackedRideCars.Trains__Update__UseMirrorCarRotation(TrainID, UseMirrorCarRotation)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__UseMirrorCarRotation", {TrainID, UseMirrorCarRotation}, 2)
end

--- Note: Autogenerated.
--- Updates field "ForceCarAttachOffsetYToZero" in Trains. Default = "0". Common Values = 0. 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param ForceCarAttachOffsetYToZero boolean|nil Default = "0". Common Values = 0. 
---@return nil
function TrackedRideCars.Trains__Update__ForceCarAttachOffsetYToZero(TrainID, ForceCarAttachOffsetYToZero)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__ForceCarAttachOffsetYToZero", {TrainID, ForceCarAttachOffsetYToZero}, 2)
end

--- Note: Autogenerated.
--- Updates field "ForceCarAttachOffsetYToValue" in Trains. Default = "0". Common Values = 0.0. 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param ForceCarAttachOffsetYToValue number|nil Default = "0". Common Values = 0.0. 
---@return nil
function TrackedRideCars.Trains__Update__ForceCarAttachOffsetYToValue(TrainID, ForceCarAttachOffsetYToValue)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__ForceCarAttachOffsetYToValue", {TrainID, ForceCarAttachOffsetYToValue}, 2)
end

--- Note: Autogenerated.
--- Updates field "AudioCabinIsEnclosed" in Trains. Default = "0". Common Values = 0, 1. 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param AudioCabinIsEnclosed boolean Default = "0". Common Values = 0, 1. 
---@return nil
function TrackedRideCars.Trains__Update__AudioCabinIsEnclosed(TrainID, AudioCabinIsEnclosed)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__AudioCabinIsEnclosed", {TrainID, AudioCabinIsEnclosed}, 2)
end

--- Note: Autogenerated.
--- Updates field "IsWaterSlideTrain" in Trains. Default = "0". Common Values = 0, 1. 
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk".  (Lookup Key)
---@param IsWaterSlideTrain integer Default = "0". Common Values = 0, 1. 
---@return nil
function TrackedRideCars.Trains__Update__IsWaterSlideTrain(TrainID, IsWaterSlideTrain)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "Trains__Update__IsWaterSlideTrain", {TrainID, IsWaterSlideTrain}, 2)
end

--- Note: Autogenerated.
--- Selector for table TransitionList.
---@param TrackedRideName string|nil 
---@return table|nil data
function TrackedRideCars.TransitionList__Select(TrackedRideName)
    local results = DatabaseUtils.ExecuteQuery("TrackedRideCars", "TransitionList__Select", {TrackedRideName}, 1)
    if results == nil then
        return nil
    end
    local result = results[1]
    if result == nil then
        return nil
    end
    return {
        TrackedRideName = result[1] or nil,
    }
end

--- Note: Autogenerated.
--- Inserter for table TransitionList.
---@param TrackedRideName string|nil 
---@return nil
function TrackedRideCars.TransitionList__Insert(TrackedRideName)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "TransitionList__Insert", {TrackedRideName}, 1)
end

--- Note: Autogenerated.
--- Selector for table WhichCar.
---@param ID string Common Values = "Front", "Middle", "Rear". 
---@return table|nil data
function TrackedRideCars.WhichCar__Select(ID)
    local results = DatabaseUtils.ExecuteQuery("TrackedRideCars", "WhichCar__Select", {ID}, 1)
    if results == nil then
        return nil
    end
    local result = results[1]
    if result == nil then
        return nil
    end
    return {
        ID = result[1] or nil,
    }
end

--- Note: Autogenerated.
--- Inserter for table WhichCar.
---@param ID string Common Values = "Front", "Middle", "Rear". 
---@return nil
function TrackedRideCars.WhichCar__Insert(ID)
    return DatabaseUtils.ExecuteQuery("TrackedRideCars", "WhichCar__Insert", {ID}, 1)
end


return TrackedRideCars
