---
--- NOTE: THIS FILE IS AUTOGENERATED.
--- PLEASE NOTE THAT THIS IS SUBJECT TO CHANGE
--- BETWEEN EACH VERSION. IF BROKEN BY AN UPDATE,
--- REGENERATE VIA THE EXT FOLDER.
--- 
local global = _G
local ipairs = global.ipairs
local DatabaseUtils = require("forgeutils.internal.database.databaseutils")

local logger = require("forgeutils.logger").Get("TrackedRideCars")

---@class forgeutils.internal.database.TrackedRideCars
--- Note: Autogenerated!
--- This is a generated lua binding layer for the TrackedRideCars database.
local TrackedRideCars = {}

---@private
--- This method is called after data is merged
TrackedRideCars.InsertToDBs = function()
    TrackedRideCars.BindPreparedStatements()
end

TrackedRideCars.tPreparedStatements = {
    "TrackedRideCars_Cars", 
    "TrackedRideCars_CatchTrains", 
    "TrackedRideCars_RacingTrains", 
    "TrackedRideCars_Trains", 
    "TrackedRideCars_TransitionList", 
    "TrackedRideCars_WhichCar"
}

---@private
function TrackedRideCars.BindPreparedStatements()
    logger:DebugQuery("BindPreparedStatements()")
    for _, filename in ipairs(TrackedRideCars.tPreparedStatements) do
        DatabaseUtils.BindPreparedStatement("TrackedRideCars", filename)
    end
end


--- Note: Autogenerated.
---@param TrainID string Common Values = "Speed", "PTR_PoweredCoaster", "AmericanArrow", "CC_Bolt", "CC_TiltCoaster". 
---@param CarID string Common Values = "BodyFlumeCarF", "BodySlideCarF", "CC_AethonCarF", "CC_AethonCarM", "CC_AethonCarR". 
---@param Mass number Common Values = 140.0, 100.0, 700.0, 800.0, 1200.0. 
function TrackedRideCars.Cars__Insert(TrainID, CarID, Mass)
    DatabaseUtils.ExecuteQuery("Cars", "Cars__Insert", {TrainID, CarID, Mass}, 3)
end

--- Note: Autogenerated.
---@param CarID string Common Values = "BodyFlumeCarF", "BodySlideCarF", "CC_AethonCarF", "CC_AethonCarM", "CC_AethonCarR". (Lookup Key)
---@param TrainID string Common Values = "Speed", "PTR_PoweredCoaster", "AmericanArrow", "CC_Bolt", "CC_TiltCoaster". 
function TrackedRideCars.Cars__Update__TrainID(CarID, TrainID)
    DatabaseUtils.ExecuteQuery("Cars", "Cars__Update__TrainID", {CarID, TrainID}, 2)
end

--- Note: Autogenerated.
---@param CarID string Common Values = "BodyFlumeCarF", "BodySlideCarF", "CC_AethonCarF", "CC_AethonCarM", "CC_AethonCarR". (Lookup Key)
---@param WhichCar string|nil Common Values = "Front", "Middle", "Rear". 
function TrackedRideCars.Cars__Update__WhichCar(CarID, WhichCar)
    DatabaseUtils.ExecuteQuery("Cars", "Cars__Update__WhichCar", {CarID, WhichCar}, 2)
end

--- Note: Autogenerated.
---@param CarID string Common Values = "BodyFlumeCarF", "BodySlideCarF", "CC_AethonCarF", "CC_AethonCarM", "CC_AethonCarR". (Lookup Key)
---@param CarOrder integer|nil Default = 0. Common Values = 0, 1, 2, 3, 4. 
function TrackedRideCars.Cars__Update__CarOrder(CarID, CarOrder)
    DatabaseUtils.ExecuteQuery("Cars", "Cars__Update__CarOrder", {CarID, CarOrder}, 2)
end

--- Note: Autogenerated.
---@param CarID string Common Values = "BodyFlumeCarF", "BodySlideCarF", "CC_AethonCarF", "CC_AethonCarM", "CC_AethonCarR". (Lookup Key)
---@param Prefab string|nil Common Values = "CC_BakasuraCarF_Art", "TR_GondolaCarF_Game", "BodyFlumeCarF_Art", "BodySlideCarF_Art", "CC_AethonCarF_Art". 
function TrackedRideCars.Cars__Update__Prefab(CarID, Prefab)
    DatabaseUtils.ExecuteQuery("Cars", "Cars__Update__Prefab", {CarID, Prefab}, 2)
end

--- Note: Autogenerated.
---@param CarID string Common Values = "BodyFlumeCarF", "BodySlideCarF", "CC_AethonCarF", "CC_AethonCarM", "CC_AethonCarR". (Lookup Key)
---@param Mass number Common Values = 140.0, 100.0, 700.0, 800.0, 1200.0. 
function TrackedRideCars.Cars__Update__Mass(CarID, Mass)
    DatabaseUtils.ExecuteQuery("Cars", "Cars__Update__Mass", {CarID, Mass}, 2)
end

--- Note: Autogenerated.
---@param CarID string Common Values = "BodyFlumeCarF", "BodySlideCarF", "CC_AethonCarF", "CC_AethonCarM", "CC_AethonCarR". (Lookup Key)
---@param PlatformPrefab string|nil Common Values = nil, "StationPlatform_CC_Stingray_Front", "StationPlatform_CC_Stingray_Mid", "StationPlatform_CC_Stingray_Rear", "StationPlatform_CC_Aethon_Front". 
function TrackedRideCars.Cars__Update__PlatformPrefab(CarID, PlatformPrefab)
    DatabaseUtils.ExecuteQuery("Cars", "Cars__Update__PlatformPrefab", {CarID, PlatformPrefab}, 2)
end

--- Note: Autogenerated.
---@param CarID string Common Values = "BodyFlumeCarF", "BodySlideCarF", "CC_AethonCarF", "CC_AethonCarM", "CC_AethonCarR". (Lookup Key)
---@param IsPowered boolean|nil Default = 0. Common Values = 0, 1. 
function TrackedRideCars.Cars__Update__IsPowered(CarID, IsPowered)
    DatabaseUtils.ExecuteQuery("Cars", "Cars__Update__IsPowered", {CarID, IsPowered}, 2)
end

--- Note: Autogenerated.
---@param TrainID string Common Values = "TK_010_CableHookCar", "TK_010_CatchCar", "TK_014_CatchCar_001", "TK_014_CatchCar_002", "TK_015_CatchCar". 
function TrackedRideCars.CatchTrains__Insert(TrainID)
    DatabaseUtils.ExecuteQuery("CatchTrains", "CatchTrains__Insert", {TrainID}, 1)
end

--- Note: Autogenerated.
---@param TrainID string Common Values = "TK_010_CableHookCar", "TK_010_CatchCar", "TK_014_CatchCar_001", "TK_014_CatchCar_002", "TK_015_CatchCar". (Lookup Key)
---@param ShouldWait boolean Default = 0. Common Values = 0, 1. 
function TrackedRideCars.CatchTrains__Update__ShouldWait(TrainID, ShouldWait)
    DatabaseUtils.ExecuteQuery("CatchTrains", "CatchTrains__Update__ShouldWait", {TrainID, ShouldWait}, 2)
end

--- Note: Autogenerated.
---@param TrainID string Common Values = "TK_010_CableHookCar", "TK_010_CatchCar", "TK_014_CatchCar_001", "TK_014_CatchCar_002", "TK_015_CatchCar". (Lookup Key)
---@param CatchOnReturn boolean Default = 0. Common Values = 0, 1. 
function TrackedRideCars.CatchTrains__Update__CatchOnReturn(TrainID, CatchOnReturn)
    DatabaseUtils.ExecuteQuery("CatchTrains", "CatchTrains__Update__CatchOnReturn", {TrainID, CatchOnReturn}, 2)
end

--- Note: Autogenerated.
---@param TrainID string Common Values = "TK_010_CableHookCar", "TK_010_CatchCar", "TK_014_CatchCar_001", "TK_014_CatchCar_002", "TK_015_CatchCar". (Lookup Key)
---@param MatchSpeed boolean Default = 0. Common Values = 0, 1. 
function TrackedRideCars.CatchTrains__Update__MatchSpeed(TrainID, MatchSpeed)
    DatabaseUtils.ExecuteQuery("CatchTrains", "CatchTrains__Update__MatchSpeed", {TrainID, MatchSpeed}, 2)
end

--- Note: Autogenerated.
---@param TrainID string Common Values = "TK_010_CableHookCar", "TK_010_CatchCar", "TK_014_CatchCar_001", "TK_014_CatchCar_002", "TK_015_CatchCar". (Lookup Key)
---@param CatchOnFinalLap boolean Default = 0. Common Values = 0, 1. 
function TrackedRideCars.CatchTrains__Update__CatchOnFinalLap(TrainID, CatchOnFinalLap)
    DatabaseUtils.ExecuteQuery("CatchTrains", "CatchTrains__Update__CatchOnFinalLap", {TrainID, CatchOnFinalLap}, 2)
end

--- Note: Autogenerated.
---@param TrainID string Common Values = "Speed". 
function TrackedRideCars.RacingTrains__Insert(TrainID)
    DatabaseUtils.ExecuteQuery("RacingTrains", "RacingTrains__Insert", {TrainID}, 1)
end

--- Note: Autogenerated.
---@param TrainID string Common Values = "Speed". (Lookup Key)
---@param PitOffset number|nil Common Values = 5.067. 
function TrackedRideCars.RacingTrains__Update__PitOffset(TrainID, PitOffset)
    DatabaseUtils.ExecuteQuery("RacingTrains", "RacingTrains__Update__PitOffset", {TrainID, PitOffset}, 2)
end

--- Note: Autogenerated.
---@param TrainID string Common Values = "Speed". (Lookup Key)
---@param PitFront number|nil Common Values = 7.0. 
function TrackedRideCars.RacingTrains__Update__PitFront(TrainID, PitFront)
    DatabaseUtils.ExecuteQuery("RacingTrains", "RacingTrains__Update__PitFront", {TrainID, PitFront}, 2)
end

--- Note: Autogenerated.
---@param TrainID string Common Values = "Speed". (Lookup Key)
---@param PitStep number|nil Common Values = 4.5. 
function TrackedRideCars.RacingTrains__Update__PitStep(TrainID, PitStep)
    DatabaseUtils.ExecuteQuery("RacingTrains", "RacingTrains__Update__PitStep", {TrainID, PitStep}, 2)
end

--- Note: Autogenerated.
---@param TrainID string Common Values = "Speed". (Lookup Key)
---@param StartingOffset number|nil Common Values = 1.8. 
function TrackedRideCars.RacingTrains__Update__StartingOffset(TrainID, StartingOffset)
    DatabaseUtils.ExecuteQuery("RacingTrains", "RacingTrains__Update__StartingOffset", {TrainID, StartingOffset}, 2)
end

--- Note: Autogenerated.
---@param TrainID string Common Values = "Speed". (Lookup Key)
---@param StartingFront number|nil Common Values = 3.5. 
function TrackedRideCars.RacingTrains__Update__StartingFront(TrainID, StartingFront)
    DatabaseUtils.ExecuteQuery("RacingTrains", "RacingTrains__Update__StartingFront", {TrainID, StartingFront}, 2)
end

--- Note: Autogenerated.
---@param TrainID string Common Values = "Speed". (Lookup Key)
---@param StartingStep number|nil Common Values = 4.4. 
function TrackedRideCars.RacingTrains__Update__StartingStep(TrainID, StartingStep)
    DatabaseUtils.ExecuteQuery("RacingTrains", "RacingTrains__Update__StartingStep", {TrainID, StartingStep}, 2)
end

--- Note: Autogenerated.
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". 
---@param CanAddOffStation boolean Common Values = 0, 1. 
function TrackedRideCars.Trains__Insert(TrainID, CanAddOffStation)
    DatabaseUtils.ExecuteQuery("Trains", "Trains__Insert", {TrainID, CanAddOffStation}, 2)
end

--- Note: Autogenerated.
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". (Lookup Key)
---@param StaticFriction number|nil Default = 0.06. Common Values = 0.06, 0.0. 
function TrackedRideCars.Trains__Update__StaticFriction(TrainID, StaticFriction)
    DatabaseUtils.ExecuteQuery("Trains", "Trains__Update__StaticFriction", {TrainID, StaticFriction}, 2)
end

--- Note: Autogenerated.
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". (Lookup Key)
---@param AirResistance number|nil Default = 0.02. Common Values = 0.02, 0.4, 0.04, 0.36, 0.39. 
function TrackedRideCars.Trains__Update__AirResistance(TrainID, AirResistance)
    DatabaseUtils.ExecuteQuery("Trains", "Trains__Update__AirResistance", {TrainID, AirResistance}, 2)
end

--- Note: Autogenerated.
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". (Lookup Key)
---@param DynamicFriction number|nil Default = 0.04. Common Values = 0.03, 0.035, 0.04, 0.08, 0.039. 
function TrackedRideCars.Trains__Update__DynamicFriction(TrainID, DynamicFriction)
    DatabaseUtils.ExecuteQuery("Trains", "Trains__Update__DynamicFriction", {TrainID, DynamicFriction}, 2)
end

--- Note: Autogenerated.
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". (Lookup Key)
---@param DynamicFriction_Alternate number|nil Common Values = nil, 0.6, 0.11, 0.05, "". 
function TrackedRideCars.Trains__Update__DynamicFriction_Alternate(TrainID, DynamicFriction_Alternate)
    DatabaseUtils.ExecuteQuery("Trains", "Trains__Update__DynamicFriction_Alternate", {TrainID, DynamicFriction_Alternate}, 2)
end

--- Note: Autogenerated.
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". (Lookup Key)
---@param LuaScoringModule string|nil Default = DefaultScoring. Common Values = "CoasterScoring", "NonInvertedCoasterScoring", "DefaultScoring", "SwimsuitFlumeScoring", "PoweredTrackedRideScoring". 
function TrackedRideCars.Trains__Update__LuaScoringModule(TrainID, LuaScoringModule)
    DatabaseUtils.ExecuteQuery("Trains", "Trains__Update__LuaScoringModule", {TrainID, LuaScoringModule}, 2)
end

--- Note: Autogenerated.
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". (Lookup Key)
---@param BaseExcitement number|nil Common Values = nil, 4.0, 3.0, 6.0, "". 
function TrackedRideCars.Trains__Update__BaseExcitement(TrainID, BaseExcitement)
    DatabaseUtils.ExecuteQuery("Trains", "Trains__Update__BaseExcitement", {TrainID, BaseExcitement}, 2)
end

--- Note: Autogenerated.
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". (Lookup Key)
---@param BaseFear number|nil Common Values = nil, 2.0, 1.0, "". 
function TrackedRideCars.Trains__Update__BaseFear(TrainID, BaseFear)
    DatabaseUtils.ExecuteQuery("Trains", "Trains__Update__BaseFear", {TrainID, BaseFear}, 2)
end

--- Note: Autogenerated.
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". (Lookup Key)
---@param BaseNausea number|nil Common Values = nil, 1.0, "". 
function TrackedRideCars.Trains__Update__BaseNausea(TrainID, BaseNausea)
    DatabaseUtils.ExecuteQuery("Trains", "Trains__Update__BaseNausea", {TrainID, BaseNausea}, 2)
end

--- Note: Autogenerated.
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". (Lookup Key)
---@param CanAddOffStation boolean Common Values = 0, 1. 
function TrackedRideCars.Trains__Update__CanAddOffStation(TrainID, CanAddOffStation)
    DatabaseUtils.ExecuteQuery("Trains", "Trains__Update__CanAddOffStation", {TrainID, CanAddOffStation}, 2)
end

--- Note: Autogenerated.
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". (Lookup Key)
---@param AudioSpeedThreshold number|nil Default = 25. Common Values = 25.0. 
function TrackedRideCars.Trains__Update__AudioSpeedThreshold(TrainID, AudioSpeedThreshold)
    DatabaseUtils.ExecuteQuery("Trains", "Trains__Update__AudioSpeedThreshold", {TrainID, AudioSpeedThreshold}, 2)
end

--- Note: Autogenerated.
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". (Lookup Key)
---@param AudioAccnThreshold number|nil Default = 30. Common Values = 30.0. 
function TrackedRideCars.Trains__Update__AudioAccnThreshold(TrainID, AudioAccnThreshold)
    DatabaseUtils.ExecuteQuery("Trains", "Trains__Update__AudioAccnThreshold", {TrainID, AudioAccnThreshold}, 2)
end

--- Note: Autogenerated.
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". (Lookup Key)
---@param AudioWeightThreshold number|nil Default = 100. Common Values = 100.0. 
function TrackedRideCars.Trains__Update__AudioWeightThreshold(TrainID, AudioWeightThreshold)
    DatabaseUtils.ExecuteQuery("Trains", "Trains__Update__AudioWeightThreshold", {TrainID, AudioWeightThreshold}, 2)
end

--- Note: Autogenerated.
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". (Lookup Key)
---@param AudioLateralThreshold number|nil Default = 50. Common Values = 50.0. 
function TrackedRideCars.Trains__Update__AudioLateralThreshold(TrainID, AudioLateralThreshold)
    DatabaseUtils.ExecuteQuery("Trains", "Trains__Update__AudioLateralThreshold", {TrainID, AudioLateralThreshold}, 2)
end

--- Note: Autogenerated.
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". (Lookup Key)
---@param AudioUseFrontAxelForFlanges number|nil Default = 0. Common Values = 0.0. 
function TrackedRideCars.Trains__Update__AudioUseFrontAxelForFlanges(TrainID, AudioUseFrontAxelForFlanges)
    DatabaseUtils.ExecuteQuery("Trains", "Trains__Update__AudioUseFrontAxelForFlanges", {TrainID, AudioUseFrontAxelForFlanges}, 2)
end

--- Note: Autogenerated.
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". (Lookup Key)
---@param AudioIgnoreFrontCarForFlanges number|nil Default = 0. Common Values = 0.0, 1.0. 
function TrackedRideCars.Trains__Update__AudioIgnoreFrontCarForFlanges(TrainID, AudioIgnoreFrontCarForFlanges)
    DatabaseUtils.ExecuteQuery("Trains", "Trains__Update__AudioIgnoreFrontCarForFlanges", {TrainID, AudioIgnoreFrontCarForFlanges}, 2)
end

--- Note: Autogenerated.
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". (Lookup Key)
---@param AudioIgnoreRearCarForFlanges number|nil Default = 1. Common Values = 1.0, 0.0. 
function TrackedRideCars.Trains__Update__AudioIgnoreRearCarForFlanges(TrainID, AudioIgnoreRearCarForFlanges)
    DatabaseUtils.ExecuteQuery("Trains", "Trains__Update__AudioIgnoreRearCarForFlanges", {TrainID, AudioIgnoreRearCarForFlanges}, 2)
end

--- Note: Autogenerated.
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". (Lookup Key)
---@param AudioIgnoreMidCarsForFlanges number|nil Default = 1. Common Values = 1.0, 0.0. 
function TrackedRideCars.Trains__Update__AudioIgnoreMidCarsForFlanges(TrainID, AudioIgnoreMidCarsForFlanges)
    DatabaseUtils.ExecuteQuery("Trains", "Trains__Update__AudioIgnoreMidCarsForFlanges", {TrainID, AudioIgnoreMidCarsForFlanges}, 2)
end

--- Note: Autogenerated.
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". (Lookup Key)
---@param AudioChainLiftPrefix string|nil Default = CL. Common Values = "Mtl", "SlideConveyor", "FWL", "Wood", "Water". 
function TrackedRideCars.Trains__Update__AudioChainLiftPrefix(TrainID, AudioChainLiftPrefix)
    DatabaseUtils.ExecuteQuery("Trains", "Trains__Update__AudioChainLiftPrefix", {TrainID, AudioChainLiftPrefix}, 2)
end

--- Note: Autogenerated.
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". (Lookup Key)
---@param AudioBrakePrefix string|nil Default = Fri. Common Values = "Fri", "Mag", "SlideBrake", "SFri", "WdFr". 
function TrackedRideCars.Trains__Update__AudioBrakePrefix(TrainID, AudioBrakePrefix)
    DatabaseUtils.ExecuteQuery("Trains", "Trains__Update__AudioBrakePrefix", {TrainID, AudioBrakePrefix}, 2)
end

--- Note: Autogenerated.
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". (Lookup Key)
---@param DefaultRideMusic string|nil Default = NO_MUSIC. Common Values = "NO_MUSIC", "GondolaLift_TRMusic". 
function TrackedRideCars.Trains__Update__DefaultRideMusic(TrainID, DefaultRideMusic)
    DatabaseUtils.ExecuteQuery("Trains", "Trains__Update__DefaultRideMusic", {TrainID, DefaultRideMusic}, 2)
end

--- Note: Autogenerated.
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". (Lookup Key)
---@param UniqueEngineSound number|nil Default = 0. Common Values = 0.0, 1.0. 
function TrackedRideCars.Trains__Update__UniqueEngineSound(TrainID, UniqueEngineSound)
    DatabaseUtils.ExecuteQuery("Trains", "Trains__Update__UniqueEngineSound", {TrainID, UniqueEngineSound}, 2)
end

--- Note: Autogenerated.
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". (Lookup Key)
---@param PlayMusicContinuously boolean|nil Default = 0. Common Values = 0, 1. 
function TrackedRideCars.Trains__Update__PlayMusicContinuously(TrainID, PlayMusicContinuously)
    DatabaseUtils.ExecuteQuery("Trains", "Trains__Update__PlayMusicContinuously", {TrainID, PlayMusicContinuously}, 2)
end

--- Note: Autogenerated.
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". (Lookup Key)
---@param PlayMusicOnAllCarsSimultaneously boolean|nil Default = 0. Common Values = 0, 1. 
function TrackedRideCars.Trains__Update__PlayMusicOnAllCarsSimultaneously(TrainID, PlayMusicOnAllCarsSimultaneously)
    DatabaseUtils.ExecuteQuery("Trains", "Trains__Update__PlayMusicOnAllCarsSimultaneously", {TrainID, PlayMusicOnAllCarsSimultaneously}, 2)
end

--- Note: Autogenerated.
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". (Lookup Key)
---@param AudioGuestsUseExcitement boolean Default = 1. Common Values = 1, 0. 
function TrackedRideCars.Trains__Update__AudioGuestsUseExcitement(TrainID, AudioGuestsUseExcitement)
    DatabaseUtils.ExecuteQuery("Trains", "Trains__Update__AudioGuestsUseExcitement", {TrainID, AudioGuestsUseExcitement}, 2)
end

--- Note: Autogenerated.
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". (Lookup Key)
---@param AudioGuestsUseFear boolean Default = 1. Common Values = 1, 0. 
function TrackedRideCars.Trains__Update__AudioGuestsUseFear(TrainID, AudioGuestsUseFear)
    DatabaseUtils.ExecuteQuery("Trains", "Trains__Update__AudioGuestsUseFear", {TrainID, AudioGuestsUseFear}, 2)
end

--- Note: Autogenerated.
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". (Lookup Key)
---@param AudioGuestsUseSpecialBehaviour boolean Default = 1. Common Values = 1, 0. 
function TrackedRideCars.Trains__Update__AudioGuestsUseSpecialBehaviour(TrainID, AudioGuestsUseSpecialBehaviour)
    DatabaseUtils.ExecuteQuery("Trains", "Trains__Update__AudioGuestsUseSpecialBehaviour", {TrainID, AudioGuestsUseSpecialBehaviour}, 2)
end

--- Note: Autogenerated.
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". (Lookup Key)
---@param UseTransportRideMusic boolean Default = 0. Common Values = 0, 1. 
function TrackedRideCars.Trains__Update__UseTransportRideMusic(TrainID, UseTransportRideMusic)
    DatabaseUtils.ExecuteQuery("Trains", "Trains__Update__UseTransportRideMusic", {TrainID, UseTransportRideMusic}, 2)
end

--- Note: Autogenerated.
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". (Lookup Key)
---@param TreatAsCoaster boolean Default = 1. Common Values = 1, 0. 
function TrackedRideCars.Trains__Update__TreatAsCoaster(TrainID, TreatAsCoaster)
    DatabaseUtils.ExecuteQuery("Trains", "Trains__Update__TreatAsCoaster", {TrainID, TreatAsCoaster}, 2)
end

--- Note: Autogenerated.
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". (Lookup Key)
---@param AudioMaxRange number|nil Default = 500. Common Values = 500.0, 300.0, 35.0, 75.0, 200.0. 
function TrackedRideCars.Trains__Update__AudioMaxRange(TrainID, AudioMaxRange)
    DatabaseUtils.ExecuteQuery("Trains", "Trains__Update__AudioMaxRange", {TrainID, AudioMaxRange}, 2)
end

--- Note: Autogenerated.
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". (Lookup Key)
---@param CatchTrainType string|nil Common Values = nil, "TK_010_CatchCar", "TK_019_CableHookCar", 0, "TK_010_CableHookCar". 
function TrackedRideCars.Trains__Update__CatchTrainType(TrainID, CatchTrainType)
    DatabaseUtils.ExecuteQuery("Trains", "Trains__Update__CatchTrainType", {TrainID, CatchTrainType}, 2)
end

--- Note: Autogenerated.
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". (Lookup Key)
---@param NumCatchCars integer Default = 0. Common Values = 0, 1, 2. 
function TrackedRideCars.Trains__Update__NumCatchCars(TrainID, NumCatchCars)
    DatabaseUtils.ExecuteQuery("Trains", "Trains__Update__NumCatchCars", {TrainID, NumCatchCars}, 2)
end

--- Note: Autogenerated.
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". (Lookup Key)
---@param ReverseCatchTrainType string|nil Common Values = nil, 0, "TK_014_CatchCar_001", "TK_015_CatchCar_Rev". 
function TrackedRideCars.Trains__Update__ReverseCatchTrainType(TrainID, ReverseCatchTrainType)
    DatabaseUtils.ExecuteQuery("Trains", "Trains__Update__ReverseCatchTrainType", {TrainID, ReverseCatchTrainType}, 2)
end

--- Note: Autogenerated.
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". (Lookup Key)
---@param NumReverseCatchCars integer Default = 0. Common Values = 0, 1. 
function TrackedRideCars.Trains__Update__NumReverseCatchCars(TrainID, NumReverseCatchCars)
    DatabaseUtils.ExecuteQuery("Trains", "Trains__Update__NumReverseCatchCars", {TrainID, NumReverseCatchCars}, 2)
end

--- Note: Autogenerated.
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". (Lookup Key)
---@param SplitCatchTrainType string|nil Common Values = nil, 0, "TK_014_CatchCar_002". 
function TrackedRideCars.Trains__Update__SplitCatchTrainType(TrainID, SplitCatchTrainType)
    DatabaseUtils.ExecuteQuery("Trains", "Trains__Update__SplitCatchTrainType", {TrainID, SplitCatchTrainType}, 2)
end

--- Note: Autogenerated.
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". (Lookup Key)
---@param SplitNormalTrainDelay number Default = 0. Common Values = 0.0, 3.0, 1.0. 
function TrackedRideCars.Trains__Update__SplitNormalTrainDelay(TrainID, SplitNormalTrainDelay)
    DatabaseUtils.ExecuteQuery("Trains", "Trains__Update__SplitNormalTrainDelay", {TrainID, SplitNormalTrainDelay}, 2)
end

--- Note: Autogenerated.
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". (Lookup Key)
---@param AudioPrefixOverride string|nil Common Values = nil, "Outa_HydLaunch", "PR_SpinningMouse", "VN_Flying", "VN_Wing_Chain". 
function TrackedRideCars.Trains__Update__AudioPrefixOverride(TrainID, AudioPrefixOverride)
    DatabaseUtils.ExecuteQuery("Trains", "Trains__Update__AudioPrefixOverride", {TrainID, AudioPrefixOverride}, 2)
end

--- Note: Autogenerated.
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". (Lookup Key)
---@param UseMirrorCarRotation boolean|nil Default = 0. Common Values = 0. 
function TrackedRideCars.Trains__Update__UseMirrorCarRotation(TrainID, UseMirrorCarRotation)
    DatabaseUtils.ExecuteQuery("Trains", "Trains__Update__UseMirrorCarRotation", {TrainID, UseMirrorCarRotation}, 2)
end

--- Note: Autogenerated.
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". (Lookup Key)
---@param ForceCarAttachOffsetYToZero boolean|nil Default = 0. Common Values = 0. 
function TrackedRideCars.Trains__Update__ForceCarAttachOffsetYToZero(TrainID, ForceCarAttachOffsetYToZero)
    DatabaseUtils.ExecuteQuery("Trains", "Trains__Update__ForceCarAttachOffsetYToZero", {TrainID, ForceCarAttachOffsetYToZero}, 2)
end

--- Note: Autogenerated.
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". (Lookup Key)
---@param ForceCarAttachOffsetYToValue number|nil Default = 0. Common Values = 0.0. 
function TrackedRideCars.Trains__Update__ForceCarAttachOffsetYToValue(TrainID, ForceCarAttachOffsetYToValue)
    DatabaseUtils.ExecuteQuery("Trains", "Trains__Update__ForceCarAttachOffsetYToValue", {TrainID, ForceCarAttachOffsetYToValue}, 2)
end

--- Note: Autogenerated.
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". (Lookup Key)
---@param AudioCabinIsEnclosed boolean Default = 0. Common Values = 0, 1. 
function TrackedRideCars.Trains__Update__AudioCabinIsEnclosed(TrainID, AudioCabinIsEnclosed)
    DatabaseUtils.ExecuteQuery("Trains", "Trains__Update__AudioCabinIsEnclosed", {TrainID, AudioCabinIsEnclosed}, 2)
end

--- Note: Autogenerated.
---@param TrainID string Common Values = "Aethon", "AmericanArrow", "Bakasura", "Barghest", "Basilisk". (Lookup Key)
---@param IsWaterSlideTrain integer Default = 0. Common Values = 0, 1. 
function TrackedRideCars.Trains__Update__IsWaterSlideTrain(TrainID, IsWaterSlideTrain)
    DatabaseUtils.ExecuteQuery("Trains", "Trains__Update__IsWaterSlideTrain", {TrainID, IsWaterSlideTrain}, 2)
end

--- Note: Autogenerated.
---@param TrackedRideName string|nil 
function TrackedRideCars.TransitionList__Insert(TrackedRideName)
    DatabaseUtils.ExecuteQuery("TransitionList", "TransitionList__Insert", {TrackedRideName}, 1)
end

--- Note: Autogenerated.
---@param ID string Common Values = "Front", "Middle", "Rear". 
function TrackedRideCars.WhichCar__Insert(ID)
    DatabaseUtils.ExecuteQuery("WhichCar", "WhichCar__Insert", {ID}, 1)
end


return TrackedRideCars
