import re

db_constants_file = """---
--- NOTE: THIS FILE IS AUTOGENERATED.
--- PLEASE NOTE THAT THIS IS SUBJECT TO CHANGE
--- BETWEEN EACH VERSION. IF BROKEN BY AN UPDATE,
--- REGENERATE VIA THE SCRIPT IN SQLBINDINGFOLDER.
--- 

---@class {1}.{0}
--- Note: Autogenerated!
--- This is a class containing generated
--- lua constants from the {2} database.
local {0} = {{}}

{3}

return {0}
"""

db_constant_collection_file = """---
--- Constants for: {0}
---

{1}"""

db_constant_entry_file = "{0}.{1}_{2} = {3}"

def convert_constant_to_lua_value(constant : any) -> str:
    match constant:

        # lua string literal
        case str():
            return f"\"{re.sub(r'\W+', '', constant)}\""
        
        # easy conversion
        case int() | float():
            return str(constant)
        
        # lowercase
        case bool():
            return "true" if constant else "false"
        
        case _:
            raise NotImplementedError(f"Type of constant {type(constant)} is not supported when converting to lua. Add support!")

def generate_lua_source_file(
    class_name : str,
    lua_namespace : str, 
    database_name : str,
    constants : dict[str, list[any]]
) -> str:
    
    constant_entries = {
        constantName: "\n".join([
            db_constant_entry_file.format(
                class_name,
                constantName,
                re.sub(r'\W+', '', constant), # remove ws
                convert_constant_to_lua_value(constant),
            )
            for constant in constants
        ])
        for constantName, constants in constants.items()
    }

    constants = [
        db_constant_collection_file.format(
            constantName,
            constantsStr
        )
        for constantName, constantsStr in constant_entries.items()
    ]

    return db_constants_file.format(
        class_name,
        lua_namespace,
        database_name,
        "\n\n".join(
            constants
        )
    )
