from .luagen import map_sqltype_to_lua
from .tabletypes import TableData, TableParam

doc_file_template = """
# {0}
> [!CAUTION]
> Please note that the documentation in this section is autogenerated. It is up to date with the bindings, and new updates may break these methods at any time.

> [!WARNING]
> The schemas in this page are not 100% accurate. If you are writing custom precompiled statements, you should extract the database for yourself to read the SQL DDL.

This page documents the schema for the tables within the `{0}` database.

## Table Schemas
{1}"""

table_schema_template = """
### {0}
| Name | Lua Type | Primary | Foreign | Unique | Default Value |
| ---- | -------- | :-----: | :-----: | :----: | ------------- |
{1}"""

schema_param_template = "| {0} | {1} | {2} | {3} | {4} | {5} |"

def generate_doc_source_file(
    database_name : str,
    data : dict[str, TableData]
) -> str:
    
    return doc_file_template.format(
        database_name,
        get_tables_content(data)
    )

def get_tables_content(
    data : dict[str, TableData]
) -> str:
    return "\n".join([
        get_table_schemas_content(
            name, 
            data
        )
        for name, data in data.items()
    ])

def get_table_schemas_content(
    name : str,
    data : TableData
) -> str:
    return table_schema_template.format(
        name,
        "\n".join([
            get_param_entry(
                name, 
                param
            )
            for name, param in data.parameters.items()
        ])
    )

def get_param_entry(
    name : str,
    param : TableParam
) -> str:
    return schema_param_template.format(
        name,
        get_lua_type(param),
        get_doc_display_for_tick(param.primary_key),
        get_doc_display_for_tick(param.foreign_key),
        get_doc_display_for_tick(param.unique),
        f"`{param.default}`" if param.default is not None else ""
    )

def get_lua_type(
    param : TableParam
) -> str:
    luatype = map_sqltype_to_lua(param.sql_type)

    if not param.not_null:
        luatype += "\|nil"
    return f"`{luatype}`"

def get_doc_display_for_tick(bool : bool) -> str:
    return "✅" if bool else ""