from .shared_gen import get_insert_name, get_update_name, get_select_name
from .tabletypes import TableData, TableParam

sql_luafunc_template = """
--- Note: Autogenerated.
{0}
function {1}.{2}({3})
    return DatabaseUtils.ExecuteQuery("{4}", "{5}", {{{3}}}, {6})
end
"""

sql_select_luafunc_template = """
--- Note: Autogenerated.
{0}
function {1}.{2}({3})
    local results = DatabaseUtils.ExecuteQuery("{4}", "{5}", {{{3}}}, {6})
    if results == nil then
        return nil
    end
    local result = results[1]
    if result == nil then
        return nil
    end
    return {{
{7}
    }}
end
"""

sql_luafunc_indent2 = "        "

sql_luafunccomment_template = "---@param {0} {1} {2}"

db_manager_file = """---
--- NOTE: THIS FILE IS AUTOGENERATED.
--- PLEASE NOTE THAT THIS IS SUBJECT TO CHANGE
--- BETWEEN EACH VERSION. IF BROKEN BY AN UPDATE,
--- REGENERATE VIA THE SCRIPT IN SQLBINDINGFOLDER.
--- 
local global = _G
local ipairs = global.ipairs
local DatabaseUtils = require("forgeutils.internal.database.databaseutils")

local logger = require("forgeutils.logger").Get("{0}")

---@class {1}.{0}
--- Note: Autogenerated!
--- This is a generated lua binding layer for the {3} database.
local {0} = {{}}

---@private
--- This method is called after data is merged
{0}.InsertToDBs = function()
    {0}.BindPreparedStatements()
end

{0}.tPreparedStatements = {{
{2}
}}

---@private
function {0}.BindPreparedStatements()
    logger:DebugQuery("BindPreparedStatements()")
    for _, filename in ipairs({0}.tPreparedStatements) do
        DatabaseUtils.BindPreparedStatement(\"{3}\", filename)
    end
end

{4}

return {0}
"""

def generate_lua_source_file(
    manager_name : str,
    manager_luapath : str, 
    database_name : str, 
    pscollection_names : list[str],
    extra_lua_functions : str = ""
) -> str:
    return db_manager_file.format(
        manager_name,
        manager_luapath,
        ", \n".join([
            f"    \"{pscoll}\""
            for pscoll in pscollection_names
        ]),
        database_name,
        extra_lua_functions
    )

def get_luadoc_desc(param_data : TableParam) -> str:
    res = ""
    if (param_data.default != None):
        res += f"Default = {get_pretty_print_for_value(param_data.default)}. "

    if (len(param_data.most_common_values) > 0):
        res += f"Common Values = {", ".join(param_data.most_common_values)}. "
    return res

def get_luadoc_comment(param_name : str, param_data : TableParam) -> str:
    return sql_luafunccomment_template.format(
        param_name,
        f"{map_sqltype_to_lua(param_data.sql_type)}{"|nil" if not param_data.not_null else ""}",
        get_luadoc_desc(param_data)
    )

def get_pretty_print_for_value(val : any) -> str:
    if isinstance(val, str):
        return f"\"{val}\""
    if val == None:
        return "nil"
    return str(val)

def map_sqltype_to_lua(sql_type: str) -> str:
    sql_type = sql_type.lower()
    if sql_type in ("integer", "int"):
        return "integer"
    if sql_type in ("real", "double"):
        return "number"
    if sql_type in ("text"):
        return "string"
    return sql_type

def get_select_method(manager_name : str, database : str, table : str, table_data : TableData) -> str:
    primary_keys = table_data.get_primary_keys()

    luadoc_comments = "\n".join(
        [
            f"--- Selector for table {table}."
        ] 
        + 
        [
            get_luadoc_comment(param_name, param_data)
            for param_name, param_data in primary_keys.items()
        ]
        +
        [
            f"---@return table|nil data"
        ] 
    )
    param_count = len(primary_keys.keys())
    param_names = ", ".join(primary_keys.keys())
    pscol_name = get_select_name(table)

    param_list = list(table_data.parameters.keys())
    
    lua_table_map = "\n".join(
        [
            f"{sql_luafunc_indent2}{param_name} = result[{i + 1}] or nil,"
            for i, param_name in enumerate(param_list)
        ]
    )

    return sql_select_luafunc_template.format(
        luadoc_comments,
        manager_name,
        pscol_name,
        param_names,
        database,
        pscol_name,
        param_count,
        lua_table_map
    )

def get_insert_method(manager_name : str, database : str, table : str, table_data : TableData) -> str:
    required_parameters = table_data.get_insert_parameters()

    luadoc_comments = "\n".join(
        [
            f"--- Inserter for table {table}."
        ] 
        + 
        [
            get_luadoc_comment(param_name, param_data)
            for param_name, param_data in required_parameters.items()
        ]
        +
        [
            f"---@return nil"
        ] 
    )
    param_count = len(required_parameters.keys())
    param_names = ", ".join(required_parameters.keys())
    pscol_name = get_insert_name(table)

    return sql_luafunc_template.format(
        luadoc_comments,
        manager_name,
        pscol_name,
        param_names,
        database,
        pscol_name,
        param_count
    )

def get_update_method(manager_name : str, database : str, table : str, primary_keys : dict[str, TableParam], param_name : str, param_data : TableParam) -> str:
    pscol_name = get_update_name(table, param_name)



    luadoc_comments = "\n".join(
        [
            f"--- Updates field \"{param_name}\" in {table}. {get_luadoc_desc(param_data)}"
        ] 
        +
        [
            f"{get_luadoc_comment(name, value)} (Lookup Key)"
            for name, value in primary_keys.items()
        ]
        +
        [
            get_luadoc_comment(param_name, param_data),
            f"---@return nil"
        ] 
    )




    return sql_luafunc_template.format(
        luadoc_comments,
        manager_name,
        pscol_name,
        f"{", ".join(primary_keys.keys())}, {param_name}",
        database,
        pscol_name,
        len(primary_keys) + 1
    )