name: Build & Deploy Lua Docs (luals-docs-gen + mdbook)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repository code
        uses: actions/checkout@v4
        with:
          path: repo_main

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: 'latest'

      - name: Setup luals_docs_gen
        run: |
          # Make sure execution path exists
          mkdir -p ~/.local/bin

          # Get latest mdbook version
          LUALS_VERSION=$(curl -s https://api.github.com/repos/emuell/luals-docs-gen/releases/latest | jq -r .tag_name)

          # get latest binary for linux
          curl -sSL "https://github.com/emuell/luals-docs-gen/releases/download/${LUALS_VERSION}/luals_docs_gen-linux_x86_64.zip" -o /tmp/luals_docs_gen.zip
          
          # Unzip luals binary into folder
          unzip /tmp/luals_docs_gen.zip -d ~/.local/bin
          chmod +x ~/.local/bin/luals_docs_gen
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Generate Markdown with luals-docs-gen
        run: |
          # Define absolute paths for clarity and robustness using GITHUB_WORKSPACE

          PROJECT_ROOT_ON_RUNNER="${GITHUB_WORKSPACE}/repo_main"

          LUA_SOURCE_PATH="${PROJECT_ROOT_ON_RUNNER}/Main"
          DOCS_OUTPUT_BASE_PATH="${PROJECT_ROOT_ON_RUNNER}/Docs/src"

          find "${LUA_SOURCE_PATH}" -type d

          # Run luals-docs-gen for our code
          luals_docs_gen -o by-class -n "forgeutils" "${LUA_SOURCE_PATH}" "${DOCS_OUTPUT_BASE_PATH}"

          cat "${DOCS_OUTPUT_BASE_PATH}/SUMMARY.md"

      - name: Build mdbook documentation
        run: |
          cd "${GITHUB_WORKSPACE}/repo_main/Docs"
          mdbook build

      - name: Check mdbook output
        run: |
          echo "Contents of Docs after build:"
          ls -l "${GITHUB_WORKSPACE}/repo_main/Docs"
          echo "Contents of book dir (if exists):"
          ls -l "${GITHUB_WORKSPACE}/repo_main/Docs/book" || echo "No book directory found"

      # Only upload 
      - name: Upload mdBook output as artifact
        if: github.event_name != 'pull_request'
        id: upload-pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: repo_main/Docs/book

  deploy:
    if: github.event_name != 'pull_request'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deploy-pages
        uses: actions/deploy-pages@v4

      - name: Debug deployed contents
        run: |
          echo "Deployed directory listing:"
          find .